image: registry.gitlab.com/spritely/guile-goblins:latest

stages:
  - build

unit-tests:
  stage: build
  script:
    - sh ./bootstrap.sh
    - ./configure
    - make distcheck
    # Check we can build the HTML docs
    - make html
    # Finally run make check and generate the JUnit report for Gitlab.
    - make check -j$(nproc)
    - make combine-junit-xml-results
  artifacts:
    reports:
      junit: 'test-results.xml'

perf-tests:
  stage: build
  script:
    - sh ./bootstrap.sh
    - ./configure
    - make -j$(nproc)
    - ./pre-inst-env guile --no-auto-compile -e main misc/perf-tests.scm > perf-metrics.txt
  artifacts:
    reports:
      metrics: 'perf-metrics.txt'
