on: [push]
jobs:
  no-tabs-please:
    runs-on: guix
    steps:
      - run: git clone --depth=1 --branch=$GITHUB_REF_NAME https://codeberg.org/$GITHUB_REPOSITORY src
      - run: |
          set -e
          FOUND_TABS=0
          find . -name \*.scm | xargs grep $'\t' && FOUND_TABS=1
          exit $FOUND_TABS
        shell: guix-ci -Df guix.scm -- {0}
        working-directory: src
        timeout-minutes: 5
  unit-tests:
    runs-on: guix
    steps:
      - run: git clone --depth=1 --branch=$GITHUB_REF_NAME https://codeberg.org/$GITHUB_REPOSITORY src
      - run: |
          set -e
          ./bootstrap.sh
          ./configure
          make -j${nproc}
          make run-tests
        shell: guix-ci -Df guix.scm -- {0}
        working-directory: src
        timeout-minutes: 15
  distcheck:
    runs-on: guix
    steps:
      - run: git clone --depth=1 --branch=$GITHUB_REF_NAME https://codeberg.org/$GITHUB_REPOSITORY src
      - run: |
          set -e
          ./bootstrap.sh
          ./configure
          make -j${nproc}
          make distcheck -j${nproc}
        shell: guix-ci -Df guix.scm -- {0}
        working-directory: src
        timeout-minutes: 15
  ocapn-test-suite:
    runs-on: guix
    steps:
      - run: git clone --depth=1 --branch=$GITHUB_REF_NAME https://codeberg.org/$GITHUB_REPOSITORY goblins
      - run: git clone --depth=1 https://github.com/ocapn/ocapn-test-suite.git
      - run: |
          set -e
          ./bootstrap.sh
          ./configure
          make -j${nproc}
          ./pre-inst-env guile tests/ocapn-test-suite.scm &> /dev/null &
          TEST_SUITE_PID=$!
          trap "kill $TEST_SUITE_PID || true" EXIT INT TERM
          cd ../ocapn-test-suite
          timeout 60 bash -c "until nc -z 127.0.0.1 24680; do sleep 1; done" || { echo "Goblins didn't start netlayer"; exit 1; }
          python3 ./test_runner.py --captp-version=goblins-0.16 "ocapn://guile-goblins.tcp-testing-only?host=127.0.0.1&port=24680"
        shell: guix shell -m manifest.scm python python-cryptography python-stem netcat -- {0}
        working-directory: goblins
        timeout-minutes: 15
  basic-hoot-check:
    runs-on: guix
    steps:
      - run: git clone --depth=1 --branch=$GITHUB_REF_NAME https://codeberg.org/$GITHUB_REPOSITORY src
      - run: |
          set -e
          ./bootstrap.sh
          ./configure
          make tests/hoot-ci/test-program.wasm
        shell: guix shell -m manifest.scm guile-next guile-hoot -- {0}
        working-directory: src
        timeout-minutes: 15
