The Goblins actor library, in the @code{(goblins actor-lib ...)}
module namespace, provides implementations for a variety of common
actor model patterns.

@menu
* Cell::
* Common::
* Facet::
* Joiners::
* Let-On::
* Methods::
* Nonce Registry::
* Opportunistic::
* Pubsub::
* Pushdown::
* Sealers::
* Simple Mint::
* Swappable::
* Ticker::
* Ward::
@end menu

@node Cell
@section Cell

The @code{(goblins actor-lib cell)} module provides a very handy actor
called a ``cell.''  Cells are used to store arbitrary data.  It also
provides some helper functions for cells.

@deffn {Constructor} ^cell bcom [val #f]

Construct an actor which contains @var{val} or @code{#f} if @var{val}
is not provided.

@lisp
> (define empty-chest (spawn ^cell))
> (define chest (spawn ^cell 'gold))
@end lisp

Cells have two possible invocations: with no arguments, which returns
the current value; and with one argument, which sets a new value and
returns nothing.

@lisp
> ($ chest)
=> 'gold
> ($ chest 'sword)
> ($ chest)
=> 'sword
@end lisp

@end deffn

@deffn {Procedure} cell->read-only cell

Create and return a read-only proxy to @var{cell}. It is an error to
attempt to write to such a cell.

@lisp
> (define ro-chest (cell->read-only chest))
> ($ chest)
=> 'sword
> ($ chest 'wand)
=> error: ...
@end lisp

@end deffn

@deffn {Procedure} cell->write-only cell

Create and return a write-only proxy to @var{cell}. It is an error to
attempt to read from such a cell.

@lisp
> (define wo-chest (cell->write-only chest))
> ($ chest 'wand)
> ($ chest)
=> error: ...
@end lisp

@end deffn

@deffn {Syntax} define-cell id [val #f]

Syntax for creating a cell using a form like Scheme @code{define}.

@lisp
> (define-cell chest 'gold)
> ($ chest)
=> 'gold
@end lisp

@end deffn

@node Common
@section Common

The @code{(goblins actor-lib common)} module provides actors wrapping
functional data structures, allowing Goblins transactionality
guarantees while providing an apparently mutable interface.

@deffn {Constructor} ^seteq bcom initial @dots{}

Construct an actor representing a set (each member is unique).  A
@code{seteq} has four methods:

@itemize
@item
@code{add val}: Add @var{val} to the set.

@item
@code{remove val}: Remove @var{val} from the set.

@item
@code{member? val}: Return @code{#t} if @var{val} is in the set, else
@code{#f}.

@item
@code{as-list}: Return a representation of the set as a Scheme list.
Note that the order of items in the list is not specified.

@end itemize

@lisp
> (define a-set (spawn ^seteq 'a 'b 'c))
> ($ a-set 'as-list)
=> (a b c)
> ($ a-set 'member? 'c)
=> #t
> ($ a-set 'member? 'f)
=> #f
> ($ a-set 'add 'f)
> ($ a-set 'remove 'b)
> ($ a-set 'as-list)
=> (f c a)
@end lisp

@end deffn

@deffn {Constructor} ^ghash bcom [ht ghash-null]

Construct an actor representing a hashtable using @code{eq?} for
key lookup and @code{equal?} for other comparisons.  @var{ht}, if
provided, is the underlying @code{ghash} to use as the starting state.
See @code{(goblins ghash)} module for the compatible hashtable
implementation.

A @code{ghash} actor has five methods:

@itemize
@item
@code{ref key [dflt #f]}: Return the value associated with @var{key},
or @var{dflt} if the key is not found.

@item
@code{set key val}: Add @var{key} to the @code{ghash} and associate it
with @var{val}.

@item
@code{has-key? key}: Return @code{#t} if @var{key} is in the
@code{ghash}; otherwise return @code{#f}.

@item
@code{remove key}: Delete @var{key} and its associated value from the
@code{ghash}.

@item
@code{data}: Return the underlying @code{ghash}.

@end itemize

@lisp
> (define ag (spawn ^ghash))
> ($ ag 'set "dog" "animal")
> ($ ag 'set "cesna" "plane")
> ($ ag 'data)
=> $<ghash (2)>
> ($ ag 'ref "cesna")
=> "plane"
> ($ ag 'has-key? "dog")
=> #t
> ($ ag 'remove "cesna")
> ($ ag 'ref "cesna")
=> #f
> ($ ag 'ref "cesna" 'missing)
=> missing
> ($ ag 'data)
=> $<ghash (1)>
@end lisp

@end deffn
