The Goblins actor library, in the @code{(goblins actor-lib ...)}
module namespace, provides implementations for a variety of common
actor model patterns.

@menu
* Cell::
* Common::
* Facet::
* Joiners::
* Let-On::
* Methods::
* Nonce Registry::
* Opportunistic::
* Pubsub::
* Pushdown::
* Sealers::
* Simple Mint::
* Swappable::
* Ticker::
* Ward::
@end menu

@node Cell
@section Cell

The @code{(goblins actor-lib cell)} module provides a very handy actor
called a ``cell.''  Cells are used to store arbitrary data.  It also
provides some helper functions for cells.

@deffn {Constructor} ^cell bcom [val #f]

Construct an actor which contains @var{val} or @code{#f} if @var{val}
is not provided.

@lisp
> (define empty-chest (spawn ^cell))
> (define chest (spawn ^cell 'gold))
@end lisp

Cells have two possible invocations: with no arguments, which returns
the current value; and with one argument, which sets a new value and
returns nothing.

@lisp
> ($ chest)
=> 'gold
> ($ chest 'sword)
> ($ chest)
=> 'sword
@end lisp

@end deffn
