This is the documentation for the core Goblins API. That is, this is
the documentation for everything imported with
@code{(use-modules (goblins))}.

@menu
* Objects::
* Vats::
* Actormaps::
@end menu

@node Objects
@section Objects

@menu
* Spawning objects::
* Synchronous invocation::
* Asynchronous invocation::
* Object reference predicates::
@end menu

@node Spawning objects
@subsection Spawning objects

Objects can be spawned with the @code{spawn} operator:

@deffn {Procedure} spawn constructor args @dots{}

Construct and return a reference to a new object.

@itemize
@item
@var{constructor}: Procedure which returns a procedure representing
the object's initial behavior; implicitly passed a first argument,
@ref{bcom}, which can be used to change the object's behavior.

@item
@var{args}: Remaining arguments passed to @var{constructor}.

@end itemize

For example, given the following constructor:

@lisp
(define* (^cell bcom #:optional val)  ; constructor (outer procedure)
  (case-lambda                        ; behavior    (inner procedure)
    (()                               ; 0-argument invocation (getter)
     val)                             ;   (return current value)
    ((new-val)                        ; 1-argument invocation (setter)
     (bcom (^cell bcom new-val)))))   ;   ("become" ^cell with new value)
@end lisp

The instantiation@dots{}

@lisp
(define some-cell (spawn ^cell 42))
@end lisp

will bind @code{val} to @code{42}.

@end deffn

@code{spawn} also has a few variants:

@deffn {Procedure} spawn-named name constructor args @dots{}

Like @code{spawn}, and set the object's debug name to @var{name}.

@end deffn

@deffn {Procedure} spawn-promise-values

Return a promise and its associated resolver.

@lisp
(define-values a-promise a-resolver (spawn-promise-values))
@end lisp

@end deffn

@deffn {Procedure} spawn-promise-cons

Return a promise and its associated resolver as a @code{cons} pair.

@lisp
(define promise-pair (spawn-promise-cons))
(define a-promise (car promise-pair))
(define a-resolver (cdr promise-pair))
@end lisp

@end deffn

@node Synchronous invocation
@subsection Synchronous invocation

Relative to a given @emph{vat}, there are two types of objects.  A
@dfn{near} object is in the @emph{vat}.  A @dfn{far} object is in a
different @emph{vat}.  Similarly, there are two ways to invoke objects:
@dfn{synchronous}ly, or using traditional call-return, which only
works for @emph{near} objects; or @dfn{asynchronous}ly, which works for
either @emph{near} or @emph{far} objects, and usually returns a
@emph{promise}. @emph{Synchronous} and @emph{asynchronous} invocation
use different but similar procedures.

@deffn {Procedure} $ to-refr args @dots{}

Call a @ref{near} object's behavior and return the result.

@itemize
@item
@var{to-refr}: @ref{Near} object to call.

@item
@var{args}: Arguments to the object's behavior.  If @var{to-refr}
has @ref{methods}, the first argument will conventionally be a symbol
indicating the behavior/method to be invoked.

@end itemize

@lisp
(define object-a (spawn ^some-object))
;; in the same vat
(define a-val ($ object-a arg1))
(define b-val ($ object-a 'some-method arg2))
@end lisp

@end deffn

@node Asynchronous invocation
@subsection Asynchronous invocation

@deffn {Procedure} <- to-refr args @dots{}

Like @code{$}, but @var{to-refr} may be @ref{near} or @ref{far}, and
@code{<-} returns a promise instead of a result.

@lisp
(define object-a (spawn ^some-object))
;; in a different vat... or the same; it doesn't matter to <-
(define a-promise (<- object-a arg1))
(define b-promise (<- object-a 'some-method arg2))
@end lisp

@end deffn

@code{<-} has a variant that does not return a promise:

@deffn {Procedure} <-np to-refr args @dots{}

Like @code{<-}, but return @code{void} instead of a promise.

@lisp
(define object-a (spawn ^some-object))
;; in a different vat... or the same; it doesn't matter to <-np
(<-np object-a arg1)                ; returns void
(<-np object-a 'some-method arg2)   ; returns void
@end lisp

@end deffn

@deffn {Procedure} <-np-extern to-refr args @dots{}

Like @code{<-np}, but only operate on @ref{far} objects.

@end deffn

@deffn {Procedure} on vow [fulfilled-handler #f]
       [#:catch #f] [#:finally #f] [#:promise? #f]

Respond to a promise, optionally with error handling.  Return nothing
unless @var{promise?} is @code{#t}, in which case return a promise.

@itemize
@item
@var{vow}: Promise to which to respond.

@item
@var{fulfilled-handler}: Procedure called with the result of @var{vow}
if it is fulfilled.

@item
@var{catch}: Procedure invoked on an error; passed one argument, the
exception object.

@item
@var{finally}: Procedure invoked on success or failure after the
appropriate handler.

@end itemize

@lisp
;; in the context of some vat
(define object-a (spawn ^some-object))
;; in the context of some vat, possibly different
(on (<- object-a arg1)
    (lambda (val)
      (some-proc val))
    #:catch
    (lambda (err)
      (handle-err err))
    #:finally
    (lambda _
      (other-proc))
    #:promise? #f)      ; the default, written out for demonstration
@end lisp

@end deffn

You can also wait for the resolution of a promise without necessarily
responding:

@deffn {Procedure} listen-to to-refr listener [#:wants-partial? #f]

Wait for @var{to-refr} to resolve, then inform @var{listener}.  If
@var{wants-partial?} is @code{#t}, return updates rather than waiting
for full promise resolution.

@end deffn

@node Object reference predicates
@subsection Object reference predicates

Goblins comes with a variety of predicates for identifying and working
with objects.  While these are primarily for internal use, they are
also helpful when defining custom @ref{vat} code.

@deffn {Procedure} local-object-refr? obj

Return @code{#t} if @var{obj} is an object in the current process,
else @code{#f}.

@end deffn
