This is the documentation for the core Goblins API. That is, this is
the documentation for everything imported with
@code{(use-modules (goblins))}.

@menu
* Objects::
* Vats::
* Actormaps::
@end menu

@node Objects
@section Objects

@menu
* Spawning objects::
* Synchronous invocation::
* Asynchronous invocation::
* Object reference predicates::
@end menu

@node Spawning objects
@subsection Spawning objects

Objects can be spawned with the @code{spawn} operator:

@deffn {Procedure} spawn constructor args @dots{}

Construct and return a reference to a new object.

@itemize
@item
@var{constructor}: Procedure which returns a procedure representing
the object's initial behavior; implicitly passed a first argument,
@ref{bcom}, which can be used to change the object's behavior.

@item
@var{args}: Remaining arguments passed to @var{constructor}.

@end itemize

For example, given the following constructor:

@lisp
(define* (^cell bcom #:optional val)  ; constructor (outer procedure)
  (case-lambda                        ; behavior    (inner procedure)
    (()                               ; 0-argument invocation (getter)
     val)                             ;   (return current value)
    ((new-val)                        ; 1-argument invocation (setter)
     (bcom (^cell bcom new-val)))))   ;   ("become" ^cell with new value)
@end lisp

The instantiation@dots{}

@lisp
(define some-cell (spawn ^cell 42))
@end lisp

will bind @code{val} to @code{42}.

@end deffn

@code{spawn} also has a few variants:

@deffn {Procedure} spawn-named name constructor args @dots{}

Like @code{spawn}, and set the object's debug name to @var{name}.

@end deffn

@deffn {Procedure} spawn-promise-values

Return a promise and its associated resolver.

@lisp
(define-values a-promise a-resolver (spawn-promise-values))
@end lisp

@end deffn

@deffn {Procedure} spawn-promise-cons

Return a promise and its associated resolver as a @code{cons} pair.

@lisp
(define promise-pair (spawn-promise-cons))
(define a-promise (car promise-pair))
(define a-resolver (cdr promise-pair))
@end lisp

@end deffn

@node Synchronous invocation
@subsection Synchronous invocation

Relative to a given @emph{vat}, there are two types of objects.  A
@dfn{near} object is in the @emph{vat}.  A @dfn{far} object is in a
different @emph{vat}.  Similarly, there are two ways to invoke objects:
@dfn{synchronous}ly, or using traditional call-return, which only
works for @emph{near} objects; or @dfn{asynchronous}ly, which works for
either @emph{near} or @emph{far} objects, and usually returns a
@emph{promise}. @emph{Synchronous} and @emph{asynchronous} invocation
use different but similar procedures.

@deffn {Procedure} $ to-refr args @dots{}

Call a @ref{near} object's behavior and return the result.

@itemize
@item
@var{to-refr}: @ref{Near} object to call.

@item
@var{args}: Arguments to the object's behavior.  If @var{to-refr}
has @ref{methods}, the first argument will conventionally be a symbol
indicating the behavior/method to be invoked.

@end itemize

@lisp
(define object-a (spawn ^some-object))
;; in the same vat
(define a-val ($ object-a arg1))
(define b-val ($ object-a 'some-method arg2))
@end lisp

@end deffn

@node Asynchronous invocation
@subsection Asynchronous invocation

@deffn {Procedure} <- to-refr args @dots{}

Like @code{$}, but @var{to-refr} may be @ref{near} or @ref{far}, and
@code{<-} returns a promise instead of a result.

@lisp
(define object-a (spawn ^some-object))
;; in a different vat... or the same; it doesn't matter to <-
(define a-promise (<- object-a arg1))
(define b-promise (<- object-a 'some-method arg2))
@end lisp

@end deffn

@code{<-} has a variant that does not return a promise:

@deffn {Procedure} <-np to-refr args @dots{}

Like @code{<-}, but return @code{void} instead of a promise.

@lisp
(define object-a (spawn ^some-object))
;; in a different vat... or the same; it doesn't matter to <-np
(<-np object-a arg1)                ; returns void
(<-np object-a 'some-method arg2)   ; returns void
@end lisp

@end deffn

@deffn {Procedure} <-np-extern to-refr args @dots{}

Like @code{<-np}, but only operate on @ref{far} objects.

@end deffn

@deffn {Procedure} on vow [fulfilled-handler #f]
       [#:catch #f] [#:finally #f] [#:promise? #f]

Respond to a promise, optionally with error handling.  Return nothing
unless @var{promise?} is @code{#t}, in which case return a promise.

@itemize
@item
@var{vow}: Promise to which to respond.

@item
@var{fulfilled-handler}: Procedure called with the result of @var{vow}
if it is fulfilled.

@item
@var{catch}: Procedure invoked on an error; passed one argument, the
exception object.

@item
@var{finally}: Procedure invoked on success or failure after the
appropriate handler.

@end itemize

@lisp
;; in the context of some vat
(define object-a (spawn ^some-object))
;; in the context of some vat, possibly different
(on (<- object-a arg1)
    (lambda (val)
      (some-proc val))
    #:catch
    (lambda (err)
      (handle-err err))
    #:finally
    (lambda _
      (other-proc))
    #:promise? #f)      ; the default, written out for demonstration
@end lisp

@end deffn

You can also wait for the resolution of a promise without necessarily
responding:

@deffn {Procedure} listen-to to-refr listener [#:wants-partial? #f]

Wait for @var{to-refr} to resolve, then inform @var{listener}.  If
@var{wants-partial?} is @code{#t}, return updates rather than waiting
for full promise resolution.

@end deffn

@node Object reference predicates
@subsection Object reference predicates

Goblins comes with a variety of predicates for identifying and working
with objects.  While these are primarily for internal use, they are
also helpful when defining custom @ref{vat} code.

@deffn {Procedure} local-object-refr? obj

Return @code{#t} if @var{obj} is an object in the current process,
else @code{#f}.

@end deffn

@deffn {Procedure} local-promise-refr? obj

Return @code{#t} if @var{obj} is a promise in the current process,
else @code{#f}.

@end deffn

@deffn {Procedure} local-refr? obj

Return @code{#t} if @var{obj} is an object or promise in the current
process, else @code{#f}.

@end deffn

@deffn {Procedure} remote-object-refr? obj

Return @code{#t} if @var{obj} is an object in a different process,
else @code{#f}.

@end deffn

@deffn {Procedure} remote-promise-refr? obj

Return @code{#t} if @var{obj} is a promise in a different process,
else @code{#f}.

@end deffn

@deffn {Procedure} remote-refr? obj

Return @code{#t} if @var{obj} is an object or promise in a different
process, else @code{#f}.

@end deffn

@deffn {Procedure} promise-refr? maybe-promise

Return @code{#t} if @var{maybe-promise} is a local or remote promise,
else @code{#f}.

@end deffn

@deffn {Procedure} live-refr? obj

Return @code{#t} if @var{obj} is a local or remote object or promise,
else @code{#f}.

@end deffn

@deffn {Procedure} near-refr? obj

Return @code{#t} if @var{obj} is a @ref{near} object or promise, else
@code{#f}.

@end deffn

@deffn {Procedure} far-refr? obj

Return @code{#t} if @var{obj} is a @ref{far} object or promise, else
@code{#f}.

@end deffn

@node Vats
@section Vats

A @dfn{vat} is an event loop that manages a set of objects which are
@ref{near} to each other. They are one of the central abstractions of
Spritely Goblins facilitating the object capabilities security model
as well as transactionality and distributed programming. All Goblins
objects live inside a @ref{vat}.

@menu
* Making vats::
* Using vats::
@end menu

@node Making vats
@subsection Making vats

At a high level, users generally will spawn a @ref{vat}, bind it to a
name in the local namespace, and use it for various operations. This
will usually use @code{spawn-vat}:

@deffn {Procedure} spawn-vat [#:name] [#:log?]
       [log-capacity]

Create and return a reference to a new @ref{vat}.

@itemize
@item
@var{name}: Name of the vat.  Note that this is @emph{not} the name it is
bound to in the current namespace.

@item
@var{log?}: If @code{#t}, log @ref{vat} events; otherwise, do not.

@item
@var{log-capacity}: Number of events to be retained in the log.
Defaults to 256.

@end itemize

@lisp
(define a-vat (spawn-vat))
@end lisp

@end deffn

Sometimes, it is useful to make and manage a @ref{vat} at a slightly
lower level. In such cases, @code{make-vat} comes into play:

@deffn {Procedure} make-vat [#:name] [#:start] [#:halt] [#:send]
       [#:log?] [log-capacity]

Return a new vat named @var{name}.  Vat behavior is determined by
three event hooks, and logging is controlled by the remaining
arguments:

@itemize
@item
@var{start}: Procedure to start @ref{vat} process in non-blocking
manner such as a new thread.  Accepts a procedure which takes a
message as its single argument and churns the underlying
@ref{actormap} for the @ref{vat}.

@item
@var{halt}: Thunk to stop @ref{vat} process.

@item
@var{send}: Procedure accepting a message to handle within the
@ref{vat} process and a boolean indicating if the message result
needs to be returned to sender.

@item
@var{log?}: If @code{#t}, event logging is enabled, otherwise it is
disabled (the default).

@item
@var{log-capacity}: Number of events to be retained in the log.
Defaults to 256.

@end itemize

@end deffn

@node Using vats
@subsection Using vats

Regardless of whether a @ref{vat} is standard or custom, there are
several procedures supporting their use.

@deffn {Procedure} vat? obj

Return @code{#t} if @var{obj} is a @ref{vat}, else @code{#f}.

@end deffn

@deffn {Procedure} vat-name vat

Return the name of @var{vat}.

@end deffn

@deffn {Procedure} vat-running? vat

Return @code{#t} if @var{vat} is running, else @code{#f}.

@end deffn

@deffn {Procedure} vat-halt! vat

Stop processing @ref{turn}s for @var{vat}.

@end deffn

@deffn {Procedure} vat-start! vat

Start processing @ref{turn}s for @var{vat}.

@end deffn

@deffn {Procedure} call-with-vat vat thunk

Run @var{thunk} in the context of @var{vat} and return the resulting
values.

@lisp
(define a-vat (spawn-vat))
(call-with-vat a-vat
  (lambda ()
    (define an-object (spawn ^some-object))
    ($ an-object 'a-message an-arg)))
@end lisp

@end deffn

@deffn {Syntax} with-vat vat body @dots{}

Execute @var{body} in the context of @var{vat} and return the result.
This is syntax for @code{call-with-vat} so the user does not have to
write a separate lambda expression.

@end deffn

@deffn {Syntax} define-vat-run vat-run-id [vat (spawn-vat)]

This procedure is deprecated.

Return a procedure bound to @var{vat-run-id} accepting a body to be
evaulated in the context of @var{vat}.

@lisp
(define-vat-run run-in-vat)
(run-in-vat
  (define a-near-object (spawn ^some-object))
  (<- a-far-object 'some-message an-arg)
  ($ a-near-object 'some-message))
@end lisp

@end deffn

@node Actormaps
@section Actormaps

An @dfn{actormap} is the transactional data structure underlying
@ref{vat}s. They are useful for building a custom event loop (such as
for a video game) or as a synchronous one-turn-at-a-time mapping of
actor references to their current behaviors.

@deffn {Procedure} make-whactormap [#:vat-connector #f]

Return a reference to a new @ref{whactormap}.  @var{vat-connector}, if
provided, is the @ref{syscaller} for the containing @ref{vat}.

@end deffn

@deffn {Procedure} make-actormap

Return a reference to a new @ref{actormap}.  This is a convenience
wrapper around @code{make-whactormap}.

@lisp
(define an-actormap (make-actormap))
@end lisp

@end deffn

@deffn {Procedure} make-transactormap parent

Return a reference to a new @ref{transactormap} with @var{parent} as
its preceding generation.

@end deffn

@deffn {Procedure} actormap-spawn actormap actor-constructor args @dots{}

Spawn an actor inside @var{actormap}, but do not commit the
transaction.  Return a reference to the spawned object and a
@emph{transactormap}.

@itemize
@item
@var{actor-constructor}: Constructor for the actor to be spawned.

@item
@var{args}: Arguments to @var{actor-constructor}.

@end itemize

@end deffn

@deffn {Procedure} actormap-spawn! actormap actor-constructor args @dots{}

Like @code{actormap-spawn}, but do commit the transaction.

@end deffn

@deffn {Procedure} actormap-turn* actormap to-refr args

Perform a single turn in @var{actormap} by invoking @var{to-refr}
with the list of arguments @var{args}.  Return the result of the
invoked behavior, a new @emph{actormap}, and a list of new messages
generated by the turn.

@end deffn

@deffn {Procedure} actormap-turn actormap to-refr args @dots{}

Like @code{actormap-turn*}, but create a new generation of
transaction with @var{actormap} as the parent and operate in it
instead.

@end deffn

@deffn {Procedure} actormap-turn-message actormap msg
       [#:error-handler simple-display-error] [#:reckless? #f]
       [#:catch-errors? #t]

Return the result of @var{msg} in the context of @var{actormap}.
How to handle errors and transactions is controlled by keyword args:

@itemize
@item
@var{error-handler}: Procedure to handle errors.  It is passed
@var{msg}, the error, and the stack at the time of the error.

@item
@var{reckless?}: If @code{#t}, operate within @var{actormap} instead
of creating a new generation; otherwise, create a new generation.

@item
@var{catch-errors?}: If @code{#t}, capture the stack and abort to a
prompt; otherwise, propagate the error.

@end itemize

@end deffn

@deffn {Procedure} actormap-peek actormap to-refr args @dots{}

Perform a turn in @var{actormap} only to return the results; do not
commit the transaction to the transaction history.

@itemize
@item
@var{to-refr}: Object to be invoked.

@item
@var{args}: Arguments passed to @var{to-refr}.

@end itemize

@end deffn

@deffn {Procedure} actormap-poke! actormap to-refr args @dots{}

Perform a turn in @var{actormap} and commit the results, but ignore
any messages generated by it.  Return the results.

@itemize
@item
@var{to-refr}: Object to be invoked.

@item
@var{args}: Arguments passed to @var{to-refr}.

@end itemize

@end deffn

@deffn {Procedure} actormap-reckless-poke! actormap to-refr args @dots{}

Like @code{actormap-poke!}, but commit the results to the current
transaction generation without creating a new one.  This voids
Goblin's transactionality guarantees like time travel.

@end deffn

@deffn {Procedure} actormap-run actormap thunk

Execute @var{thunk} in @var{actormap}, but do not commit the results.
Return the results.

@end deffn

@deffn {Procedure} actormap-run! actormap thunk [#:reckless? #f]

Like @code{actormap-run}, and commit the results.  If @var{reckless?}
is @code{#t}, do not create a new generation for the turn.

@end deffn

@deffn {Procedure} actormap-run* actormap thunk

Like @code{actormap-run}, and return a reference to the new
@emph{actormap} as well as any messages generated.

@end deffn

@deffn {Procedure} actormap-churn am msg [#:catch-errors? #t]
       [#:make-transactormap? #t]

Perform every turn in @var{am} possible without needing to invoke
@emph{far} objects to resolve @var{msg}, then dispatch messages to
the appropriate @emph{far} objects.

@itemize
@item
@var{catch-errors?}: If @code{#f}, do not handle errors.

@item
@var{make-transactormap?}: If @code{#f}, operate and commit in
@var{am} instead of creating a new generation.

@end itemize

@end deffn

@deffn {Procedure} actormap-churn-run actormap thunk
       [#:catch-errors? #t]

Evaluate @var{thunk} in the context of @var{actormap}, performing all
possible local invocations to resolve @var{thunk}.  If
@code{catch-errors?} is @code{#f}, do not handle errors.  Return the
results, a reference to the new actormap, and any messages generated.

@end deffn

@deffn {Procedure} actormap-churn-run! actormap thunk
       [#:catch-errors? #t]

Like @code{actormap-churn-run}, but dispatch messages and only return
the results of the @emph{churn}.

@end deffn
