#+TITLE: Spritely Goblins
#+AUTHOR: Christine Lemmer-Webber
#+SUBAUTHOR: The Spritely Institute
#+EMAIL: christine@spritely.institute

#+OPTIONS: ':t toc:t author:t email:t
#+LANGUAGE: en

#+TEXINFO_FILENAME: goblins.info
#+TEXINFO_HEADER: @syncodeindex pg cp

#+TEXINFO_DIR_CATEGORY: The Algorithmic Language Scheme

#+TEXINFO_DIR_TITLE: Goblins: (goblins)
#+TEXINFO_DIR_DESC: Distributed programming environment and Spritely's core (Guile edition).

This is the manual for [[https://spritelyproject.org/#goblins][Spritely Goblins]], a distributed object
programming environment.
Spritely Goblins is a project of the [[https://spritely.institute/][Spritely Institute]] and is
built to be the core layer for building Spritely's broader
decentralized networking technologies.

Both this manual and Guile Goblins itself are released under
Apache v2.  See [[* License][License]] for more information.

* What is Goblins?

[[https://spritelyproject.org/#goblins][Spritely Goblins]] is a distributed object programming environment.
Features:

 - *Quasi-functional object system:*
   Users hold on to references of objects/actors, but objects/actors
   are just procedures.
   Rather than directly mutating, objects/actors can specify that
   they should "become" a new version of themselves when they
   handle the next invocation.

 - *Fully distributed, networked, secure p2p communication:*
   Via OCapN, the Object Capability Network (which features CapTP, the
   Capability Transport Protocol), you can communicate with other
   objects over a network connection.  Distributed object interactions
   are safe because of ocap security guarantees.

 - *Transactional updates:*
   Changes happen within a transaction.
   If an unhandled exception occurs, we can "roll back" history
   as if the message never happened, avoiding confused state
   changes throughout the system.

 - *Time travel:*
   We can snapshot old revisions of the system and
   interact with them.

 - *Asynchronous programming with sophisticated promise chaining:*
   Asynchronous message passing with promises is supported.
   Promises work such that there's no need to wait for promises
   to resolve before interacting... you can communicate with the
   future that doesn't even yet exist!
   Sent a message to that remote car factory asking for a new car?
   Why wait for the car to be delivered... you can send it a
   drive message at the same time, and both messages can be
   delivered across the network in a single hop.

 - *Communicating event loops:*
   Objects across multiple event loops (aka "vats") can
   communicate, whether in the same OS process or (soon) across
   the network.

 - *Synchronous and asynchronous behavior, integrated but distinguished:*
   Both synchronous and asynchronous programming is supported,
   but only objects in the same "vat" (event loop) can perform
   synchronous immediate calls.
   All objects can perform asynchronous calls against each other.

 - *A library, not a language:*
   Goblins is itself a library that can be utilized across a wide
   variety of Guile programs.

 - *Object capability security:*
   Goblins itself is built for object capability (ocap) security,
   which is to say that you can only operate on the references
   you have access to.
   Goblins embraces and builds upon this foundation.
   (However, full ocap security will require utilizing the
   sandboxing features of Guile; demonstrations of this coming soon.)


Goblins' design is inspired by the [[http://www.erights.org/][E programming language]] and by the
observation that [[http://mumble.net/~jar/pubs/secureos/secureos.html][lambda is already the ultimate security mechanism]]
(ie, normal argument-passing in programs, if taken seriously/purely,
is already all the security system we need).

Spritely is a wider project to advance decentralized networking
infrastructure, particularly as it pertains to social networks.
Goblins is the heart of the system, on which other layers are built.
At the time of writing, two key versions of Goblins are supported, the
[[https://docs.racket-lang.org/goblins/index.html][Racket version of Goblins]], and the [[https://www.gnu.org/software/guile/][Guile]] version.
This manual is for the Guile edition of Spritely Goblins.

This manual is also very, very incomplete in this early release.
Please see the [[https://docs.racket-lang.org/goblins/][manual for the Racket version of Goblins]] manual,
most of which applies to the Guile version too.

[fn:on-actors-and-objects] Goblins uses the term "object" and "actor"
somewhat interchangably, even though in some ways these terms have
become vague.  There are, in particular,
[[http://mumble.net/~jar/articles/oo.html][many meanings for the word "object"]]; for us, object really means an
encapsulation of behavior and state.  (In Goblins, state is typically
built out of behavior, not the other way around.)
Goblins also follows the [[https://en.wikipedia.org/wiki/Actor_model#Fundamental_concepts][classic actor]] model mostly, in that
in response to a message, an "actor" can:
(a) send a finite number of messages to other actors;
(b) create a finite number of new actors; or
(c) designate the behavior to be used for the next message it receives.
However, Goblins supports both synchronous call-return invocation of
actors within the same event loop via =$= and asynchronous message
sends via =<-=.  Arguably the true "classic actor" model only supports
the latter.

* Getting started

** Installing Goblins

You'll need to install =guile-goblins=.  Either use [[https://guix.gnu.org/][Guix]] or use your
standard GNU/Linux distro's package for =guile-goblins= (if it exists)
or even better yet run Guix as your standard distro.

See the =HACKING= and =README= files with git checkouts / release
tarballs otherwise to install.

** Setup for hacking on Goblins

You're going to want/need:

 - [[https://www.gnu.org/software/emacs/][GNU Emacs]]
 - [[https://www.nongnu.org/geiser/][Geiser]], for hacking on Guile

Then, at minimum, you'll want to put in your .emacs:

#+BEGIN_SRC emacs-lisp
(show-paren-mode 1)  ; Match parentheses
#+END_SRC

However you probably also want some combination of:

 - [[https://github.com/Fuco1/smartparens][smartparens]] (or [[https://www.emacswiki.org/emacs/ParEdit][paredit]], which is much more strict... use
   smartparens if uncertain)
 - [[https://github.com/Fanael/rainbow-delimiters][rainbow-delimeters]]
 - [[https://www.emacswiki.org/emacs/HighlightParentheses][highlight-parentheses]]

Now you'll have a nice hacking setup!  Be sure to read the Geiser
manual.

** TEMPORARY: Live hacking "fix"

The traditional way to hack Guile is to use Geiser, both evaluating
from some =foo.scm= file/buffer with more "permanent" code via, for
example, the =C-x C-e= / =C-x C-b= / =C-x C-k= commands to evaluate an
expression, evaluate a whole buffer, or compile a buffer's content,
and switching back and forth between that and the (usually called
=*Geiser Guile REPL*=) experimental-hacking-and-debugging REPL.

This works with Goblins, but Geiser does some things to temporarily
redirect output/error ports when doing the file/buffer oriented
evaluation, and unfortunately this results in Goblins vats potentially
breaking due to spawning a separate thread which inherit these
temporarily redirected ports, which then are closed when the
evaluation succeeds.  We have a long-term plan to deal with this, but
in the meanwhile, whenever you start a Guile / Geiser hacking session,
first execute:

#+BEGIN_SRC scheme
  > (use-modules (goblins))
#+END_SRC

... from the =*Geiser Guile REPL*=.  Otherwise vats may mysteriously
"hang".  We know this is an annoyance!  It'll be fixed soon!


* A high level view of Goblins

Let's start with a sketch of a network of Goblins objects wired
to communicate with each other:

#+BEGIN_SRC text
  .----------------------------------.         .----------------------.
  |            Machine 1             |         |       Machine 2      |
  |            =========             |         |       =========      |
  |                                  |         |                      |
  | .--------------.  .---------.   .-.       .-.                     |
  | |    Vat A     |  |  Vat B  |   |  \______|  \_   .------------.  |
  | |  .---.       |  |   .-.   | .-|  /      |  / |  |    Vat C   |  |
  | | (Alice)----------->(Bob)----' '-'       '-'  |  |  .---.     |  |
  | |  '---'       |  |   '-'   |    |         |   '--->(Carol)    |  |
  | |      \       |  '----^----'    |         |      |  '---'     |  |
  | |       V      |       |         |         |      |            |  |
  | |      .----.  |       |        .-.       .-.     |  .------.  |  |
  | |     (Alfred) |       '-------/  |______/  |____---( Carlos ) |  |
  | |      '----'  |               \  |      \  |     |  '------'  |  |
  | |              |                '-'       '-'     '------------'  |
  | '--------------'                 |         |                      |
  |                                  |         |                      |
  '----------------------------------'         '----------------------'
#+END_SRC

In the above diagram, we see:

 - Two machines (=Machine 1= and =Machine 2=, running separately from
   each other, but connected to each other over the network via OCapN
   and CapTP.

 - =Vat A= and =Vat B= are event loops which live on =Machine 1=,
   and =Vat C= is an event loop which live son =Machine 2=.

 - The individual objects (represented by circles) live in /vats/,
   aka event loops which contain objects.  =Alice= and
   =Alfred= live in =Vat A=, =Bob= lives in =Vat B=, and =Carol= and
   =Carlos= live on =Vat C=.  (While we've given these objects
   human-like names, they're just Goblins objects.)

 - The arrows between the objects represent references these objects
   have to each other.  =Alice= has references to both =Alfred= and
   =Bob=.  =Bob= has a reference to =Carol=.  =Carlos= has a reference
   to =Bob=.

 - Two objects which are in the same vat are considered /near/ each
   other, and thus can invoke each other synchronously, whereas any
   objects not in the same vat are considered /far/ from each other.
   Any objects can invoke each other by asynchronous message
   passing... assuming they have a reference to each other.

 - Not pictured: each vat has an /actormap/, an underlying
   transactional heap used for object communication.  This is what
   permits transactionality and time travel.  (Actormaps can also used
   independently of vats for certain categories of applications.)

Another way to think about this is via the following abstraction
nesting dolls:

#+BEGIN_SRC scheme
  (machine (vat (actormap {refr: object-behavior})))
#+END_SRC

 - *Machines*, which are computers on the network, or more
   realistically, operating system processes, which contain...
 - *Vats*, which are communicating event loops, which contain...
 - *Actormaps*, transactional heaps, which contain...
 - A mapping of *References* to *Object Behavior*.

** The "vat model" of computation

As said, Goblins follows what is called the /vat model/ of
computation.
A /vat/ is simply an event loop that manages a set of
objects which are /near/ to each other (and similarly, objects outside
of a vat are /far/ from each other).

Objects which are /near/ can perform synchronous call-return
invocations in a manner familiar to most sequential programming
languages used by most programmers today.  Aside from being
a somewhat more convenient way to program, sequential invocation
is desirable because of cheap /transactionality/, which we shall
expand on more later.  In Goblins, we use the =$= operator
to perform synchronous operations.

Both /near/ and /far/ objects are able to invoke each other
asynchronously using asynchronous message passing (in the same style
as the /classic actor model/).  It does not
generally matter whether or not a /far/ object is running within the
same OS process or machine or one somewhere else on the
network for most programming tasks; asynchronous
message passing works the same either way.  In Goblins, we use the
=<-= operator to perform asynchronous operations.
# [fn:classic-actors] [fn:session-severance]

For both programmer convenience and for networked efficiency, Goblins
supports /promise pipelining/: messages can be sent to promises which
have not yet resolved, and will be forwarded to the target once the
promise resolves.
The sender of the message is handed back a promise to which it can
supply callbacks, listening for the promise to be fulfilled with a
value or broken (usually in case of an unexpected error).
# [fn:full-promise-vision]

As usual in the vat model of computation, individual message sends to
a vat (event loop) are queued and then handled one /turn/ at a time,
akin to the way board game players take turns around a table (which is
indeed the basis for the term /turn/).

The message, addressing a specific object, is passed to the recipient
object's current behavior.  This object may then invoke other
/near/ objects (residing within the same vat), which may themselves
invoke other near objects in a synchronous and sequential call-return
style familiar to most users of most contemporary programming
languages.  Any of these invoked objects may also change their
state/behavior (behavior changes appear purely functional in Goblins;
invocations of other actors do not), spawn new objects, invoke
ordinary expressions from the host language, or send asynchronous
messages to other objects (which are only sent if the /turn/ completes
successfully).

While the /vat model/ of computation is not new (it originates in the
[[http://erights.org/][E]] programming language and can trace some of its ideas back to E's
predecessor [[http://erights.org/history/joule/][Joule]], and has since reappeared in systems such as
[[https://agoric.com/][Agoric's]] [[https://github.com/Agoric/agoric-sdk/tree/master/packages/SwingSet][SwingSet]] kernel), Goblins brings some novel contributions to
the table in terms of transactionality and time-travel debugging,
enhancing an already powerful distributed programming paradigm.

* Tutorial

** A simple greeter

First, let's import Goblins:

#+BEGIN_SRC scheme
  > (use-modules (goblins))
#+END_SRC

(*NOTE*: See [[*TEMPORARY: Live hacking "fix"][TEMPORARY: Live hacking "fix"]] if you haven't.)

Goblins actors live in special event loops called /vats/.
Let's make a vat to play around with and "enter" it at the REPL:

#+BEGIN_SRC scheme
scheme> (define a-vat (spawn-vat))
scheme> ,enter-vat a-vat
goblins[1]>
#+END_SRC

Now let us implement a friend who will greet us:

#+BEGIN_SRC scheme
(define (^greeter bcom our-name)   ; constructor (outer procedure)
  (lambda (your-name)              ; behavior    (inner procedure)
    (format #f "Hello ~a, my name is ~a!"
            your-name our-name)))
#+END_SRC

Let's give it a try by instantiating an instance of =^greeter= using
=spawn= and assign her to the variable =alice=:

#+BEGIN_SRC scheme
 > (define alice
     (spawn ^greeter "Alice"))
#+END_SRC

The first argument to =spawn= is the constructor we will use to make
our Goblins object, in this case =^greeter=.
The remaining arguments will be passed to the constructor,
along with an implicit argument which can be used to change object
behavior called =bcom= (pronounced "become").
Thus ="Alice"= maps to =our-name=.

We can invoke =alice= by using =$= for a synchronous call-return
operation:

#+BEGIN_SRC scheme
goblins[1]> (define alice
              (spawn ^greeter "Alice"))
goblins[1]> ($ alice "Alfred")
; => "Hello Alfred, my name is Alice!"
#+END_SRC

The first argument to =$= is the object to be invoked, the remaining
arguments are passed to the "behavior" of the object.
Thus =your-name= in =^greeter='s behavior procedure is bound to
="Alfred"=.
The behavior procedure thus proceeds with formatting and returning the
greeting string.

We can exit the subrepl for =a-vat= with =,q= (the same way as if
Guile put us in a subrepl to debug an error):

#+BEGIN_SRC scheme
goblins[1]> ,q
scheme>
#+END_SRC

As you have probably inferred, Goblins-specific operations such as =$=
and =spawn= happen within a context (typically a /vat/, though there is
an even lower-level structure called an /actormap/ which we will see
more about later).
However, the subrepl entered by =,enter-vat= is a convenience for
hacking.
We can run also run code within =a-vat= like so:

#+BEGIN_SRC scheme
  scheme> (a-vat (lambda () ($ alice "Arthur")))
  ; => "Hello Arthur, my name is Alice!"
#+END_SRC

Very few operations in Goblins spend time operating on vats directly;
typically commands like the above only happen when bootstrapping the
initial set of actors within a vat or when hacking, then the actors
within the vats do their own thing.

** State as updating behavior

Re-enter =a-vat='s subrepl if you haven't:

#+BEGIN_SRC scheme
scheme> ,enter-vat a-vat
goblins[1]>
#+END_SRC

Let's introduce a simple cell which stores a value.
This cell will have two methods:
='get= retrieves the current value, and ='set= replaces
the current value with a new value.

#+BEGIN_SRC scheme
(define* (^cell bcom #:optional [val #f])
  (case-lambda
    (()         ; get
     val)
    ((new-val)  ; set
     (bcom (^cell bcom new-val)))))
#+END_SRC

=case-lambda= allows for dispatching depending on the number of
arguments, so here we're choosing that if no arguments are provided,
our cell shares the current value, and if one argument is provided,
the cell updates itself to become a cell storing the new value.

Cells hold values, and so do treasure chests, so let's make
a treasure chest flavored cell.
Taking things out and putting them back in is easy:

#+BEGIN_SRC scheme
  goblins[1]> (define chest
                (spawn ^cell "sword"))
  goblins[1]> ($ chest)
  ; => "sword"
  goblins[1]> ($ chest "gold")
  goblins[1]> ($ chest)
  ; => "gold" 
#+END_SRC

Now we can see what =bcom= is: a capability specific to this object
instance which allows it to change its behavior!
(For this reason, =bcom= is pronounced "become"!)

** Methods aren't essential, but they are useful

The most common way to select different sub-behaviors isn't by the
number of arguments though.
It's much more common to have "methods" that are selected by name.
We can use the =methods= macro to do just that:

#+BEGIN_SRC scheme
(use-modules (goblins actor-lib methods))

(define* (^mcell bcom #:optional [val #f])
  (methods
   ((get)
    val)
   ((set new-val)
    (bcom (^mcell bcom new-val)))))
#+END_SRC

The use of =^mcell= is similar, but now we pass in a first argument
as a symbol selecting the method, and the rest of the arguments are
passed to the object:

#+BEGIN_SRC scheme
  goblins[1]> (define jar
                (spawn ^mcell "cookies"))
  goblins[1]> ($ jar 'get)
  ; => "cookies"
  goblins[1]> ($ jar 'set "crumbs")
  goblins[1]> ($ jar 'get)
  ; => "crumbs"
#+END_SRC

Methods aren't particularly magical... the =methods= macro just
returns a procedure which is convenient to use for procedure dispatch:

#+BEGIN_SRC scheme
  > (define foo-or-bar
      (methods
       ((foo)
        'called-foo)
       ((bar arg)
        (list 'called-bar-with arg))))
  > (foo-or-bar 'foo)
  ; => called-foo
  > (foo-or-bar 'bar "meep")
  ; => (called-bar-with "meep")
#+END_SRC

So really, =methods= just makes a particularly useful kind of
behavior procedure for us, one which takes a first argument for
the method name, grabs the rest of the arguments, and then applies
them to the relevant method.

** Objects which contain objects

Objects can also contain and define other object references, including
in their outer constructor procedure.

Here is the definition of a "counting greeter" we call =^cgreeter=:

#+BEGIN_SRC scheme
(define (^cgreeter _bcom our-name)
  (define times-called
    (spawn ^mcell 0))
  (methods
   ((get-times-called)
    ($ times-called 'get))
   ((greet your-name)
    ;; increase the number of times called
    ($ times-called 'set
       (+ 1 ($ times-called 'get)))
    (format #f "[~a] Hello ~a, my name is ~a!"
            ($ times-called 'get)
            your-name our-name))))
#+END_SRC

As we can see near the top, =times-called= is instantiated as an
=^cell= like the one we defined earlier.
The current value of this cell is returned by =get-times-called=
and is updated every time the =greet= method is called:

#+BEGIN_SRC scheme
  goblins[1]> (define julius
                (spawn ^cgreeter "Julius"))
  goblins[1]> ($ julius 'get-times-called)
  ; => 0
  goblins[1]> ($ julius 'greet "Gaius")
  ; => "[1] Hello Gaius, my name is Julius!"
  goblins[1]> ($ julius 'greet "Brutus")
  ; => "[2] Hello Brutus, my name is Julius!"
  goblins[1]> ($ julius 'get-times-called)
  ; => 2
#+END_SRC

** Asynchronous message passing

We have shown that the behavior of objects may be invoked
synchronously with =$=.
However, this only works if two objects are both defined on the same
machine on the network and the same event loop within that machine.

Now, recall our friend =alice= who we defined on vat A.
The following works just fine if we're still executing within
=a-vat='s subrepl context:

#+BEGIN_SRC scheme
 goblins[1]> ($ alice "Alfred")
 => "Hello Alfred, my name is Alice!"
#+END_SRC

But let's exit the =a-vat= subrepl and make =b-vat= and enter that:

#+BEGIN_SRC scheme
  goblins[1]> ,q
  scheme> (define b-vat
            (spawn-vat))
  scheme> ,enter-vat b-vat
  goblins[1]>
#+END_SRC

But since Alice works on A, we cannot synchronously invoke her with
=$= on vat B:

#+BEGIN_SRC scheme
  goblins[1]> ($ alice "Bob")
  ;; === Caught error: ===
  ;;  message: #<<message> to: #<local-object> resolve-me: #f args: ()>
  ;;  exception: ... "Not in the same vat:" #<local-object ^greeter>) ...
#+END_SRC

This is where =<-= comes in.
In contrast to =$=, =<-= can be used against objects which live
anywhere, even on remote machines.
However, unlike invocation with =$=, we do not get back an
immediate result, we get a promise:

#+BEGIN_SRC scheme
  goblins[1]> (<- alice "Bob")
  ; => #<promise>
#+END_SRC

This promise must be listened to.
The procedure to listen to promises in Goblins is called
=on=:

#+BEGIN_SRC scheme
  goblins[1]> (on (<- alice "Bob")
                  (lambda (got-back)
                    (format #t "Heard back: ~a\n"
                            got-back)))
  ; Prints out, at some point in the future:
  ;   "Heard back: [3] Hello Bob, my name is Alice!"
#+END_SRC

Not all communication goes as planned, especially in a distributed
system.
Consider an object which breaks in the middle of execution, such as
an instance of =^broken= here:

#+BEGIN_SRC scheme
  (define (^broken _bcom)
    (lambda ()
      (error "Yikes, I broke!")))
#+END_SRC

=on= also supports the keyword arguments of =#:catch= and =#:finally=,
which both accept a procedure defining handling errors in the former case
and code which will run regardless of successful resolution or failure
in the latter case:

#+BEGIN_SRC scheme
  goblins[1]> (define broken-ben
                (spawn ^broken-ben))
  goblins[1]> (on (<- broken-ben)
                  (lambda (what-did-ben-say)
                    (format #t "Ben says: ~a\n" what-did-ben-say))
                  #:catch
                  (lambda (err)
                    (format #t "Got an error: ~a\n" err))
                  #:finally
                  (lambda ()
                    (display "Whew, it's over!\n")))
#+END_SRC

** Transactions make errors survivable

Mistakes happen, and when they do, we'd like damage to be minimal.
But with many moving parts, accomplishing this can be difficult.

However, Goblins makes our life easier.
To see how, let's intentionally insert a couple of print debugging
lines (with =pk=, which is pronounced and means "peek")
and then an error:

#+BEGIN_SRC scheme
  (define (^borked-cgreeter _bcom our-name)
    (define times-called
      (spawn ^mcell 0))
    (methods
      ((get-times-called)
       ($ times-called 'get))
      ((greet your-name)
       (pk 'before-incr ($ times-called 'get))
       ;; increase the number of times called
       ($ times-called 'set
          (+ 1 ($ times-called 'get)))
       (pk 'after-incr ($ times-called 'get))
       (error "Yikes")
       (format #f "[~a] Hello ~a, my name is ~a!"
               ($ times-called 'get)
               your-name our-name))))
#+END_SRC

Now let's spawn this friend and invoke it:

#+BEGIN_SRC scheme
  goblins[1]> (define horatio
                (spawn ^borked-cgreeter "Horatio"))
  goblins[1]> ($ horatio 'get-times-called)
  ; => 0
  goblins[1]> ($ horatio 'greet "Hamlet")
  ; pk debug: (before-incr 0)
  ; pk debug: (after-incr 1)
  ; ice-9/boot-9.scm:1685:16: In procedure raise-exception:
  ;   Yikes
  ; Entering a new prompt.  Type `,bt' for a backtrace or `,q' to continue.
#+END_SRC

Whoops!  Looks like something went wrong!
We can see from the =pk= debugging that the =times-called= cell should
be incremented to 1.
And yet...

#+BEGIN_SRC scheme
  goblins[1]> ($ horatio 'get-times-called)
  ; => 0
#+END_SRC

We will cover this in greater detail later, but the core idea here
is that synchronous operations run with =$= are all done together
as one transaction.
If an unhandled error occurs, any state changes resulting from
synchronous operations within that transaction will simply not
be committed.
This is useful, because it means most otherwise difficult cleanup
steps are handled automatically.

** Promise pipelining

#+BEGIN_QUOTE
  "Machines grow faster and memories grow larger.
  But the speed of light is constant and New York is not getting any
  closer to Tokyo."

   --- Mark S. Miller,
       [[http://www.erights.org/talks/thesis/][Robust Composition: Towards a Unified Approach to Access Control and Concurrency Control]]
#+END_QUOTE

Promise pipelining provides two different features at once:

 - A convenient developer interface for describing a series of
   asynchronous actions, allowing for invoking the objects which
   promises will point to before they are even resolved (sometimes
   before the objects even exist!)
 - A network abstraction that eliminates many round trips

Consider the following car factory, which makes cars carrying
the company name of the factory:

#+BEGIN_SRC scheme
  ;; Create a "car factory", which makes cars branded with
  ;; company-name.
  (define (^car-factory bcom company-name)
    ;; The constructor for cars we will create.
    (define (^car bcom model color)
      (methods                      ; methods for the ^car
       ((drive)                    ; drive the car
        (format #f "*Vroom vroom!*  You drive your ~a ~a ~a!"
                color company-name model))))
    ;; methods for the ^car-factory instance
    (methods                        ; methods for the ^car-factory
     ((make-car model color)       ; create a car
      (spawn ^car model color))))
#+END_SRC

Here is an instance of this car factory, which we will call
=fork-motors=, which we will spawn on =a-vat=:

#+BEGIN_SRC scheme
  scheme> ,enter a-vat
  goblins[1]> (define fork-motors
                (spawn ^car-factory "Fork"))
#+END_SRC

Since asynchronous message passing with =<-= works across machines,
it does not matter whether interacitons with =fork-motors= are local
or via objects communicating over the network.
We will treat =fork-motors= as living on machine A, and so the
following interactions will happen with invocations originating from
machine B.

Let's send a message to =fork-motors= invoking the ='make-car= method,
receiving back a promise for the car which will be made, which we
shall name =car-vow= (=-vow= being the conventional suffix given
for promises in Goblins):

#+BEGIN_SRC scheme
  goblins[1]> ,q
  scheme> ,enter-vat b-vat
  ;; Interaction on machine B, communicating with fork-motors on A
  goblins[1]> (define car-vow
                (<- fork-motors 'make-car "Explorist" "blue"))
#+END_SRC

So we have a /promise/ to a future car reference, but not the
reference itself.
We would like to drive the car as soon as it rolls off the lot of the
factory, which of course involves sending a message to the car.

Without promise pipelining, making use of the tools we have already
shown (and following the pattern most other distributed programming
systems use), we would end up with something like:

#+BEGIN_SRC scheme
  ;; Interaction on machine B, communicating with A
  goblins[1]> (on car-vow                    ; B->A: first resolve the car-vow
                  (lambda (our-car)          ; A->B: car-vow resolved as our-car
                    (on (<- our-car 'drive)  ; B->A: now we can message our-car
                        (lambda (val)        ; A->B: result of that message
                          (format #f "Heard: ~a\n" val)))))
#+END_SRC

With promise pipelining, we can simply message the promise of the car
directly.
The first benefit can be observed from code compactness, in that
we do not need to do an =on= of =car-vow= to later message =our-car=,
we can simply message =car-vow= directly:

#+BEGIN_SRC scheme
  ;; Interaction on machine B, communicating with A
  goblins[1]> (on (<- car-vow 'drive)       ; B->A: send message to future car
                  (lambda (val)             ; A->B: result of that message
                    (format #t "Heard: ~a\n" val)))
#+END_SRC

While clearly a considerable programming convenience, the other
advantage of promise pipelining is a reduction of round-trips, whether
between our event-loop /vats/ or across machines on the network.

This can be understood by looking at the comments to the right of the
two above code interactions.  The message flow in the first case looks
like:

: B => A => B => A => B

The message flow in the second case looks like:

: B => A => B

In other words, machine B can say to machine A: "Make me a car,
and as soon as that car is ready, I want to drive it!"

With this in mind, the promise behind Mark Miller's quote at the
beginning of this section is clear.[fn:thanks-to-e]
If two objects are on opposite ends of the planet, round trips
are unavoidably expensive.
Promise pipelining both allows us to make plans as programmers
and allows for Goblins to optimize carrying out those steps as
bulk operations over the network.

[fn:thanks-to-e] Like so many examples in this document, the designs
of promise pipelining and the explanation of its value come from the E
programming language, the many contributors to its design, and Mark
S. Miller's extraordinary work documenting that work and its history.
If you find this section interesting, both the the [[http://www.erights.org/elib/distrib/pipeline.html][Promise Pipelining]]
page from [[http://erights.org][erights.org]] and sections 2.5 and 16.2 of
[[http://www.erights.org/talks/thesis/markm-thesis.pdf][Mark Miller's dissertation]].

** OCapN, my CapN!

TODO

* API

Here lies the core procedures for building and manipulating Goblins
programs!

Unless where stated, most code from this section can be found by
importing:

#+BEGIN_SRC scheme
  (use-modules (goblins))
#+END_SRC

** Objects

Objects are the core of Goblins.
In general, you'll need to be within an ambient "Goblins Context" (TM)
in order to start programming against them, see [[*Vats][Vats]] for most event
loop type programming, or [[*Actormaps][Actormaps]] if you want to play with more low-level
control over transactional operations.
(However, most users will just use vats.)

*** Spawning objects

Objects can be spawned with the =spawn= operator:

#+BEGIN_SRC scheme
  (spawn CONSTRUCTOR ARGS ...)
  ;=> <local-refr>
#+END_SRC

where =CONSTRUCTOR= is a procedure which itself returns a procedure
representing an object's current behavior.
The =CONSTRUCTOR= is implicitly passed a first argument, traditionally
labeled =bcom=, which can be used to change an object's behavior.
The =ARGS= are passed as the remaining arguments to the constructor.

So for example, let's say we have the following constructor:

#+BEGIN_SRC scheme
  (define* (^cell bcom #:optional val)  ; constructor (outer procedure)
    (case-lambda                        ; behavior    (inner procedure)
      (()                               ; 0-argument invocation (getter)
       val)                             ;   (return current value)
      ((new-val)                        ; 1-argument invocation (setter)
       (bcom (^cell bcom new-val)))))   ;   ("become" ^cell with new value)
#+END_SRC

And so...

#+BEGIN_SRC scheme
  (define some-cell (spawn ^cell 42))
#+END_SRC

will bind =val= to =42=.

Let's look at the =bcom= argument in depth.
This is a capability which allows the actor to change its own behavior.
It must be called in a tail position, since =bcom= actually returns
a datastructure demonstrating that this object is choosing to change
its value (part of Goblins' quasi-functional design.)

=bcom= also can take a second argument, which will be returned from
the object's invocation as a return value, allowing for both an object
change its own behavior and return a value at the same time during an
invocation.

The following actor represents a consumable object that returns a
string explaining its current status:

#+BEGIN_SRC scheme
  (define (^drink bcom drink-name portions)
    (define (drinkable-beh portions)   ; "-beh" is a common suffix for "-behavior"
      (lambda ()
        (define portions-left
          (- portions 1))
        (if (zero? portions-left)
            (bcom empty-beh
                  (format #f "*GLUG!* You drink your ~a. It's empty!"
                          drink-name))
            (bcom (drinkable-beh portions-left)
                  (format #f "*GLUG!* You drink your ~a. Still some left!"
                          drink-name)))))
    (define (empty-beh)
      "Sadly, your glass appears to be empty!")
    (drinkable-beh portions))
#+END_SRC

Now, playing around at the REPL, we can see how this works:

#+BEGIN_SRC scheme
  > ,vr (define root-beer (spawn ^drink "root beer" 3))
  > ,vr ($ root-beer)
  => "*GLUG!* You drink your root beer. Still some left!"
  > ,vr ($ root-beer)
  => "*GLUG!* You drink your root beer. Still some left!"
  > ,vr ($ root-beer)
  => "*GLUG!* You drink your root beer. It's empty!"
  > ,vr ($ root-beer)
  => "Sadly, your glass appears to be empty!"
#+END_SRC

As you can see above, =bcom= is also a handy way to construct state
machines, as =^drink= moves from drinkable to empty as it is consumed.

*** Synchronous invocation

To synchronously invoke two objects within the same vat / actormap,
use =$=:

#+BEGIN_SRC scheme
  ($ near-object args ...)
  ;=> something
#+END_SRC

Provide a synchronous call against the current message handler of
=NEAR-REFR=, which must be a /near/ =live-refr?=
in the same vat as the currently running actor context.
The value returned is that which is returned by the
current behavior of =NEAR-REFR= upon invocation (or, if
=NEAR-REFR= chose to =bcom= something else, the second
argument passed to its =bcom=, or is =unspecified?= if not provided.)

*** Asynchronous invocation

#+BEGIN_SRC scheme
  (<- near-object arg ...)
  ;=> <local-promise>
#+END_SRC

Like =$=, but called asynchronously and returns a /promise/,
which may be handled with =on=.
Unlike =$=, =<-= is not limited to only /near/ objects;
interaction with /far/ actors are permitted as well.

#+BEGIN_SRC scheme
  (<-np [actor-refr live-refr?] [arg any/c] ...)
#+END_SRC

Like =<-= but does not return (or require the overhead of) a
promise.
=<-np= is effectively an optimization; where promises are not
needed, using =<-np= over =<-= is a good idea.

#+BEGIN_SRC scheme
(on vow
    [fulfilled-handler]
    [#:catch broken-handler]
    [#:finally finally-handler]
    [#:promise? #f])
#+END_SRC

Sets up promise handlers for =vow=, which is typically a
=live-refr?= to a /promise/ but may be anything.

=fulfilled-handler=, =broken-handler=, and =finally-handler=
all, if specified, may be either a procedure (the most common case)
which is run when =vow= becomes resolved, or a reference to an
actor that should be messaged when the promise is resolved with the
same arguments that would be passed to an equivalent procedure.
As their names suggest, =fulfilled-handler= will run if a promise is
fulfilled and takes one argument, the fulfilled value.
=broken-handler= will run if a promise is broken and takes one
argument, the error value.
=finally-handler= will run when a promise is resolved, no matter the
outcome and is called with no arguments.

If =#:promise?= is set to =#t=, then =on=
will itself return a promise.
The promise will be resolved as follows:

 - If =vow= is fulfilled and =fulfilled-handler= is not
   provided, the promise returned will share =vow='s resolution.
 - If =vow= is broken and =broken-handler= is not
   provided, the promise returned will share =vow='s broken result.
 - If =vow= is fulfilled and =fulfilled-handler= is provided,
   the resolution will be whatever is returned from =fulfilled-handler=,
   unless =fulfilled-handler= raises an error, in which case the promise
   will be broken with its error-value set to this exception.
 - If =vow= is broken and =broken-handler= is provided,
   the resolution will be whatever is returned from =broken-handler=,
   unless =broken-handler= raises an error, in which case the promise
   will be broken with its error-value set to this exception (which
   may even be the original exception).

** Vats

In order to start programming with Goblins, you will need to boot up a
vat somewhere.  In general, Goblins uses [[https://github.com/wingo/fibers/][Fibers]] to implement vats.
However, you can also roll your own vats should you have "unusual"
event loop needs ([[*Rolling your own vats][Rolling your own vats]].)

*** Starting and stopping vats

#+BEGIN_SRC scheme
  > (define my-vat (spawn-vat))
  > my-vat
  => #<vat izvD0DJT>
#+END_SRC

Running =spawn-vat= returns a vat object.  Code can be run within the
context of a vat using the =call-with-vat= procedure.  This is useful
for bootstrapping vats, or hacking at the REPL:

#+BEGIN_SRC scheme
  > (define my-vat (spawn-vat))
  > (call-with-vat my-vat
     (lambda ()
       (define alice (spawn ^greeter "Alice"))
       ($ alice "Bob")))
  => "Hello Alice, my name is Bob!"
#+END_SRC

For convenience, the =with-vat= macro can be used instead of
=call-with-vat=.  Here's the above example rewritten to use
=with-vat=:

#+BEGIN_SRC scheme
  > (define my-vat (spawn-vat))
  > (with-vat my-vat
     (define alice (spawn ^greeter "Alice"))
     ($ alice "Bob"))
  => "Hello Alice, my name is Bob!"
#+END_SRC

You can also use the =vat-halt!= procedure to stop the vat, and
=vat-running?= to check its status:

#+BEGIN_SRC scheme
  > (vat-halt! my-vat)
  > (vat-running? my-vat)
  => #f
#+END_SRC

*NOTE:* In the future, we would like vats to automatically halt when
no more references exist and thus the vat can do no more work.  The
Racket version of vats works this way, it would be good for the Guile
version to do the same.  In the meanwhile, you'll need to call
=vat-halt!= manually.

*** Rolling your own vats

Goblins comes with a built-in vat implementation that is
general-purpose and useful in most situations.  However, using Goblins
with a foreign event loop (such as a GUI widget toolkit or game
engine) calls for a specialized vat that knows how to hook into it.
The API described below is considered unstable and likely to change in
future releases of Goblins, so be prepared to update custom vat code
at a later date.

The =make-vat= constructor is used to make specialized vats.  Below is
some pseudocode that illustrates the basic pattern:

#+BEGIN_SRC scheme
  > (define (make-custom-vat)
      (define thread #f)
      (define (start churn)
        (define (loop)
          (churn (dequeue-msg))
          (loop))
        (set! thread (call-with-new-thread loop)))
      (define (halt)
        (cancel-thread thread))
      (define (send msg return?)
        (if return?
            (enqueue-msg-and-wait-for-result msg)
            (enqueue-msg msg)))
      (make-vat #:start start
                #:halt halt
                #:send send))
#+END_SRC

How to implement =enqueue-msg=, =enqueue-msg-and-wait-for-result=, and
=dequeue-msg= depends on the integration target and is left as an
exercise for the implementer.

Vat implementations must provide three hook procedures to =make-vat=:

- =start=: This procedure starts the vat message processor in the
  desired foreign event loop.  It accepts a =churn= procedure as its
  only argument.  The =churn= procedure accepts a message object and
  processes it using the vat's underlying actormap.
- =halt=: This procedure stops vat message processing.  It is a thunk,
  meaning that it accepts zero arguments.
- =send=: This procedure receives a message to process within the vat.
  It accepts two arguments: a message and a boolean flag indicating if
  the result of processing the message needs to be returned to the
  caller.  When the return flag is =#f=, vat implementations can
  simply queue the message for processing and move on.  When it is
  =#t=, however, the vat must arrange to wait and retrieve the
  eventual result of processing the message.

Custom vat implementations /must/ enqueue and dequeue messages in a
thread-safe manner because incoming messages from other vats may be,
and likely are, running in a different thread.

The =vat-start!= procedure initiates the processing of messages sent
to the vat.

#+BEGIN_SRC scheme
  > (define custom-vat (make-custom-vat))
  > (vat-start! custom-vat)
#+END_SRC

Once a custom vat has been started, it can be used as usual:

#+BEGIN_SRC scheme
  > (define alice
      (with-vat custom-vat
       (spawn ^greeter "Alice")))
#+END_SRC

** Actormaps

So far we have dealt with vats, but there is a lower level of
abstraction in Goblins which is called an =actormap=.

The key differences are:

 - *vat*: An event loop implementation that runs continuously
    in its own thread.
    Comes pre-built with tooling to handle message passing between
    vats.
    Actually wraps an actormap.
 - *actormap*: The transactional datastructure that vats use.
    But, useful on its own to either build your own event loop
    or as a synchronous one-turn-at-a-time mapping of actor references
    to their current implementations.

The best way to learn is by doing, so let's make an actormap now:

#+BEGIN_SRC scheme
  (define am (make-actormap))
#+END_SRC

Let's add an actor to it.
Since cells are simple, let's add one of those.

#+BEGIN_SRC scheme
  (define lunchbox
    (actormap-spawn! am ^cell))
#+END_SRC

What's in the lunchbox?
We could take a look with =actormap-peek=:

#+BEGIN_SRC scheme
  > (actormap-peek am lunchbox)
  ; => #f
#+END_SRC

An empty lunchbox... we'd like to eat something later, so how about we
pack ourselves a nice sandwich by using =actormap-poke=:

#+BEGIN_SRC scheme
  > (actormap-poke! am lunchbox 'peanut-butter-and-jelly)
  > (actormap-peek am lunchbox)
  ; => 'peanut-butter-and-jelly
#+END_SRC

What if we tried to look inside the lunchbox with =actormap-poke!=
instead of =actormap-peek=?

#+BEGIN_SRC scheme
  > (actormap-poke! am lunchbox 'bbq-tofu)
  > (actormap-poke! am lunchbox)
  ; => 'bbq-tofu
#+END_SRC

Well that worked just fine.
What happens if we do both operations with =actormap-peek=?

#+BEGIN_SRC scheme
  > (actormap-peek am lunchbox 'chickpea-salad)
  > (actormap-peek am lunchbox)
  ; => 'bbq-tofu
#+END_SRC

What the...???
Our lunchbox didn't change!

We said that actormaps were transactional.
We have gotten a hint of this with the above:
=actormap-poke!= returns a value and commits any changes.
=actormap-peek= returns a value and throws any changes away.

Actually, these two functions are just simple conveniences that wrap a
more powerful (but cumbersome to use) tool, =actormap-turn=:

#+BEGIN_SRC scheme
  > (actormap-turn am lunchbox)
  ; => 'bbq-tofu
  ; => #<transactormap>
  ; => '()
  (actormap-turn am lunchbox 'chickpea-salad)
  ; => *unspecified* (not printed)
  ; => #<transactormap>
  ; => '()
#+END_SRC

=actormap-turn= returns three values to its continuation: a
return value (if any... Guile's REPL doesn't print out the unspecified
value, which is what actually got returned in the second invocation),
a "transactormap", and a list representing messages
queued for delivery.

This =#<transactormap>= is interesting... we haven't mentioned this
before, but there are really two kinds of actormaps, "whactormaps"
(weak-hash actormaps) and "transactormaps" (which hold a transaction
which we can choose whether or not to commit).
Actually our =am= is a whactormap:

#+BEGIN_SRC scheme
  > am
  ; => #<whactormap>
#+END_SRC

It's a weak hashtable which stores the current mutable state of all
actors.

But we'd like to see about that transactormap... just running
=actormap-turn= on its own won't update the lunchbox either:

#+BEGIN_SRC scheme
  > (actormap-turn am lunchbox 'chickpea-salad)
  ; => *unspecified* (not printed)
  ; => #<transactormap>
  ; => '()
  > (actormap-turn am lunchbox)
  ; => 'bbq-tofu
  ; => #<transactormap>
  ; => '()
#+END_SRC

We need to capture the transactormap and commit it.

#+BEGIN_SRC scheme
  > (define-values (_val tr-am _nm)
      (actormap-turn am lunchbox 'chickpea-salad))
  > tr-am
  ; => #<transactormap>
  > (transactormap-merge! tr-am)
#+END_SRC

Now at least our =am= actormap should reflect that we've switched out
our ='bbq-tofu= sandwich for a ='chickpea-salad= one:

#+BEGIN_SRC scheme
  > (actormap-peek am lunchbox)
  ; => 'chickpea-salad
#+END_SRC

Horray!

** OCapN: The Object Capabilities Network

[[https://github.com/ocapn/ocapn][OCapN]] stands for "Object Capability Network" and is a suite of
protocols for communication between distributed, networked objects.
In other words, it's how Goblins actors can talk to actors running on
another computer.

OCapN uses the [[http://erights.org/elib/distrib/captp/index.html][Capability Transport Protocol (CapTP)]] as the core
protocol for enabling distributed programming in a mutually suspicious
network.  It originated in the [[http://www.erights.org/][E programming language]] but has since
appeared in [[https://capnproto.org/][Cap'N Proto]], [[http://waterken.sourceforge.net/][Waterken]], [[https://agoric.com/][Agoric]]'s [[https://github.com/Agoric/agoric-sdk/tree/master/packages/SwingSet][SwingSet]], and now Goblins.

*CAUTION*: CapTP support is still in its early days.  Please do not
rely on the protocol being stable at this time.

*** CapTP: The Capability Transport Protocol

OCapN's CapTP has an abstract "netlayer" interface, allowing
communication over many different protocols ranging from Tor Onion
Services to IBC to I2P to libp2p to perhaps carrier pigeons with
backpacks full of encrypted MicroSD cards.  Currently, Goblins only
supports the Tor Onion Services netlayer.

Benefits of CapTP:

- Invocation of remote objects resembles the same as with local
  objects.  You can use =<-= and =on= which means that any most
  programs that were even originally designed mostly for local-only
  computing naturally scale out to a networked environment.
- All this is done while mostly hiding the abstraction of the
  networked protocol from the user.
- Object capability security is upheld.  A remote machine cannot make
  use of any capability that has not been handed to it.
- Live object references between CapTP endpoints are incredibly cheap,
  merely represented as integers on each side.  This keeps message
  sizes small and efficient.
- CapTP provides (acyclic) distributed garbage collection.  Remote
  machines can indicate when they no longer need an object and the
  machine locally containing that reference can reclaim it if
  appropriate.
- Promise pipelining means that messages can be sent to the resolution
  of a promise before that resolution actually occurs.  Over the
  network this is represented as a pipeline of messages.  This can
  reduce round trips significantly, which is a big win.

  #+BEGIN_QUOTE
  Machines grow faster and memories grow larger.  But the speed of
  light is constant and New York is not getting any closer to
  Tokyo.

   --- Mark S. Miller
  #+END_QUOTE
- CapTP is written independently of network transport abstractions.
  It can be run over local unix domain sockets, an OpenSSL connection,
  Tor Onion Services, or something custom.  CapTP operates under the
  assumption of secure pairwise channels; the layer which provides the
  pairwise channels is called "MachineTP" and can be written in a
  variety of ways.  A simple MachineTP abstraction is provided, but
  presently still requires some manual wiring.  (In the future, even
  simpler abstractions will be provided which cover most user needs.)

All of these combine into an efficient and powerful protocol that,
most powerfully of all, the author of Goblins programs mostly need not
think too much about.  This circumvents the usual years and years of
careful message structure coordination and standardization for many
kinds of distributed programs, which can simply be written as normal
Goblins programs rather than bespoke protocols.

Limitations of CapTP:

- Goblins' CapTP provides /acyclic/ distributed garbage collection.
  Cycles between servers are not automatically recognized.  Full
  [[http://erights.org/history/original-e/dgc/][cycle-collecting distributed garbage collection]] has been written,
  but requires special cooperation from the garbage collector that we
  don't have access to in Guile (or in most languages).
- Goblins' CapTP does not do anything about memory usage or resource
  management on its own.  (Features for this will come as Spritely
  sub-projects in the future.)
- While CapTP in theory routes capabilities to specific remote
  objects, since the network is mutually suspicious we can't assume
  that the remote end isn't conspiring some way to hand those
  capabilities to other objects that we don't expect.  The right way
  to think about this from an object capability perspective is that a
  remote misbehaving machine is equivalent to a misbehaving object
  with the surface area of the entire machine.
- *TEMPORARY*: The API is heavily in flux.

*** Launching a Tor daemon for Goblins

In order for Goblins' Onion Service netlayer to work, it needs to talk
to a Tor daemon.  Goblins can set up and manage the Onion Services
itself once it connects to the Tor daemon.  So far it seems like
running a single Goblins tor process "as your user" and letting
various Goblins processes connect to it is the easiest option.

Here's an example config file template (replace =<user>= with your
actual username):

#+BEGIN_SRC text
  DataDirectory /home/<user>/.cache/goblins/tor/data/
  SocksPort unix:/home/<user>/.cache/goblins/tor/tor-socks-sock RelaxDirModeCheck
  ControlSocket unix:/home/<user>/.cache/goblins/tor/tor-control-sock RelaxDirModeCheck
  Log notice file /home/<user>/.cache/goblins/tor/tor-log.txt}|
#+END_SRC

Write this configuration to =~/.config/goblins/tor-config.txt=.

Create the necessary cache directory:

#+BEGIN_SRC sh
  mkdir -p ~/.cache/goblins/tor/data
#+END_SRC

Now launch the Tor daemon:

#+BEGIN_SRC sh
  tor -f ~/.config/goblins/tor-config.txt
#+END_SRC

*** Example: Two Goblins programs chatting over CapTP via Tor

Before diving into API details, let's take a look at a couple of small
example programs to demonstrate that this stuff works.

Here's our client script named =captp-alice.scm=:

#+BEGIN_SRC scheme
  (use-modules (fibers conditions)
               (fibers operations)
               (goblins)
               (goblins ocapn ids)
               (goblins ocapn captp)
               (goblins ocapn netlayer onion)
               (ice-9 match))

  ;; Create a CapTP router using Tor Onion Services.
  (define machine-vat (spawn-vat))
  (define-values (onion-netlayer private-key service-id)
    (with-vat machine-vat
      (new-onion-netlayer))
  (define mycapn
    (with-vat machine-vat
      (spawn-mycapn onion-netlayer)))

  ;; Convert the command-line argument into a sturdyref for Bob.
  (define bob-uri
    (match (command-line)
      ((_ uri) uri)))
  (define bob-sref (string->ocapn-id bob-uri))

  ;; Create a vat for Alice and enliven Bob.
  (define a-vat (spawn-vat))
  (define bob-vow
    (with-vat a-vat
      (<- mycapn 'enliven bob-sref)))

  ;; Send a message to Bob and print the response.
  (define done? (make-condition))
  (with-vat a-vat
    (on (<- bob-vow "Alice")
        (lambda (response)
          (format #t "Alice heard back: ~a" response)
          (signal-condition! done?))))

  ;; Wait until Alice has received a response before exiting.
  (perform-operation (wait-operation done?))
 #+END_SRC

Traditionally, Alice talks to Bob.  So, now we need Bob.  Save the
following server script as =captp-bob.scm=:

#+BEGIN_SRC scheme
  (use-modules (fibers conditions)
               (fibers operations)
               (goblins)
               (goblins ocapn ids)
               (goblins ocapn captp)
               (goblins ocapn netlayer onion))

  ;; Bob is going to be a greeter that says hello to other people.
  (define (^greeter _bcom our-name)
    (lambda (your-name)
      (format #f "Hello ~a, my name is ~a!" your-name our-name)))

  ;; Create Bob in their own vat.
  (define b-vat (spawn-vat))
  (define bob (with-vat b-vat (spawn ^greeter "Bob")))

  ;; Create a CapTP router using Tor Onion Services.
  (define machine-vat (spawn-vat))
  (define-values (onion-netlayer private-key service-id)
    (with-vat machine-vat
      (new-onion-netlayer))
  (define mycapn
    (with-vat machine-vat
      (spawn-mycapn onion-netlayer)))

  ;; Create a sturdyref for Bob and print it.
  (define bob-sref
    (with-vat machine-vat
      ($ mycapn 'register bob 'onion)))
  (format #t "Bob's sturdyref: ~a"
          (ocapn-id->string bob-sref))

  ;; Hold the process open indefinitely.
  (perform-operation (wait-operation (make-condition)))
#+END_SRC

Okay, let’s try it out!  Open up two terminals, and in the first one
run:

#+BEGIN_SRC sh
  guile captp-bob.scm
#+END_SRC

This will print out a captp "sturdyref" URI to the terminal.  Copy it
and paste it in the second terminal as the argument to =guile
captp-alice.scm=:

#+BEGIN_SRC sh
  guile captp-alice.scm <STURDYREF-GOES-HERE>
#+END_SRC

Tor Onion Services can take awhile to establish, but after a short
wait you should see:

#+BEGIN_SRC text
  Bob heard back: Hello Bob, my name is Alice!
#+END_SRC

If you see the same output then your connection succeeded!  Yay!  In
the next sections we will get into the details of how to use the CapTP
API.

*** Using the CapTP API

Goblins uses an actor to communicate over CapTP.  This actor can be
spawned using the =spawn-mycapn= procedure from the =(goblins ocapn
captp)= module:

#+BEGIN_SRC scheme
  > (define mycapn (spawn-mycapn netlayer))
#+END_SRC

Where =netlayer= refers to a CapTP netlayer object.  See the next
section for details on available netlayers.

Local actors need to be registered so that they can receive messages
over CapTP.  Registering an actor generates a CapTP identifier for
that actor:

#+BEGIN_SRC scheme
  > (define alice (spawn ^greeter "Alice"))
  > (define alice-captp-id ($ mycapn 'register alice 'onion))
#+END_SRC

To use this actor on another machine, that machine needs a "sturdyref"
to the actor.  A sturdyref is a special URI that uniquely identifies
the actor on the network.  The =ocapn-id->string= procedure from the
=(goblins ocapn ids)= module can generate such a URI:

#+BEGIN_SRC scheme
  > (ocapn-id->string community-sref)
  => "ocapn://jv4arqqwntmxs3rljkx3ao5bucci37rxxb575vypovntyve76mmyf4ad.onion/s/nGxw4_p6s91IF-R5r6MMYsZzoByODX46MV7AWTApX5s"
#+END_SRC

To generate a Guile URI object instead of a string, use
=ocapn-id->uri= instead.

On the other machine, the sturdyref can be "enlivened" to create a
promise that, when resolved, yields a remote object:

#+BEGIN_SRC scheme
  > (define vow ($ mycapn 'enliven "ocapn://..."))
  > vow
  => #<local-promise>
  > (on vow
        (lambda (obj)
          (display obj)
          (newline)))
  ; #<remote-object>
#+END_SRC

Sending messages to remote objects using =<-= looks the same as
sending messages to local objects.  The message will be transparently
sent over CapTP to the remote object!

**** Keeping a persistant sturdyref for an object
When an object is registered, it is given a "swiss num" (object specific part of the sturdyref). This can be extracted from the ocapn id:

#+BEGIN_SRC scheme
  > (define swiss-num (ocapn-sturdyref-swiss-num alice-captp-id))
  > swiss-num
  => #vu8(156 108 112 227 250 122 179 221 72 23 228 121 175 163 12 98 198 115 160 28 142 13 126 58 49 94 192 89 48 41 95 155)
#+END_SRC

Often it is desirable to have an object have a persistant sturdyref between sessions, to do this, you need do two things:

- Register the object at a specific swiss num
- Restore the netlayer (see the netlayer secion)

To install the object at a given swiss num, get the nonce registry. This is an object which holds all of the swiss nums to each registered object in mycapn. The following is how this can be done:

#+BEGIN_SRC scheme
  > (define registry ($ mycapn 'get-registry)) ;; nonce registry
  > (define alice-captp-id ($ registry 'register alice swiss-num))
#+END_SRC


*** Netlayers

**** Tor Onion Services

Assuming a Tor daemon is running, a Goblins Onion netlayer can be
created using the =new-onion-netlayer= procedure from the =(goblins
ocapn netlayer onion)= module:

#+BEGIN_SRC scheme
  > (define-values (onion-netlayer private-key service-id)
      (new-onion-netlayer))
#+END_SRC

That netlayer can then be used to spawn an OCapN router actor:

#+BEGIN_SRC scheme
  > (define mycapn (spawn-mycapn onion-netlayer))
#+END_SRC

Each time =new-onion-netlayer= is called it generates a new =private-key=  and =service-id=. If you wish for these to persist, these needs to be stored (securely, as anyone with them has the capability to host at them) and call =restore-onion-netlayer= providing them. An example of this is:

#+BEGIN_SRC scheme
  > (define-values (onion-netlayer _private-key _service-id)
      (restore-onion-netlayer private-key service-id))
#+END_SRC

** COMMENT Persistence

* actor-lib: A standard library of sorts

The Goblins actor library, in the =(goblins actor-lib ...)= module
namespace, provides implementations for a variety of common actor
model patterns.

** Cells

The =(goblins actor-lib cell)= module provides a very handy actor
called a "cell."  Cells are used to store arbitrary data.

New cells are created with the constructor =^cell=:

#+BEGIN_SRC scheme
  > (define chest (spawn ^cell 'gold))
#+END_SRC

The current value of a cell can be retrieved by sending an empty
message to the cell:

#+BEGIN_SRC scheme
  > ($ chest)
  => gold
#+END_SRC

The value of a cell can be changed by sending a message containing the
new value:

#+BEGIN_SRC scheme
  > ($ chest 'sword)
  > ($ chest)
  => sword
#+END_SRC

** Methods

The =(goblins actor-lib methods)= module provides a simple,
single-dispatch method system for actor behaviors.

Here's a constructor for an actor that can say hello or goodbye:

#+BEGIN_SRC scheme
  > (define (^hello-goodbye _bcom)
      (methods
       ((say-hello name)
        (format #f "Hello, ~a!" name))
       ((say-goodbye name)
        (format #f "Goodbye, ~a!" name))))
#+END_SRC

The =methods= macro is used to describe a collection of messages that
an actor accepts.  The first argument of the message is used to
dispatch the proper behavior for handling that message.

Let's try it out:

#+BEGIN_SRC scheme
  > (define hello-goodbye (spawn ^hello-goodbye))
  > ($ hello-goodbye 'say-hello "Alice")
  => "Hello, Alice!"
  > ($ hello-goodbye 'say-goodbye "Alice")
  => "Goodbye, Alice!"
#+END_SRC

** Joiners

The =(goblins actor-lib joiners)= module provides a means of combining
the results of many promises.

The =all-of= procedure returns a new promise that waits for all of the
given promises to resolve before resolving itself.  This is very
useful when we need to wait for several asynchronous operations to
complete successfully before moving on.

To demonstrate this, we'll use a very useless actor that waits for
awhile before returning the same thing it received:

#+BEGIN_SRC scheme
  > (define (^procrastinator _bcom delay)
      (lambda (x)
        (sleep delay)
        x))
#+END_SRC

We can use =all-of= to wait for all procrastinators to finish
procrastinating before writing some output:

#+BEGIN_SRC scheme
  > (define a-vat (spawn-vat))
  > (define b-vat (spawn-vat))
  > (define c-vat (spawn-vat))
  > (define p1 (with-vat b-vat (spawn ^procrastinator 1)))
  > (define p2 (with-vat c-vat (spawn ^procrastinator 2)))
  > (with-vat a-vat
      (on (all-of (<- p1 'foo) (<- p2 'bar))
          (lambda (items)
            (display items)
            (newline))))
  ; (foo bar)
#+END_SRC

*Note*: Currently, =all-of= calls the resolution procedure with a list
as its only argument.  In a future release of Goblins we intend to
call the resolution procedure with multiple arguments, one for each
promise passed to =all-of=.

** Sealers

The =(goblins actor-lib sealers)= module provides a mechanism for
ensuring the authenticity of data.  Using sealers, data can be hidden
within a wrapper and marked with a unique brand to produce a sealed
object.  A sealed object can be checked to verify that it has been
marked with the expected brand.  An authentic sealed object can then
be unsealed to reveal the data within.  Sealers and unsealers are
analagous to public key cryptography where sealing resembles
encryption, unsealing resembles decryption, and the brand check
predicate resembles signature verification.  However, sealers work
without any cryptography at all!

Sealers are comprised of three distinct capabilities: the sealer, the
unsealer, and the brand check.  Using separate capabilities allows for
fine-grained privilege management.  For example, an actor that only
has the brand check capability cannot seal or unseal data.

Imagine a scenario where we are protecting lunchtime meals using
sealers and unsealers. Our rival, who wishes to sabotage us, does the
same:

#+BEGIN_SRC scheme
  > (define-values (our-lunch:seal our-lunch:unseal our-can?)
      (spawn-sealer-triplet))
  > (define-values (rival-lunch:seal rival-lunch:unseal rival-can?)
      (spawn-sealer-triplet))
#+END_SRC

Calling the =spawn-sealer-triplet= procedure returns three new actors
representing the seal, unseal, and check capabilities.  We give our
customer the unsealer, the delivery driver the brand predicate, and we
keep the sealer to ourselves so no one else can brand their lunch as
ours.

A value can be sealed by sending it as a message to the sealer.  Let's
put some fried rice in a can by sending a message to the sealer:

#+BEGIN_SRC scheme
  > ($ our-lunch:seal 'fried-rice)
  => #<local-object sealed-value>
#+END_SRC

The contents of sealed cans are private and cannot be seen by
inspecting the sealed object.

Our customer wants some chickpea salad, so we seal some for them:

#+BEGIN_SRC scheme
  > (define chickpea-lunch ($ our-lunch:seal 'chickpea-salad))
#+END_SRC

Our truck driver is able to check that the food they are to deliver
really is from us (we have a reputation to uphold!) by sending a
message to the brand predicate:

#+BEGIN_SRC scheme
  > ($ our-can? chickpea-lunch)
  => #t
  > ($ our-can? ($ rival-lunch:seal 'melted-ice-cream))
  => #f
#+END_SRC

The customer is able to open up their can by sending it to the
unsealer:

#+BEGIN_SRC scheme
  > ($ our-lunch:unseal chickpea-lunch)
  => chickpea-salad
#+END_SRC

* COMMENT Design and philosophy

** On the design of Goblins' distributed objects


** Why Scheme?  Why Guile?

** History

** The future: hopes, dreams, and hard work

** License choice

** Spritely and user freedom

* Thanks

This manual was primarily written by Christine Lemmer-Webber.

# Additional text by: ...

Many of the ideas are borrowed from [[http://www.erights.org/talks/thesis/markm-thesis.pdf][Mark Miller's dissertation]],
which is an excellent, if nerdy, read.

Jessica Tallon, Jonathan A. Rees, Randy Farmer, and David Thompson
provided review and feedback.

* License

/(C) 2019-2022 Christine Lemmer-Webber, the Spritely Institute, and other contributors.  See =AUTHORS= for details./

/Both Spritely Goblins and this manual are released under the terms of the following license:/

#+INCLUDE: "../COPYING"
