\input texinfo    @c -*- texinfo -*-
@c %**start of header
@setfilename goblins.info
@settitle Spritely Goblins
@documentencoding UTF-8
@documentlanguage en
@syncodeindex pg cp
@c %**end of header

@dircategory The Algorithmic Language Scheme
@direntry
* Goblins: (goblins).   Distributed programming environment and Spritely's core (Guile edition).
@end direntry

@finalout
@titlepage
@title Spritely Goblins
@author Christine Lemmer-Webber (@email{christine@@spritely.institute})
@author The Spritely Institute
@end titlepage

@contents

@ifnottex
@node Top
@top Spritely Goblins

This is the manual for @uref{https://spritely.institute/goblins/,
Spritely Goblins}, a distributed object programming environment.
Spritely Goblins is mantained by
@uref{https://spritely.institute/, Spritely Networked Communities Institute} and is built to
be the core layer for building broader decentralized networking technologies.

Both this manual and Guile Goblins itself are released under Apache
v2.  See @ref{License} for more information.
@end ifnottex

@menu
* What is Goblins?::
* Getting started::
* A high level view of Goblins::
* Tutorial::
* API::
* actor-lib A standard library of sorts::
* Thanks::
* License::
@end menu

@node What is Goblins?
@chapter What is Goblins?

@uref{https://spritely.institute/goblins/, Goblins} is a distributed object programming environment.
Features:

@itemize
@item
@strong{Quasi-functional object system:} users hold on to references
of objects/actors, but objects/actors are just procedures.  Rather
than directly mutating, objects/actors can specify that they should
``become'' a new version of themselves when they handle the next
invocation.

@item
@strong{Fully distributed, networked, secure p2p communication:} via
OCapN, the Object Capability Network (which features CapTP, the
Capability Transport Protocol), you can communicate with other objects
over a network connection.  Distributed object interactions are safe
because of ocap security guarantees.

@item
@strong{Transactional updates:} changes happen within a transaction.
If an unhandled exception occurs, Goblins can ``roll back'' history
as if the message never happened, avoiding confused state changes
throughout the system.

@item
@strong{Time travel:} you can snapshot old revisions of the system and
interact with them.

@item
@strong{Asynchronous programming with sophisticated promise chaining:}
asynchronous message passing with promises is supported.  Promises
work such that there's no need to wait for promises to resolve before
interacting@dots{} you can communicate with the future that doesn't
even yet exist!  Sent a message to that remote car factory asking for
a new car?  Why wait for the car to be delivered@dots{} you can send
it a drive message at the same time, and both messages can be
delivered across the network in a single hop.

@item
@strong{Communicating event loops:} objects across multiple event
loops (aka ``vats'') can communicate, whether in the same OS process
or across the network.

@item
@strong{Synchronous and asynchronous behavior, integrated but
distinguished:} both synchronous and asynchronous programming is
supported, but only objects in the same ``vat'' (event loop) can
perform synchronous immediate calls.  All objects can perform
asynchronous calls against each other.

@item
@strong{A library, not a language:} Goblins is itself a library that
can be utilized across a wide variety of Guile programs.

@item
@strong{Object capability security:} Goblins itself is built for
object capability (OCap) security, which is to say that you can only
operate on the references you have access to.  Goblins embraces and
builds upon this foundation.  (However, full OCap security will
require utilizing the sandboxing features of Guile; demonstrations of
this coming soon.)
@end itemize


Goblins' design is inspired by the @uref{http://www.erights.org/, E
programming language} and by the observation that
@uref{http://mumble.net/~jar/pubs/secureos/secureos.html, lambda is
already the ultimate security mechanism} (ie, normal argument-passing
in programs, if taken seriously/purely, is already all the security
system needed).

Spritely Networked Communities Institute was created to advance decentralized
networking infrastructure, particularly as it pertains to social networks.
Goblins is the heart of the system, on which other layers are built.
At the time of writing, two key versions of Goblins are supported, the
@uref{https://docs.racket-lang.org/goblins/index.html, Racket version
of Goblins}, and the @uref{https://www.gnu.org/software/guile/, Guile}
version.  This manual is for the Guile edition of Spritely Goblins.

@node Getting started
@chapter Getting started

@menu
* Installing Goblins::
* Setup for hacking on Goblins::
* TEMPORARY Live hacking ``fix''::
@end menu

@node Installing Goblins
@section Installing Goblins

You'll need to install @code{guile-goblins}.  Either use
@uref{https://guix.gnu.org/, Guix} or use your standard GNU/Linux
distro's package for @code{guile-goblins} (if it exists), or even
better yet run Guix as your standard distro.

Otherwise see the @file{HACKING} and @file{README} files with git
checkouts / release tarballs to install.

@node Setup for hacking on Goblins
@section Setup for hacking on Goblins

You're going to want/need:

@itemize
@item
@uref{https://www.gnu.org/software/emacs/, GNU Emacs}
@item
@uref{https://www.nongnu.org/geiser/, Geiser}, for hacking on Guile
@end itemize

Then, at minimum, you'll want to put in your .emacs:

@lisp
(show-paren-mode 1)  ; Match parentheses
@end lisp

However you probably also want some combination of:

@itemize
@item
@uref{https://github.com/Fuco1/smartparens, smartparens} (or @uref{https://www.emacswiki.org/emacs/ParEdit, paredit}, which is much more strict@dots{} use
smartparens if uncertain)
@item
@uref{https://github.com/Fanael/rainbow-delimiters, rainbow-delimeters}
@item
@uref{https://www.emacswiki.org/emacs/HighlightParentheses, highlight-parentheses}
@end itemize

Now you'll have a nice hacking setup!  Be sure to read the Geiser
manual.

@node TEMPORARY Live hacking ``fix''
@section TEMPORARY: Live hacking ``fix''

The traditional way to hack Guile is to use Geiser, both evaluating
from some @code{foo.scm} file/buffer with more ``permanent'' code via,
for example, the @code{C-x C-e} / @code{C-x C-b} / @code{C-x C-k}
commands to evaluate an expression, evaluate a whole buffer, or
compile a buffer's content; and switching back and forth between that
and the (usually called @code{*Geiser Guile REPL*})
experimental-hacking-and-debugging REPL@.

This works with Goblins, but Geiser does some things to temporarily
redirect output/error ports when doing the file/buffer oriented
evaluation. Unfortunately, this results in Goblins vats potentially
breaking due to spawning a separate thread which inherits these
temporarily redirected ports, which are then closed when the
evaluation succeeds.  There is a long-term plan to deal with this, but
in the meanwhile, whenever you start a Guile / Geiser hacking session,
first execute:

@lisp
> (use-modules (goblins))
@end lisp

@dots{} from the @code{*Geiser Guile REPL*}.  Otherwise vats may
mysteriously ``hang''.  This annoyance will be fixed soon!

@node A high level view of Goblins
@chapter A high level view of Goblins

As a starting point, here's a sketch of a network of Goblins objects
wired to communicate with each other:

@example
.----------------------------------.         .----------------------.
|            Machine 1             |         |       Machine 2      |
|            =========             |         |       =========      |
|                                  |         |                      |
| .--------------.  .---------.   .-.       .-.                     |
| |    Vat A     |  |  Vat B  |   |  \______|  \_   .------------.  |
| |  .---.       |  |   .-.   | .-|  /      |  / |  |    Vat C   |  |
| | (Alice)----------->(Bob)----' '-'       '-'  |  |  .---.     |  |
| |  '---'       |  |   '-'   |    |         |   '--->(Carol)    |  |
| |      \       |  '----^----'    |         |      |  '---'     |  |
| |       V      |       |         |         |      |            |  |
| |      .----.  |       |        .-.       .-.     |  .------.  |  |
| |     (Alfred) |       '-------/  |______/  |____---( Carlos ) |  |
| |      '----'  |               \  |      \  |     |  '------'  |  |
| |              |                '-'       '-'     '------------'  |
| '--------------'                 |         |                      |
|                                  |         |                      |
'----------------------------------'         '----------------------'
@end example

In the above diagram, you see:

@itemize
@item
Two machines (@code{Machine 1} and @code{Machine 2}, running
separately from each other, but connected to each other over the
network via OCapN and CapTP@.

@item
@code{Vat A} and @code{Vat B} are event loops which live on
@code{Machine 1}, and @code{Vat C} is an event loop which lives on
@code{Machine 2}.

@item
The individual objects (represented by circles) live in @emph{vats},
aka event loops which contain objects.  @code{Alice} and @code{Alfred}
live in @code{Vat A}, @code{Bob} lives in @code{Vat B}, and
@code{Carol} and @code{Carlos} live in @code{Vat C}.  (While these
objects have human-like names, they're just Goblins objects.)

@item
The arrows between the objects represent references these objects have
to each other.  @code{Alice} has references to both @code{Alfred} and
@code{Bob}.  @code{Bob} has a reference to @code{Carol}.
@code{Carlos} has a reference to @code{Bob}.

@item
Two objects which are in the same vat are considered @emph{near} each
other, and thus can invoke each other synchronously.  Any objects not
in the same vat are considered @emph{far} from each other.  Any
objects can invoke each other by asynchronous message passing,
assuming they have a reference to each other.

@item
Not pictured: each vat has an @emph{actormap}, an underlying
transactional heap used for object communication.  This is what
permits transactionality and time travel.  (Actormaps can also be used
independently of vats for certain categories of applications.)
@end itemize

Another way to think about this is via the following abstraction
nesting dolls:

@lisp
(machine (vat (actormap @{refr: object-behavior@})))
@end lisp

@itemize
@item
@strong{Machines}, which are computers on the network, or more
realistically, operating system processes, which contain@dots{}
@item
@strong{Vats}, which are communicating event loops, which contain@dots{}
@item
@strong{Actormaps}, transactional heaps, which contain@dots{}
@item
a mapping of @strong{References} to @strong{Object Behavior}.
@end itemize

@menu
* The ``vat model'' of computation::
@end menu

@node The ``vat model'' of computation
@section The ``vat model'' of computation

As said, Goblins follows what is called the @emph{vat model} of
computation.  A @emph{vat} is an event loop that manages a set of
objects which are @emph{near} to each other (and similarly, objects
outside of a vat are @emph{far} from each other).

Objects which are @emph{near} can perform synchronous call-return
invocations in a manner familiar to most sequential programming
languages used by most programmers today.  Aside from being a somewhat
more convenient way to program, sequential invocation is desirable
because of cheap @emph{transactionality}, which will be expanded upon
more later.  Goblins uses the @code{$} operator to perform synchronous
operations.

Both @emph{near} and @emph{far} objects are able to invoke each other
asynchronously using asynchronous message passing (in the same style
as the @emph{classic actor model}).  It does not generally matter
whether or not a @emph{far} object is running within the same OS
process or machine or one somewhere else on the network for most
programming tasks; asynchronous message passing works the same either
way.  Goblins uses the @code{<-} operator to perform asynchronous
operations.

For both programmer convenience and for networked efficiency, Goblins
supports @emph{promise pipelining}: messages can be sent to promises
which have not yet resolved, and will be forwarded to the target once
the promise resolves.  The sender of the message is handed back a
promise to which it can supply callbacks, listening for the promise to
be fulfilled with a value or broken (usually in case of an unexpected
error).

As usual in the vat model of computation, individual message sends to
a vat (event loop) are queued and then handled one @emph{turn} at a
time, akin to the way board game players take turns around a table
(which is indeed the basis for the term @emph{turn}).

The message, addressing a specific object, is passed to the recipient
object's current behavior.  This object may then invoke other
@emph{near} objects (residing within the same vat), which may
themselves invoke other near objects in a synchronous and sequential
call-return style familiar to most users of most contemporary
programming languages.  Any of these invoked objects may also change
their state/behavior (behavior changes appear purely functional in
Goblins; invocations of other actors do not), spawn new objects,
invoke ordinary expressions from the host language, or send
asynchronous messages to other objects (which are only sent if the
@emph{turn} completes successfully).

While the @emph{vat model} of computation is not new (it originates in
the @uref{http://erights.org/, E} programming language and can trace
some of its ideas back to E's predecessor
@uref{http://erights.org/history/joule/, Joule}; and has since
reappeared in systems such as @uref{https://agoric.com/, Agoric's}
@uref{https://github.com/Agoric/agoric-sdk/tree/master/packages/SwingSet,
SwingSet} kernel), Goblins brings some novel contributions to the
table in terms of transactionality and time-travel debugging,
enhancing an already powerful distributed programming paradigm.

@node Tutorial
@chapter Tutorial

@menu
* A simple greeter::
* State as updating behavior::
* Methods aren't essential, but they are useful: Methods aren't essential but they are useful.
* Objects which contain objects::
* Asynchronous message passing::
* Transactions make errors survivable::
* Promise pipelining::
@end menu

@node A simple greeter
@section A simple greeter

First, import Goblins:

@lisp
> (use-modules (goblins))
@end lisp

(@strong{NOTE}: See @ref{TEMPORARY Live hacking ``fix''} if you haven't.)

Goblins actors live in special event loops called @emph{vats}.  Make a
vat to play around with and ``enter'' it at the REPL:

@lisp
scheme> (define a-vat (spawn-vat))
scheme> ,enter-vat a-vat
goblins[1]>
@end lisp

Now implement a friend who will greet you:

@lisp
(define (^greeter bcom our-name)   ; constructor (outer procedure)
  (lambda (your-name)              ; behavior    (inner procedure)
    (format #f "Hello ~a, my name is ~a!"
            your-name our-name)))
@end lisp

Give it a try by instantiating an instance of @code{^greeter}
using @code{spawn} and assign her to the variable @code{alice}:

@lisp
> (define alice
    (spawn ^greeter "Alice"))
@end lisp

The first argument to @code{spawn} is the constructor used to
make the Goblins object, in this case @code{^greeter}.  The remaining
arguments will be passed to the constructor, along with an implicit
argument which can be used to change object behavior called
@code{bcom} (pronounced ``become'').  Thus @code{"Alice"} maps to
@code{our-name}.

You can invoke @code{alice} by using @code{$} for a synchronous
call-return operation:

@lisp
goblins[1]> (define alice
              (spawn ^greeter "Alice"))
goblins[1]> ($ alice "Alfred")
; => "Hello Alfred, my name is Alice!"
@end lisp

The first argument to @code{$} is the object to be invoked, and the
remaining arguments are passed to the ``behavior'' of the object.
Thus @code{your-name} in @code{^greeter}'s behavior procedure is bound
to @code{"Alfred"}.  The behavior procedure thus proceeds with
formatting and returning the greeting string.

You can exit the subrepl for @code{a-vat} with @code{,q} (the same way
as if Guile put us in a subrepl to debug an error):

@lisp
goblins[1]> ,q
scheme>
@end lisp

As you have probably inferred, Goblins-specific operations such as
@code{$} and @code{spawn} happen within a context (typically a
@emph{vat}, though there is an even lower-level structure called an
@emph{actormap} which we will see more about later).  However, the
subrepl entered by @code{,enter-vat} is a convenience for hacking.  You
can run also run code within @code{a-vat} like so:

@lisp
scheme> (call-with-vat a-vat (lambda () ($ alice "Arthur")))
; => "Hello Arthur, my name is Alice!"
@end lisp

Very few operations in Goblins spend time operating on vats directly;
typically commands like the above only happen when bootstrapping the
initial set of actors within a vat or when hacking, after which the
actors within the vats do their own thing.

@node State as updating behavior
@section State as updating behavior

Re-enter @code{a-vat}'s subrepl if you haven't:

@lisp
scheme> ,enter-vat a-vat
goblins[1]>
@end lisp

Here is a simple cell which stores a value.  This cell will have two
methods: @code{'get} retrieves the current value, and @code{'set}
replaces the current value with a new value.

@lisp
(define* (^cell bcom #:optional [val #f])
  (case-lambda
    (()         ; get
     val)
    ((new-val)  ; set
     (bcom (^cell bcom new-val)))))
@end lisp

@code{case-lambda} allows for dispatching depending on the number of
arguments, so this code says that if no arguments are provided,
the cell shares the current value; and if one argument is provided,
the cell updates itself to become a cell storing the new value.

Cells hold values. So do treasure chests. Make a treasure chest
flavored cell.  Taking things out and putting them back in is
easy:

@lisp
goblins[1]> (define chest
              (spawn ^cell "sword"))
goblins[1]> ($ chest)
; => "sword"
goblins[1]> ($ chest "gold")
goblins[1]> ($ chest)
; => "gold"
@end lisp

Now you can see what @code{bcom} is: a capability specific to this
object instance which allows it to change its behavior!  (For this
reason, @code{bcom} is pronounced ``become''!)

@node Methods aren't essential but they are useful
@section Methods aren't essential, but they are useful

The most common way to select different sub-behaviors isn't by the
number of arguments.  It's much more common to have ``methods'' that
are selected by name.  You can use the @code{methods} macro to do just
that:

@lisp
(use-modules (goblins)
             (goblins actor-lib methods))

(define* (^mcell bcom #:optional [val #f])
  (methods
   ((get)
    val)
   ((set new-val)
    (bcom (^mcell bcom new-val)))))
@end lisp

The use of @code{^mcell} is similar, but now you pass in a first
argument as a symbol selecting the method, and the rest of the
arguments are passed to the object:

@lisp
goblins[1]> (define jar
              (spawn ^mcell "cookies"))
goblins[1]> ($ jar 'get)
; => "cookies"
goblins[1]> ($ jar 'set "crumbs")
goblins[1]> ($ jar 'get)
; => "crumbs"
@end lisp

Methods aren't particularly magical@dots{} the @code{methods} macro
just returns a procedure which is convenient to use for procedure
dispatch:

@lisp
> (define foo-or-bar
    (methods
     ((foo)
      'called-foo)
     ((bar arg)
      (list 'called-bar-with arg))))
> (foo-or-bar 'foo)
; => called-foo
> (foo-or-bar 'bar "meep")
; => (called-bar-with "meep")
@end lisp

So really, @code{methods} just makes a particularly useful kind of
behavior procedure for you, one which takes a first argument for the
method name, grabs the rest of the arguments, and then applies them to
the relevant method.

@node Objects which contain objects
@section Objects which contain objects

Objects can also contain and define other object references, including
in their outer constructor procedure.

Here is the definition of a ``counting greeter'' called
@code{^cgreeter}:

@lisp
(define (^cgreeter _bcom our-name)
  (define times-called
    (spawn ^mcell 0))
  (methods
   ((get-times-called)
    ($ times-called 'get))
   ((greet your-name)
    ;; increase the number of times called
    ($ times-called 'set
       (+ 1 ($ times-called 'get)))
    (format #f "[~a] Hello ~a, my name is ~a!"
            ($ times-called 'get)
            your-name our-name))))
@end lisp

As you can see near the top, @code{times-called} is instantiated as a
@code{^cell} like the one we defined earlier.  The current value of
this cell is returned by @code{get-times-called} and is updated every
time the @code{greet} method is called:

@lisp
goblins[1]> (define julius
              (spawn ^cgreeter "Julius"))
goblins[1]> ($ julius 'get-times-called)
; => 0
goblins[1]> ($ julius 'greet "Gaius")
; => "[1] Hello Gaius, my name is Julius!"
goblins[1]> ($ julius 'greet "Brutus")
; => "[2] Hello Brutus, my name is Julius!"
goblins[1]> ($ julius 'get-times-called)
; => 2
@end lisp

@node Asynchronous message passing
@section Asynchronous message passing

You have seen that the behavior of objects may be invoked
synchronously with @code{$}.  However, this only works if two objects
are both defined on the same machine on the network and the same event
loop within that machine.

Now, recall your friend @code{alice} who you defined on vat A@.  The
following works just fine if you're still executing within
@code{a-vat}'s subrepl context:

@lisp
goblins[1]> ($ alice "Alfred")
=> "Hello Alfred, my name is Alice!"
@end lisp

Exit the @code{a-vat} subrepl and make @code{b-vat} and
enter that:

@lisp
goblins[1]> ,q
scheme> (define b-vat
          (spawn-vat))
scheme> ,enter-vat b-vat
goblins[1]>
@end lisp

Since Alice works on A, you cannot synchronously invoke her with
@code{$} on vat B:

@lisp
goblins[1]> ($ alice "Bob")
;; === Caught error: ===
;;  message: #<<message> to: #<local-object> resolve-me: #f args: ()>
;;  exception: ... "Not in the same vat:" #<local-object ^greeter>) ...
@end lisp

This is where @code{<-} comes in.  In contrast to @code{$}, @code{<-}
can be used against objects which live anywhere, even on remote
machines.  However, unlike invocation with @code{$}, you do not get
back an immediate result; you get a promise:

@lisp
goblins[1]> (<- alice "Bob")
; => #<promise>
@end lisp

This promise must be listened to.  The procedure to listen to promises
in Goblins is called @code{on}:

@lisp
goblins[1]> (on (<- alice "Bob")
                (lambda (got-back)
                  (format #t "Heard back: ~a\n"
                          got-back)))
; Prints out, at some point in the future:
;   "Heard back: [3] Hello Bob, my name is Alice!"
@end lisp

Not all communication goes as planned, especially in a distributed
system.  Consider an object which breaks in the middle of execution,
such as an instance of @code{^broken} here:

@lisp
(define (^broken _bcom)
  (lambda ()
    (error "Yikes, I broke!")))
@end lisp

@code{on} also supports the keyword arguments of @code{#:catch} and
@code{#:finally}, which both accept a procedure defining handling
errors in the former case, and code which will run regardless of
successful resolution or failure in the latter case:

@lisp
goblins[1]> (define broken-ben
              (spawn ^broken))
goblins[1]> (on (<- broken-ben)
                (lambda (what-did-ben-say)
                  (format #t "Ben says: ~a\n" what-did-ben-say))
                #:catch
                (lambda (err)
                  (format #t "Got an error: ~a\n" err))
                #:finally
                (lambda ()
                  (display "Whew, it's over!\n")))
@end lisp

@node Transactions make errors survivable
@section Transactions make errors survivable

Mistakes happen, and when they do, the damage should be minimal.
But with many moving parts, accomplishing this can be difficult.

However, Goblins makes life easier.  To see how, intentionally insert
a couple of print debugging lines (with @code{pk}, which is pronounced
and means ``peek'') and then an error:

@lisp
(define (^borked-cgreeter _bcom our-name)
  (define times-called
    (spawn ^mcell 0))
  (methods
    ((get-times-called)
     ($ times-called 'get))
    ((greet your-name)
     (pk 'before-incr ($ times-called 'get))
     ;; increase the number of times called
     ($ times-called 'set
        (+ 1 ($ times-called 'get)))
     (pk 'after-incr ($ times-called 'get))
     (error "Yikes")
     (format #f "[~a] Hello ~a, my name is ~a!"
             ($ times-called 'get)
             your-name our-name))))
@end lisp

Now spawn this friend and invoke it:

@lisp
goblins[1]> (define horatio
              (spawn ^borked-cgreeter "Horatio"))
goblins[1]> ($ horatio 'get-times-called)
; => 0
goblins[1]> ($ horatio 'greet "Hamlet")
; pk debug: (before-incr 0)
; pk debug: (after-incr 1)
; ice-9/boot-9.scm:1685:16: In procedure raise-exception:
;   Yikes
; Entering a new prompt.  Type `,bt' for a backtrace or `,q' to continue.
@end lisp

Whoops!  Looks like something went wrong!  You can see from the
@code{pk} debugging that the @code{times-called} cell should be
incremented to 1.  And yet@dots{}

@lisp
goblins[1]> ($ horatio 'get-times-called)
; => 0
@end lisp

This is covered in greater detail later, but the core idea here is
that synchronous operations run with @code{$} are all done together as
one transaction.  If an unhandled error occurs, any state changes
resulting from synchronous operations within that transaction will
simply not be committed.  This is useful, because it means most
otherwise difficult cleanup steps are handled automatically.

@node Promise pipelining
@section Promise pipelining

@quotation
``Machines grow faster and memories grow larger.  But the speed of
light is constant and New York is not getting any closer to Tokyo.''

--- Mark S@. Miller,
    @uref{http://www.erights.org/talks/thesis/, Robust Composition: Towards a Unified Approach to Access Control and Concurrency Control}

@end quotation

Promise pipelining provides two different features at once:

@itemize
@item
A convenient developer interface for describing a series of
asynchronous actions, allowing for invoking the objects which promises
will point to before they are even resolved (sometimes before the
objects even exist!)
@item
A network abstraction that eliminates many round trips
@end itemize

Consider the following car factory, which makes cars carrying the
company name of the factory:

@lisp
;; Create a "car factory", which makes cars branded with
;; company-name.
(define (^car-factory bcom company-name)
  ;; The constructor for cars we will create.
  (define (^car bcom model color)
    (methods                      ; methods for the ^car
     ((drive)                    ; drive the car
      (format #f "*Vroom vroom!*  You drive your ~a ~a ~a!"
              color company-name model))))
  ;; methods for the ^car-factory instance
  (methods                        ; methods for the ^car-factory
   ((make-car model color)       ; create a car
    (spawn ^car model color))))
@end lisp

Here is an instance of this car factory, called @code{fork-motors} and
spawned in @code{a-vat}:

@lisp
scheme> ,enter-vat a-vat
goblins[1]> (define fork-motors
              (spawn ^car-factory "Fork"))
@end lisp

Since asynchronous message passing with @code{<-} works across
machines, it does not matter whether interactions with
@code{fork-motors} are local or via objects communicating over the
network.  This example treat @code{fork-motors} as living on machine A,
and so the following interactions will happen with invocations
originating from machine B@.

Now send a message to @code{fork-motors} invoking the
@code{'make-car} method, receiving back a promise for the car which
will be made, which will be name @code{car-vow} (@code{-vow} being the
conventional suffix given for promises in Goblins):

@lisp
goblins[1]> ,q
scheme> ,enter-vat b-vat
;; Interaction on machine B, communicating with fork-motors on A
goblins[1]> (define car-vow
              (<- fork-motors 'make-car "Explorist" "blue"))
@end lisp

So you have a @emph{promise} to a future car reference, but not the
reference itself.  You would like to drive the car as soon as it rolls
off the lot of the factory, which of course involves sending a message
to the car.

Without promise pipelining, making use of the tools already shown (and
following the pattern most other distributed programming systems use),
you would end up with something like:

@lisp
;; Interaction on machine B, communicating with A
goblins[1]> (on car-vow                    ; B->A: first resolve the car-vow
                (lambda (our-car)          ; A->B: car-vow resolved as our-car
                  (on (<- our-car 'drive)  ; B->A: now we can message our-car
                      (lambda (val)        ; A->B: result of that message
                        (format #f "Heard: ~a\n" val)))))
@end lisp

With promise pipelining, you can simply message the promise of the car
directly.  The first benefit can be observed from code compactness, in
that you do not need to do an @code{on} of @code{car-vow} to later
message @code{our-car}; you can simply message @code{car-vow} directly:

@lisp
;; Interaction on machine B, communicating with A
goblins[1]> (on (<- car-vow 'drive)       ; B->A: send message to future car
                (lambda (val)             ; A->B: result of that message
                  (format #t "Heard: ~a\n" val)))
@end lisp

While clearly a considerable programming convenience, the other
advantage of promise pipelining is a reduction of round-trips, whether
between event-loop @emph{vats} or across machines on the network.

This can be understood by looking at the comments to the right of the
two above code interactions.  The message flow in the first case looks
like:

@example
B => A => B => A => B
@end example

The message flow in the second case looks like:

@example
B => A => B
@end example


In other words, machine B can say to machine A: ``Make me a car, and
as soon as that car is ready, I want to drive it!''

With this in mind, the promise behind Mark Miller's quote at the
beginning of this section is clear.@footnote{Like so many examples in
this document, the designs of promise pipelining and the explanation
of its value come from the E programming language, the many
contributors to its design, and Mark S@. Miller's extraordinary work
documenting that work and its history.  If you find this section
interesting, see both the
@uref{http://www.erights.org/elib/distrib/pipeline.html, Promise
Pipelining} page from @uref{http://erights.org, erights.org} and
sections 2.5 and 16.2 of
@uref{http://www.erights.org/talks/thesis/markm-thesis.pdf, Mark
Miller's dissertation}.}  If two objects are on opposite ends of the
planet, round trips are unavoidably expensive.  Promise pipelining
both allows programmers to make plans and allows Goblins to optimize
carrying out those steps as bulk operations over the network.

@node API
@chapter API

Here lie the core procedures for building and manipulating Goblins
programs!

Except where otherwise stated, code from this section can be found by
importing:

@lisp
(use-modules (goblins))
@end lisp

@menu
* Objects::
* Vats::
* Actormaps::
* OCapN The Object Capabilities Network::
@end menu

@node Objects
@section Objects

Objects are the core of Goblins.  In general, you'll need to be within
an ambient ``Goblins Context'' (TM) in order to start programming
against them. See @ref{Vats} for most event loop type programming, or
@ref{Actormaps} if you want to play with more low-level control over
transactional operations.  Most users will just use vats.

@menu
* Spawning objects::
* Synchronous invocation::
* Asynchronous invocation::
@end menu

@node Spawning objects
@subsection Spawning objects

Objects can be spawned with the @code{spawn} operator:

@lisp
(spawn CONSTRUCTOR ARGS ...)
;=> <local-refr>
@end lisp

where @code{CONSTRUCTOR} is a procedure which itself returns a
procedure representing an object's current behavior.  The
@code{CONSTRUCTOR} is implicitly passed a first argument,
traditionally labeled @code{bcom}, which can be used to change an
object's behavior.  The @code{ARGS} are passed as the remaining
arguments to the constructor.

For example, given the following constructor:

@lisp
(define* (^cell bcom #:optional val)  ; constructor (outer procedure)
  (case-lambda                        ; behavior    (inner procedure)
    (()                               ; 0-argument invocation (getter)
     val)                             ;   (return current value)
    ((new-val)                        ; 1-argument invocation (setter)
     (bcom (^cell bcom new-val)))))   ;   ("become" ^cell with new value)
@end lisp

The instantiation@dots{}

@lisp
(define some-cell (spawn ^cell 42))
@end lisp

will bind @code{val} to @code{42}.

The @code{bcom} argument warrants further explanation.  It is a
capability which allows the actor to change its own behavior.  It must
be called in a tail position, since @code{bcom} returns a
datastructure demonstrating that this object is choosing to change its
value (part of Goblins' quasi-functional design).

@code{bcom} also can take a second argument which will be returned
from the object's invocation as a return value. This allows an object
to both change its behavior and return a value with the same
invocation.

The following actor represents a consumable object that returns a
string explaining its current status:

@lisp
(define (^drink bcom drink-name portions)
  (define (drinkable-beh portions)   ; "-beh" is a common suffix for "-behavior"
    (lambda ()
      (define portions-left
        (- portions 1))
      (if (zero? portions-left)
          (bcom empty-beh
                (format #f "*GLUG!* You drink your ~a. It's empty!"
                        drink-name))
          (bcom (drinkable-beh portions-left)
                (format #f "*GLUG!* You drink your ~a. Still some left!"
                        drink-name)))))
  (define (empty-beh)
    "Sadly, your glass appears to be empty!")
  (drinkable-beh portions))
@end lisp

Here's how this works at the REPL:

@lisp
> ,vr (define root-beer (spawn ^drink "root beer" 3))
> ,vr ($ root-beer)
=> "*GLUG!* You drink your root beer. Still some left!"
> ,vr ($ root-beer)
=> "*GLUG!* You drink your root beer. Still some left!"
> ,vr ($ root-beer)
=> "*GLUG!* You drink your root beer. It's empty!"
> ,vr ($ root-beer)
=> "Sadly, your glass appears to be empty!"
@end lisp

As you can see above, @code{bcom} is also a handy way to construct
state machines, as @code{^drink} moves from drinkable to empty as it
is consumed.

@node Synchronous invocation
@subsection Synchronous invocation

To synchronously invoke two objects within the same vat / actormap,
use @code{$}:

@lisp
($ near-object args ...)
;=> something
@end lisp

Provide a synchronous call against the current message handler of
@code{NEAR-REFR}, which must be a @emph{near} @code{live-refr?}  in
the same vat as the currently running actor context.  The value
returned is that which is returned by the current behavior of
@code{NEAR-REFR} upon invocation; or, if @code{NEAR-REFR} chose to
@code{bcom} something else, the second argument passed to its
@code{bcom}; or @code{unspecified?} @code{bcom} is invoked and a
return value is not provided.

@node Asynchronous invocation
@subsection Asynchronous invocation

@lisp
(<- near-object arg ...)
;=> <local-promise>
@end lisp

Like @code{$}, but called asynchronously and returns a @emph{promise},
which may be handled with @code{on}.  Unlike @code{$}, @code{<-} is
not limited to only @emph{near} objects; interaction with @emph{far}
actors is permitted as well.

@lisp
(<-np [actor-refr live-refr?] [arg any/c] ...)
@end lisp

Like @code{<-} but does not return (or require the overhead of) a
promise.  @code{<-np} is effectively an optimization; where promises
are not needed, using @code{<-np} over @code{<-} is a good idea.

@lisp
(on vow
    [fulfilled-handler]
    [#:catch broken-handler]
    [#:finally finally-handler]
    [#:promise? #f])
@end lisp

Sets up promise handlers for @code{vow}, which is typically a
@code{live-refr?} to a @emph{promise} but may be anything.

@code{fulfilled-handler}, @code{broken-handler}, and
@code{finally-handler} all, if specified, may be either a procedure
(the most common case) which is run when @code{vow} becomes resolved;
or a reference to an actor that should be messaged when the promise is
resolved with the same arguments that would be passed to an equivalent
procedure.  As their names suggest, @code{fulfilled-handler} will run
if a promise is fulfilled and takes one argument, the fulfilled value.
@code{broken-handler} will run if a promise is broken and takes one
argument, the error value.  @code{finally-handler} will run when a
promise is resolved, no matter the outcome, and is called with no
arguments.

If @code{#:promise?} is set to @code{#t}, then @code{on} will itself
return a promise.  The promise will be resolved as follows:

@itemize
@item
If @code{vow} is fulfilled and @code{fulfilled-handler} is not
provided, the promise returned will share @code{vow}'s resolution.
@item
If @code{vow} is broken and @code{broken-handler} is not provided, the
promise returned will share @code{vow}'s broken result.
@item
If @code{vow} is fulfilled and @code{fulfilled-handler} is provided,
the resolution will be whatever is returned from
@code{fulfilled-handler}, unless @code{fulfilled-handler} raises an
error, in which case the promise will be broken with its error-value
set to this exception.
@item
If @code{vow} is broken and @code{broken-handler} is provided, the
resolution will be whatever is returned from @code{broken-handler},
unless @code{broken-handler} raises an error, in which case the
promise will be broken with its error-value set to this exception
(which may even be the original exception).
@end itemize

@node Vats
@section Vats

In order to start programming with Goblins, you will need to boot up a
vat somewhere.  In general, Goblins uses
@uref{https://github.com/wingo/fibers/, Fibers} to implement vats.
However, you can also roll your own vats should you have ``unusual''
event loop needs (@ref{Rolling your own vats}).

@menu
* Starting and stopping vats::
* Rolling your own vats::
@end menu

@node Starting and stopping vats
@subsection Starting and stopping vats

@lisp
> (define my-vat (spawn-vat))
> my-vat
=> #<vat izvD0DJT>
@end lisp

Running @code{spawn-vat} returns a vat object.  Code can be run within
the context of a vat using the @code{call-with-vat} procedure.  This
is useful for bootstrapping vats or hacking at the REPL:

@lisp
> (define my-vat (spawn-vat))
> (call-with-vat my-vat
   (lambda ()
     (define alice (spawn ^greeter "Alice"))
     ($ alice "Bob")))
=> "Hello Alice, my name is Bob!"
@end lisp

For convenience, the @code{with-vat} macro can be used instead of
@code{call-with-vat}.  Here's the above example rewritten to use
@code{with-vat}:

@lisp
> (define my-vat (spawn-vat))
> (with-vat my-vat
   (define alice (spawn ^greeter "Alice"))
   ($ alice "Bob"))
=> "Hello Alice, my name is Bob!"
@end lisp

You can also use the @code{vat-halt!} procedure to stop the vat, and
@code{vat-running?} to check its status:

@lisp
> (vat-halt! my-vat)
> (vat-running? my-vat)
=> #f
@end lisp

@strong{NOTE:} In the future, we would like vats to automatically halt
when no more references exist and thus the vat can do no more work.
The Racket version of vats works this way; it would be good for the
Guile version to do the same.  In the meanwhile, you'll need to call
@code{vat-halt!} manually.

@node Rolling your own vats
@subsection Rolling your own vats

Goblins comes with a built-in vat implementation that is
general-purpose and useful in most situations.  However, using Goblins
with a foreign event loop (such as a GUI widget toolkit or game
engine) calls for a specialized vat that knows how to hook into it.
The API described below is considered unstable and likely to change in
future releases of Goblins, so be prepared to update custom vat code
at a later date.

The @code{make-vat} constructor is used to make specialized vats.
Below is some pseudocode that illustrates the basic pattern:

@lisp
> (define (make-custom-vat)
    (define thread #f)
    (define (start churn)
      (define (loop)
        (churn (dequeue-msg))
        (loop))
      (set! thread (call-with-new-thread loop)))
    (define (halt)
      (cancel-thread thread))
    (define (send msg return?)
      (if return?
          (enqueue-msg-and-wait-for-result msg)
          (enqueue-msg msg)))
    (make-vat #:start start
              #:halt halt
              #:send send))
@end lisp

How to implement @code{enqueue-msg},
@code{enqueue-msg-and-wait-for-result}, and @code{dequeue-msg} depends
on the integration target and is left as an exercise for the
implementer.

Vat implementations must provide three hook procedures to
@code{make-vat}:

@itemize
@item
@code{start}: This procedure starts the vat message processor in the
desired foreign event loop.  It accepts a @code{churn} procedure as
its only argument.  The @code{churn} procedure accepts a message
object and processes it using the vat's underlying actormap.
@item
@code{halt}: This procedure stops vat message processing.  It is a
thunk, meaning that it accepts zero arguments.
@item
@code{send}: This procedure receives a message to process within the
vat.  It accepts two arguments: a message and a boolean flag
indicating if the result of processing the message needs to be
returned to the caller.  When the return flag is @code{#f}, vat
implementations can simply queue the message for processing and move
on.  When it is @code{#t}, however, the vat must arrange to wait and
retrieve the eventual result of processing the message.
@end itemize

Custom vat implementations @emph{must} enqueue and dequeue messages in
a thread-safe manner because incoming messages from other vats may be,
and likely are, running in a different thread.

The @code{vat-start!} procedure initiates the processing of messages
sent to the vat.

@lisp
> (define custom-vat (make-custom-vat))
> (vat-start! custom-vat)
@end lisp

Once a custom vat has been started, it can be used as usual:

@lisp
> (define alice
    (with-vat custom-vat
     (spawn ^greeter "Alice")))
@end lisp

@node Actormaps
@section Actormaps

So far this manual has dealt with vats, but there is a lower level of
abstraction in Goblins which is called an @code{actormap}.

The key differences are:

@itemize
@item
@strong{vat}: an event loop implementation that runs continuously in
its own thread.  Comes pre-built with tooling to handle message
passing between vats.  Actually wraps an actormap.
@item
@strong{actormap}: the transactional datastructure that vats use.
But, useful on its own to either build your own event loop or as a
synchronous one-turn-at-a-time mapping of actor references to their
current implementations.
@end itemize

The best way to learn is by doing, so make an actormap now:

@lisp
(define am (make-actormap))
@end lisp

Now add an actor to it.  Since cells are simple, add one of those.

@lisp
(define lunchbox
  (actormap-spawn! am ^cell))
@end lisp

What's in the lunchbox?  Take a look with @code{actormap-peek}:

@lisp
> (actormap-peek am lunchbox)
; => #f
@end lisp

An empty lunchbox@dots{} it would be nice to eat something later, so
how about packing a nice sandwich by using
@code{actormap-poke}:

@lisp
> (actormap-poke! am lunchbox 'peanut-butter-and-jelly)
> (actormap-peek am lunchbox)
; => 'peanut-butter-and-jelly
@end lisp

What if you tried to look inside the lunchbox with
@code{actormap-poke!}  instead of @code{actormap-peek}?

@lisp
> (actormap-poke! am lunchbox 'bbq-tofu)
> (actormap-poke! am lunchbox)
; => 'bbq-tofu
@end lisp

Well that worked just fine.  What happens if you do both operations
with @code{actormap-peek}?

@lisp
> (actormap-peek am lunchbox 'chickpea-salad)
> (actormap-peek am lunchbox)
; => 'bbq-tofu
@end lisp

What the@dots{}???
The lunchbox didn't change!

As said, actormaps are transactional.  You have gotten a hint of
this with the above: @code{actormap-poke!} returns a value and commits
any changes.  @code{actormap-peek} returns a value and throws any
changes away.

Actually, these two functions are just simple conveniences that wrap a
more powerful (but cumbersome to use) tool, @code{actormap-turn}:

@lisp
> (actormap-turn am lunchbox)
; => 'bbq-tofu
; => #<transactormap>
; => '()
(actormap-turn am lunchbox 'chickpea-salad)
; => *unspecified* (not printed)
; => #<transactormap>
; => '()
@end lisp

@code{actormap-turn} returns three values to its continuation: a
return value (if any; Guile's REPL doesn't print out the
unspecified value, which is what actually got returned in the second
invocation), a ``transactormap'', and a list representing messages
queued for delivery.

This @code{#<transactormap>} is interesting. It hasn't been mentioned
before, but there are really two kinds of actormaps,
``whactormaps'' (weak-hash actormaps) and ``transactormaps'' (which
hold a transaction which you can choose whether or not to commit).
Actually @code{am} is a whactormap:

@lisp
> am
; => #<whactormap>
@end lisp

It's a weak hashtable which stores the current mutable state of all
actors.

But what about that transactormap? Just running
@code{actormap-turn} on its own won't update the lunchbox either:

@lisp
> (actormap-turn am lunchbox 'chickpea-salad)
; => *unspecified* (not printed)
; => #<transactormap>
; => '()
> (actormap-turn am lunchbox)
; => 'bbq-tofu
; => #<transactormap>
; => '()
@end lisp

You need to capture the transactormap and commit it.

@lisp
> (define-values (_val tr-am _nm)
    (actormap-turn am lunchbox 'chickpea-salad))
> tr-am
; => #<transactormap>
> (transactormap-merge! tr-am)
@end lisp

Now at least the @code{am} actormap should reflect that you've switched
out the @code{'bbq-tofu} sandwich for a @code{'chickpea-salad} one:

@lisp
> (actormap-peek am lunchbox)
; => 'chickpea-salad
@end lisp

Horray!

@node OCapN The Object Capabilities Network
@section OCapN: The Object Capabilities Network

@uref{https://github.com/ocapn/ocapn, OCapN} stands for ``Object
Capability Network'' and is a suite of protocols for communication
between distributed, networked objects.  In other words, it's how
Goblins actors can talk to actors running on another computer.

OCapN uses the @uref{http://erights.org/elib/distrib/captp/index.html,
Capability Transport Protocol (CapTP)} as the core protocol for
enabling distributed programming in a mutually suspicious network.  It
originated in the @uref{http://www.erights.org/, E programming
language} but has since appeared in @uref{https://capnproto.org/,
Cap'N Proto}, @uref{http://waterken.sourceforge.net/, Waterken},
@uref{https://agoric.com/, Agoric}'s
@uref{https://github.com/Agoric/agoric-sdk/tree/master/packages/SwingSet,
SwingSet}, and now Goblins.

@strong{CAUTION}: CapTP support is still in its early days.  Please do
not rely on the protocol being stable at this time.

@menu
* CapTP The Capability Transport Protocol::
* Launching a Tor daemon for Goblins::
* Example Two Goblins programs chatting over CapTP via Tor::
* Using the CapTP API::
* Netlayers::
@end menu

@node CapTP The Capability Transport Protocol
@subsection CapTP: The Capability Transport Protocol

OCapN's CapTP has an abstract ``netlayer'' interface, allowing
communication over many different protocols ranging from Tor Onion
Services to IBC to I2P to libp2p to perhaps carrier pigeons with
backpacks full of encrypted MicroSD cards.  Currently, Goblins only
supports the Tor Onion Services netlayer.

Benefits of CapTP:

@itemize
@item
Invocation of remote objects resembles the same as with local objects.
You can use @code{<-} and @code{on} which means that most programs
that were originally designed for local-only computing
naturally scale out to a networked environment.
@item
All this is done while mostly hiding the abstraction of the networked
protocol from the user.
@item
Object capability security is upheld.  A remote machine cannot make
use of any capability that has not been handed to it.
@item
Live object references between CapTP endpoints are incredibly cheap,
merely represented as integers on each side.  This keeps message sizes
small and efficient.
@item
CapTP provides (acyclic) distributed garbage collection.  Remote
machines can indicate when they no longer need an object and the
machine locally containing that reference can reclaim it if
appropriate.
@item
Promise pipelining means that messages can be sent to the resolution
of a promise before that resolution actually occurs.  Over the network
this is represented as a pipeline of messages.  This can reduce round
trips significantly, which is a big win.

To re-quote Mark S@. Miller:

@quotation
Machines grow faster and memories grow larger.  But the speed of light
is constant and New York is not getting any closer to Tokyo.
@end quotation
@item
CapTP is written independently of network transport abstractions.  It
can be run over local Unix domain sockets, an OpenSSL connection, Tor
Onion Services, or something custom.  CapTP operates under the
assumption of secure pairwise channels; the layer which provides the
pairwise channels is called ``MachineTP'' and can be written in a
variety of ways.  A simple MachineTP abstraction is provided, but
presently still requires some manual wiring.  In the future, even
simpler abstractions will be provided which cover most user needs.
@end itemize

All of these combine into an efficient and powerful protocol that,
most powerfully of all, the author of Goblins programs need not
think too much about.  This circumvents the usual years and years of
careful message structure coordination and standardization for many
kinds of distributed programs, which can simply be written as normal
Goblins programs rather than bespoke protocols.

Limitations of CapTP:

@itemize
@item
Goblins' CapTP provides @emph{acyclic} distributed garbage collection.
Cycles between servers are not automatically recognized.  Full
@uref{http://erights.org/history/original-e/dgc/, cycle-collecting
distributed garbage collection} has been written, but requires special
cooperation from the garbage collector that is not available in
Guile (or in most languages).
@item
Goblins' CapTP does not do anything about memory usage or resource
management on its own.  (Features for this will come as Spritely
sub-projects in the future.)
@item
While CapTP in theory routes capabilities to specific remote objects,
since the network is mutually suspicious one can't assume that the
remote end isn't conspiring some way to hand those capabilities to
other unexpected objects.  The right way to think about this
from an object capability perspective is that a remote misbehaving
machine is equivalent to a misbehaving object with the surface area of
the entire machine.
@item
@strong{TEMPORARY}: The API is heavily in flux.
@end itemize

@node Launching a Tor daemon for Goblins
@subsection Launching a Tor daemon for Goblins

In order for Goblins' Onion Service netlayer to work, it needs to talk
to a Tor daemon.  Goblins can set up and manage the Onion Services
itself once it connects to the Tor daemon.  So far it seems like
running a single Goblins Tor process ``as your user'' and letting
various Goblins processes connect to it is the easiest option.

Here's an example configuration file template (replace @code{<user>}
with your actual username):

@example
DataDirectory /home/<user>/.cache/goblins/tor/data/
SocksPort unix:/home/<user>/.cache/goblins/tor/tor-socks-sock RelaxDirModeCheck
ControlSocket unix:/home/<user>/.cache/goblins/tor/tor-control-sock RelaxDirModeCheck
Log notice file /home/<user>/.cache/goblins/tor/tor-log.txt@}|
@end example

Write this configuration to @file{~/.config/goblins/tor-config.txt}.

Create the necessary cache directory:

@example
mkdir -p ~/.cache/goblins/tor/data
@end example

Now launch the Tor daemon:

@example
tor -f ~/.config/goblins/tor-config.txt
@end example

@node Example Two Goblins programs chatting over CapTP via Tor
@subsection Example: Two Goblins programs chatting over CapTP via Tor

Before diving into API details, let's take a look at a couple of small
example programs to demonstrate that this stuff works.

Here's our client script named @file{captp-alice.scm}:

@lisp
(use-modules (fibers conditions)
             (fibers operations)
             (goblins)
             (goblins ocapn ids)
             (goblins ocapn captp)
             (goblins ocapn netlayer onion)
             (ice-9 match))

;; Create a CapTP router using Tor Onion Services.
(define machine-vat (spawn-vat))
(define-values (onion-netlayer private-key service-id)
  (with-vat machine-vat
    (new-onion-netlayer)))
(define mycapn
  (with-vat machine-vat
    (spawn-mycapn onion-netlayer)))

;; Convert the command-line argument into a sturdyref for Bob.
(define bob-uri
  (match (command-line)
    ((_ uri) uri)))
(define bob-sref (string->ocapn-id bob-uri))

;; Create a vat for Alice and enliven Bob.
(define a-vat (spawn-vat))
(define bob-vow
  (with-vat a-vat
    (<- mycapn 'enliven bob-sref)))

;; Send a message to Bob and print the response.
(define done? (make-condition))
(with-vat a-vat
  (on (<- bob-vow "Alice")
      (lambda (response)
        (format #t "Alice heard back: ~a" response)
        (signal-condition! done?))))

;; Wait until Alice has received a response before exiting.
(perform-operation (wait-operation done?))
@end lisp

Traditionally, Alice talks to Bob.  So, now we need Bob.  Save the
following server script as @file{captp-bob.scm}:

@lisp
(use-modules (fibers conditions)
             (fibers operations)
             (goblins)
             (goblins ocapn ids)
             (goblins ocapn captp)
             (goblins ocapn netlayer onion))

;; Bob is going to be a greeter that says hello to other people.
(define (^greeter _bcom our-name)
  (lambda (your-name)
    (format #f "Hello ~a, my name is ~a!" your-name our-name)))

;; Create Bob in their own vat.
(define b-vat (spawn-vat))
(define bob (with-vat b-vat (spawn ^greeter "Bob")))

;; Create a CapTP router using Tor Onion Services.
(define machine-vat (spawn-vat))
(define-values (onion-netlayer private-key service-id)
  (with-vat machine-vat
    (new-onion-netlayer)))
(define mycapn
  (with-vat machine-vat
    (spawn-mycapn onion-netlayer)))

;; Create a sturdyref for Bob and print it.
(define bob-sref
  (with-vat machine-vat
    ($ mycapn 'register bob 'onion)))
(format #t "Bob's sturdyref: ~a"
        (ocapn-id->string bob-sref))

;; Hold the process open indefinitely.
(perform-operation (wait-operation (make-condition)))
@end lisp

Okay, time to try it out!  Open up two terminals, and in the first one
run:

@example
guile captp-bob.scm
@end example

This will print out a captp ``sturdyref'' URI to the terminal.  Copy
it and paste it in the second terminal as the argument to @code{guile
captp-alice.scm}:

@example
guile captp-alice.scm <STURDYREF-GOES-HERE>
@end example

Tor Onion Services can take awhile to establish, but after a short
wait you should see:

@example
Alice heard back: Hello Alice, my name is Bob!
@end example

If you see the same output then your connection succeeded!  Yay! The
next sections will get into the details of how to use the CapTP API@.

@node Using the CapTP API
@subsection Using the CapTP API

Goblins uses an actor to communicate over CapTP@.  This actor can be
spawned using the @code{spawn-mycapn} procedure from the
@code{(goblins ocapn captp)} module:

@lisp
> (define mycapn (spawn-mycapn netlayer))
@end lisp

Where @code{netlayer} refers to a CapTP netlayer object.  See the next
section for details on available netlayers.

Local actors need to be registered so that they can receive messages
over CapTP@.  Registering an actor generates a CapTP identifier for
that actor:

@lisp
> (define alice (spawn ^greeter "Alice"))
> (define alice-captp-id ($ mycapn 'register alice 'onion))
@end lisp

To use this actor on another machine, that machine needs a
``sturdyref'' to the actor.  A sturdyref is a special URI that
uniquely identifies the actor on the network.  The
@code{ocapn-id->string} procedure from the @code{(goblins ocapn ids)}
module can generate such a URI:

@lisp
> (ocapn-id->string community-sref)
=> "ocapn://jv4arqqwntmxs3rljkx3ao5bucci37rxxb575vypovntyve76mmyf4ad.onion/s/nGxw4_p6s91IF-R5r6MMYsZzoByODX46MV7AWTApX5s"
@end lisp

To generate a Guile URI object instead of a string, use
@code{ocapn-id->uri} instead.

On the other machine, the sturdyref can be ``enlivened'' to create a
promise that, when resolved, yields a remote object:

@lisp
> (define vow ($ mycapn 'enliven "ocapn://..."))
> vow
=> #<local-promise>
> (on vow
      (lambda (obj)
        (display obj)
        (newline)))
; #<remote-object>
@end lisp

Sending messages to remote objects using @code{<-} looks the same as
sending messages to local objects.  The message will be transparently
sent over CapTP to the remote object!

@enumerate
@item
@anchor{Keeping a persistant sturdyref for an object}Keeping a persistant sturdyref for an object


When an object is registered, it is given a ``swiss num'' (object
specific part of the sturdyref). This can be extracted from the ocapn
id:

@lisp
> (define swiss-num (ocapn-sturdyref-swiss-num alice-captp-id))
> swiss-num
=> #vu8(156 108 112 227 250 122 179 221 72 23 228 121 175 163 12 98 198 115 160 28 142 13 126 58 49 94 192 89 48 41 95 155)
@end lisp

Often it is desirable to have an object have a persistant sturdyref
between sessions; to do this, you need to do two things:

@itemize
@item
Register the object at a specific swiss num
@item
Restore the netlayer (see the netlayer section)
@end itemize

To install the object at a given swiss num, get the nonce
registry. This is an object which holds all of the swiss nums to each
registered object in mycapn. The following is how this can be done:

@lisp
> (define registry ($ mycapn 'get-registry)) ;; nonce registry
> (define alice-captp-id ($ registry 'register alice swiss-num))
@end lisp
@end enumerate

@node Netlayers
@subsection Netlayers

@enumerate
@item
@anchor{Tor Onion Services}Tor Onion Services


Assuming a Tor daemon is running, a Goblins Onion netlayer can be
created using the @code{new-onion-netlayer} procedure from the
@code{(goblins ocapn netlayer onion)} module:

@lisp
> (define-values (onion-netlayer private-key service-id)
    (new-onion-netlayer))
@end lisp

That netlayer can then be used to spawn an OCapN router actor:

@lisp
> (define mycapn (spawn-mycapn onion-netlayer))
@end lisp

Each time @code{new-onion-netlayer} is called it generates a new
@code{private-key} and @code{service-id}.  If you wish for these to
persist, they need to be stored (securely, as anyone with them has
the capability to host at them) and call @code{restore-onion-netlayer}
providing them. An example of this is:

@lisp
> (define-values (onion-netlayer _private-key _service-id)
    (restore-onion-netlayer private-key service-id))
@end lisp
@end enumerate

@node actor-lib A standard library of sorts
@chapter actor-lib: A standard library of sorts

The Goblins actor library, in the @code{(goblins actor-lib ...)}
module namespace, provides implementations for a variety of common
actor model patterns.

@menu
* Cells::
* Methods::
* Joiners::
* Sealers::
@end menu

@node Cells
@section Cells

The @code{(goblins actor-lib cell)} module provides a very handy actor
called a ``cell.''  Cells are used to store arbitrary data.

New cells are created with the constructor @code{^cell}:

@lisp
> (define chest (spawn ^cell 'gold))
@end lisp

The current value of a cell can be retrieved by sending an empty
message to the cell:

@lisp
> ($ chest)
=> gold
@end lisp

The value of a cell can be changed by sending a message containing the
new value:

@lisp
> ($ chest 'sword)
> ($ chest)
=> sword
@end lisp

@node Methods
@section Methods

The @code{(goblins actor-lib methods)} module provides a simple,
single-dispatch method system for actor behaviors.

Here's a constructor for an actor that can say hello or goodbye:

@lisp
> (define (^hello-goodbye _bcom)
    (methods
     ((say-hello name)
      (format #f "Hello, ~a!" name))
     ((say-goodbye name)
      (format #f "Goodbye, ~a!" name))))
@end lisp

The @code{methods} macro is used to describe a collection of messages
that an actor accepts.  The first argument of the message is used to
dispatch the proper behavior for handling that message.

Try it out:

@lisp
> (define hello-goodbye (spawn ^hello-goodbye))
> ($ hello-goodbye 'say-hello "Alice")
=> "Hello, Alice!"
> ($ hello-goodbye 'say-goodbye "Alice")
=> "Goodbye, Alice!"
@end lisp

@node Joiners
@section Joiners

The @code{(goblins actor-lib joiners)} module provides a means of
combining the results of many promises.

The @code{all-of} procedure returns a new promise that waits for all
of the given promises to resolve before resolving itself.  This is
very useful when you need to wait for several asynchronous operations
to complete successfully before moving on.

To demonstrate this, here's a very useless actor that waits for
awhile before returning the same thing it received:

@lisp
> (define (^procrastinator _bcom delay)
    (lambda (x)
      (sleep delay)
      x))
@end lisp

You can use @code{all-of} to wait for all procrastinators to finish
procrastinating before writing some output:

@lisp
> (define a-vat (spawn-vat))
> (define b-vat (spawn-vat))
> (define c-vat (spawn-vat))
> (define p1 (with-vat b-vat (spawn ^procrastinator 1)))
> (define p2 (with-vat c-vat (spawn ^procrastinator 2)))
> (with-vat a-vat
    (on (all-of (<- p1 'foo) (<- p2 'bar))
        (lambda (items)
          (display items)
          (newline))))
; (foo bar)
@end lisp

@strong{Note}: Currently, @code{all-of} calls the resolution procedure
with a list as its only argument.  In a future release of Goblin you
will be able to call the resolution procedure with multiple arguments,
one for each promise passed to @code{all-of}.

@node Sealers
@section Sealers

The @code{(goblins actor-lib sealers)} module provides a mechanism for
ensuring the authenticity of data.  Using sealers, data can be hidden
within a wrapper and marked with a unique brand to produce a sealed
object.  A sealed object can be checked to verify that it has been
marked with the expected brand.  An authentic sealed object can then
be unsealed to reveal the data within.  Sealers and unsealers are
analagous to public key cryptography where sealing resembles
encryption, unsealing resembles decryption, and the brand check
predicate resembles signature verification.  However, sealers work
without any cryptography at all!

Sealers are comprised of three distinct capabilities: the sealer, the
unsealer, and the brand check.  Using separate capabilities allows for
fine-grained privilege management.  For example, an actor that only
has the brand check capability cannot seal or unseal data.

Imagine a scenario where you are protecting lunchtime meals using
sealers and unsealers. Your rival, who wishes to sabotage you, does
the same:

@lisp
> (define-values (our-lunch:seal our-lunch:unseal our-can?)
    (spawn-sealer-triplet))
> (define-values (rival-lunch:seal rival-lunch:unseal rival-can?)
    (spawn-sealer-triplet))
@end lisp

Calling the @code{spawn-sealer-triplet} procedure returns three new
actors representing the seal, unseal, and check capabilities.  You give
your customer the unsealer, the delivery driver the brand predicate,
and keep the sealer to yourself so no one else can brand their
lunch as yours.

A value can be sealed by sending it as a message to the sealer. Put
some fried rice in a can by sending a message to the sealer:

@lisp
> ($ our-lunch:seal 'fried-rice)
=> #<local-object sealed-value>
@end lisp

The contents of sealed cans are private and cannot be seen by
inspecting the sealed object.

Your customer wants some chickpea salad, so seal some for them:

@lisp
> (define chickpea-lunch ($ our-lunch:seal 'chickpea-salad))
@end lisp

Your truck driver is able to check that the food they are to deliver
really is from you (you have a reputation to uphold!) by sending a
message to the brand predicate:

@lisp
> ($ our-can? chickpea-lunch)
=> #t
> ($ our-can? ($ rival-lunch:seal 'melted-ice-cream))
=> #f
@end lisp

The customer is able to open up their can by sending it to the
unsealer:

@lisp
> ($ our-lunch:unseal chickpea-lunch)
=> chickpea-salad
@end lisp

@node Thanks
@chapter Thanks

This manual was primarily written by Christine Lemmer-Webber with
additional text by Jessica Tallon, David Thompson, and Juliana Sims.

Many of the ideas are borrowed from
@uref{http://www.erights.org/talks/thesis/markm-thesis.pdf, Mark
Miller's dissertation}, which is an excellent, if nerdy, read.

Jessica Tallon, Jonathan A@. Rees, Randy Farmer, David Thompson,
and Juliana Sims provided review and feedback.

@node License
@chapter License

@emph{(C) 2019-2023 Christine Lemmer-Webber, David Thompson, Jessica
Tallon, the Spritely Institute, and other contributors.  See
@file{AUTHORS} for details.}

@emph{Both Spritely Goblins and this manual are released under the
terms of the following license:}

@include apache-2.0.texi

@bye
