#+TITLE: Spritely Goblins
#+AUTHOR: Christine Lemmer-Webber
#+SUBAUTHOR: The Spritely Institute
#+EMAIL: christine@spritely.institute

#+OPTIONS: ':t toc:t author:t email:t
#+LANGUAGE: en

#+TEXINFO_FILENAME: goblins.info
#+TEXINFO_HEADER: @syncodeindex pg cp

#+TEXINFO_DIR_CATEGORY: The Algorithmic Language Scheme

#+TEXINFO_DIR_TITLE: Goblins: (goblins)
#+TEXINFO_DIR_DESC: Distributed programming environment and Spritely's core (Guile edition).

This is the manual for [[https://spritelyproject.org/#goblins][Spritely Goblins]], a distributed object
programming environment.
Spritely Goblins is a project of the [[https://spritely.institute/][Spritely Institute]] and is
built to be the core layer for building Spritely's broader
decentralized networking technologies.

Both this manual and Guile Goblins itself are released under
Apache v2.  See [[* License][License]] for more information.

* What is Goblins?

[[https://spritelyproject.org/#goblins][Spritely Goblins]] is a distributed object programming environment.
Features:

 - *Quasi-functional object system:*
   Users hold on to references of objects/actors, but objects/actors
   are just procedures.
   Rather than directly mutating, objects/actors can specify that
   they should "become" a new version of themselves when they
   handle the next invocation.

 - *Fully distributed, networked, secure p2p communication:*
   Via OCapN, the Object Capability Network (which features CapTP, the
   Capability Transport Protocol), you can communicate with other
   objects over a network connection.  Distributed object interactions
   are safe because of ocap security guarantees.

 - *Transactional updates:*
   Changes happen within a transaction.
   If an unhandled exception occurs, we can "roll back" history
   as if the message never happened, avoiding confused state
   changes throughout the system.

 - *Time travel:*
   We can snapshot old revisions of the system and
   interact with them.

 - *Asynchronous programming with sophisticated promise chaining:*
   Asynchronous message passing with promises is supported.
   Promises work such that there's no need to wait for promises
   to resolve before interacting... you can communicate with the
   future that doesn't even yet exist!
   Sent a message to that remote car factory asking for a new car?
   Why wait for the car to be delivered... you can send it a
   drive message at the same time, and both messages can be
   delivered across the network in a single hop.

 - *Communicating event loops:*
   Objects across multiple event loops (aka "vats") can
   communicate, whether in the same OS process or (soon) across
   the network.

 - *Synchronous and asynchronous behavior, integrated but distinguished:*
   Both synchronous and asynchronous programming is supported,
   but only objects in the same "vat" (event loop) can perform
   synchronous immediate calls.
   All objects can perform asynchronous calls against each other.

 - *A library, not a language:*
   Goblins is itself a library that can be utilized across a wide
   variety of Guile programs.

 - *Object capability security:*
   Goblins itself is built for object capability (ocap) security,
   which is to say that you can only operate on the references
   you have access to.
   Goblins embraces and builds upon this foundation.
   (However, full ocap security will require utilizing the
   sandboxing features of Guile; demonstrations of this coming soon.)


Goblins' design is inspired by the [[http://www.erights.org/][E programming language]] and by the
observation that [[http://mumble.net/~jar/pubs/secureos/secureos.html][lambda is already the ultimate security mechanism]]
(ie, normal argument-passing in programs, if taken seriously/purely,
is already all the security system we need).

Spritely is a wider project to advance decentralized networking
infrastructure, particularly as it pertains to social networks.
Goblins is the heart of the system, on which other layers are built.
At the time of writing, two key versions of Goblins are supported, the
[[https://docs.racket-lang.org/goblins/index.html][Racket version of Goblins]], and the [[https://www.gnu.org/software/guile/][Guile]] version.
This manual is for the Guile edition of Spritely Goblins.

This manual is also very, very incomplete in this early release.
Please see the [[https://docs.racket-lang.org/goblins/][manual for the Racket version of Goblins]] manual,
most of which applies to the Guile version too.

[fn:on-actors-and-objects] Goblins uses the term "object" and "actor"
somewhat interchangably, even though in some ways these terms have
become vague.  There are, in particular,
[[http://mumble.net/~jar/articles/oo.html][many meanings for the word "object"]]; for us, object really means an
encapsulation of behavior and state.  (In Goblins, state is typically
built out of behavior, not the other way around.)
Goblins also follows the [[https://en.wikipedia.org/wiki/Actor_model#Fundamental_concepts][classic actor]] model mostly, in that
in response to a message, an "actor" can:
(a) send a finite number of messages to other actors;
(b) create a finite number of new actors; or
(c) designate the behavior to be used for the next message it receives.
However, Goblins supports both synchronous call-return invocation of
actors within the same event loop via =$= and asynchronous message
sends via =<-=.  Arguably the true "classic actor" model only supports
the latter.

* Getting started

** Installing Goblins

You'll need to install =guile-goblins=.  Either use [[https://guix.gnu.org/][Guix]] or use your
standard GNU/Linux distro's package for =guile-goblins= (if it exists)
or even better yet run Guix as your standard distro.

See the =HACKING= and =README= files with git checkouts / release
tarballs otherwise to install.

** Setup for hacking on Goblins

You're going to want/need:

 - [[https://www.gnu.org/software/emacs/][GNU Emacs]]
 - [[https://www.nongnu.org/geiser/][Geiser]], for hacking on Guile

Then, at minimum, you'll want to put in your .emacs:

#+BEGIN_SRC emacs-lisp
(show-paren-mode 1)  ; Match parentheses
#+END_SRC

However you probably also want some combination of:

 - [[https://github.com/Fuco1/smartparens][smartparens]] (or [[https://www.emacswiki.org/emacs/ParEdit][paredit]], which is much more strict... use
   smartparens if uncertain)
 - [[https://github.com/Fanael/rainbow-delimiters][rainbow-delimeters]]
 - [[https://www.emacswiki.org/emacs/HighlightParentheses][highlight-parentheses]]

Now you'll have a nice hacking setup!  Be sure to read the Geiser
manual.

** TEMPORARY: Live hacking "fix"

The traditional way to hack Guile is to use Geiser, both evaluating
from some =foo.scm= file/buffer with more "permanent" code via, for
example, the =C-x C-e= / =C-x C-b= / =C-x C-k= commands to evaluate an
expression, evaluate a whole buffer, or compile a buffer's content,
and switching back and forth between that and the (usually called
=*Geiser Guile REPL*=) experimental-hacking-and-debugging REPL.

This works with Goblins, but Geiser does some things to temporarily
redirect output/error ports when doing the file/buffer oriented
evaluation, and unfortunately this results in Goblins vats potentially
breaking due to spawning a separate thread which inherit these
temporarily redirected ports, which then are closed when the
evaluation succeeds.  We have a long-term plan to deal with this, but
in the meanwhile, whenever you start a Guile / Geiser hacking session,
first execute:

#+BEGIN_SRC scheme
  > (use-modules (goblins))
#+END_SRC

... from the =*Geiser Guile REPL*=.  Otherwise vats may mysteriously
"hang".  We know this is an annoyance!  It'll be fixed soon!


* A high level view of Goblins

Let's start with a sketch of a network of Goblins objects wired
to communicate with each other:

#+BEGIN_SRC text
  .----------------------------------.         .----------------------.
  |            Machine 1             |         |       Machine 2      |
  |            =========             |         |       =========      |
  |                                  |         |                      |
  | .--------------.  .---------.   .-.       .-.                     |
  | |    Vat A     |  |  Vat B  |   |  \______|  \_   .------------.  |
  | |  .---.       |  |   .-.   | .-|  /      |  / |  |    Vat C   |  |
  | | (Alice)----------->(Bob)----' '-'       '-'  |  |  .---.     |  |
  | |  '---'       |  |   '-'   |    |         |   '--->(Carol)    |  |
  | |      \       |  '----^----'    |         |      |  '---'     |  |
  | |       V      |       |         |         |      |            |  |
  | |      .----.  |       |        .-.       .-.     |  .------.  |  |
  | |     (Alfred) |       '-------/  |______/  |____---( Carlos ) |  |
  | |      '----'  |               \  |      \  |     |  '------'  |  |
  | |              |                '-'       '-'     '------------'  |
  | '--------------'                 |         |                      |
  |                                  |         |                      |
  '----------------------------------'         '----------------------'
#+END_SRC

In the above diagram, we see:

 - Two machines (=Machine 1= and =Machine 2=, running separately from
   each other, but connected to each other over the network via OCapN
   and CapTP.

 - =Vat A= and =Vat B= are event loops which live on =Machine 1=,
   and =Vat C= is an event loop which live son =Machine 2=.

 - The individual objects (represented by circles) live in /vats/,
   aka event loops which contain objects.  =Alice= and
   =Alfred= live in =Vat A=, =Bob= lives in =Vat B=, and =Carol= and
   =Carlos= live on =Vat C=.  (While we've given these objects
   human-like names, they're just Goblins objects.)

 - The arrows between the objects represent references these objects
   have to each other.  =Alice= has references to both =Alfred= and
   =Bob=.  =Bob= has a reference to =Carol=.  =Carlos= has a reference
   to =Bob=.

 - Two objects which are in the same vat are considered /near/ each
   other, and thus can invoke each other synchronously, whereas any
   objects not in the same vat are considered /far/ from each other.
   Any objects can invoke each other by asynchronous message
   passing... assuming they have a reference to each other.

 - Not pictured: each vat has an /actormap/, an underlying
   transactional heap used for object communication.  This is what
   permits transactionality and time travel.  (Actormaps can also used
   independently of vats for certain categories of applications.)

Another way to think about this is via the following abstraction
nesting dolls:

#+BEGIN_SRC scheme
  (machine (vat (actormap {refr: object-behavior})))
#+END_SRC

 - *Machines*, which are computers on the network, or more
   realistically, operating system processes, which contain...
 - *Vats*, which are communicating event loops, which contain...
 - *Actormaps*, transactional heaps, which contain...
 - A mapping of *References* to *Object Behavior*.

** The "vat model" of computation

As said, Goblins follows what is called the /vat model/ of
computation.
A /vat/ is simply an event loop that manages a set of
objects which are /near/ to each other (and similarly, objects outside
of a vat are /far/ from each other).

Objects which are /near/ can perform synchronous call-return
invocations in a manner familiar to most sequential programming
languages used by most programmers today.  Aside from being
a somewhat more convenient way to program, sequential invocation
is desirable because of cheap /transactionality/, which we shall
expand on more later.  In Goblins, we use the =$= operator
to perform synchronous operations.

Both /near/ and /far/ objects are able to invoke each other
asynchronously using asynchronous message passing (in the same style
as the /classic actor model/).  It does not
generally matter whether or not a /far/ object is running within the
same OS process or machine or one somewhere else on the
network for most programming tasks; asynchronous
message passing works the same either way.  In Goblins, we use the
=<-= operator to perform asynchronous operations.
# [fn:classic-actors] [fn:session-severance]

For both programmer convenience and for networked efficiency, Goblins
supports /promise pipelining/: messages can be sent to promises which
have not yet resolved, and will be forwarded to the target once the
promise resolves.
The sender of the message is handed back a promise to which it can
supply callbacks, listening for the promise to be fulfilled with a
value or broken (usually in case of an unexpected error).
# [fn:full-promise-vision]

As usual in the vat model of computation, individual message sends to
a vat (event loop) are queued and then handled one /turn/ at a time,
akin to the way board game players take turns around a table (which is
indeed the basis for the term /turn/).

The message, addressing a specific object, is passed to the recipient
object's current behavior.  This object may then invoke other
/near/ objects (residing within the same vat), which may themselves
invoke other near objects in a synchronous and sequential call-return
style familiar to most users of most contemporary programming
languages.  Any of these invoked objects may also change their
state/behavior (behavior changes appear purely functional in Goblins;
invocations of other actors do not), spawn new objects, invoke
ordinary expressions from the host language, or send asynchronous
messages to other objects (which are only sent if the /turn/ completes
successfully).

While the /vat model/ of computation is not new (it originates in the
[[http://erights.org/][E]] programming language and can trace some of its ideas back to E's
predecessor [[http://erights.org/history/joule/][Joule]], and has since reappeared in systems such as
[[https://agoric.com/][Agoric's]] [[https://github.com/Agoric/agoric-sdk/tree/master/packages/SwingSet][SwingSet]] kernel), Goblins brings some novel contributions to
the table in terms of transactionality and time-travel debugging,
enhancing an already powerful distributed programming paradigm.

* Tutorial

** A simple greeter

First, let's import Goblins:

#+BEGIN_SRC scheme
  > (use-modules (goblins))
#+END_SRC

(*NOTE*: See [[*TEMPORARY: Live hacking "fix"][TEMPORARY: Live hacking "fix"]] if you haven't.)

Goblins actors live in special event loops called /vats/.
Let's make a vat to play around with and "enter" it at the REPL:

#+BEGIN_SRC scheme
scheme> (define a-vat (spawn-vat))
scheme> ,enter-vat a-vat
goblins[1]>
#+END_SRC

Now let us implement a friend who will greet us:

#+BEGIN_SRC scheme
(define (^greeter bcom our-name)   ; constructor (outer procedure)
  (lambda (your-name)              ; behavior    (inner procedure)
    (format #f "Hello ~a, my name is ~a!"
            your-name our-name)))
#+END_SRC

Let's give it a try by instantiating an instance of =^greeter= using
=spawn= and assign her to the variable =alice=:

#+BEGIN_SRC scheme
 > (define alice
     (spawn ^greeter "Alice"))
#+END_SRC

The first argument to =spawn= is the constructor we will use to make
our Goblins object, in this case =^greeter=.
The remaining arguments will be passed to the constructor,
along with an implicit argument which can be used to change object
behavior called =bcom= (pronounced "become").
Thus ="Alice"= maps to =our-name=.

We can invoke =alice= by using =$= for a synchronous call-return
operation:

#+BEGIN_SRC scheme
goblins[1]> (define alice
              (spawn ^greeter "Alice"))
goblins[1]> ($ alice "Alfred")
; => "Hello Alfred, my name is Alice!"
#+END_SRC

The first argument to =$= is the object to be invoked, the remaining
arguments are passed to the "behavior" of the object.
Thus =your-name= in =^greeter='s behavior procedure is bound to
="Alfred"=.
The behavior procedure thus proceeds with formatting and returning the
greeting string.

We can exit the subrepl for =a-vat= with =,q= (the same way as if
Guile put us in a subrepl to debug an error):

#+BEGIN_SRC scheme
goblins[1]> ,q
scheme>
#+END_SRC

As you have probably inferred, Goblins-specific operations such as =$=
and =spawn= happen within a context (typically a /vat/, though there is
an even lower-level structure called an /actormap/ which we will see
more about later).
However, the subrepl entered by =,enter-vat= is a convenience for
hacking.
We can run also run code within =a-vat= like so:

#+BEGIN_SRC scheme
  scheme> (a-vat (lambda () ($ alice "Arthur")))
  ; => "Hello Arthur, my name is Alice!"
#+END_SRC

Very few operations in Goblins spend time operating on vats directly;
typically commands like the above only happen when bootstrapping the
initial set of actors within a vat or when hacking, then the actors
within the vats do their own thing.

** State as updating behavior

Re-enter =a-vat='s subrepl if you haven't:

#+BEGIN_SRC scheme
scheme> ,enter-vat a-vat
goblins[1]>
#+END_SRC

Let's introduce a simple cell which stores a value.
This cell will have two methods:
='get= retrieves the current value, and ='set= replaces
the current value with a new value.

#+BEGIN_SRC scheme
(define* (^cell bcom #:optional [val #f])
  (case-lambda
    (()         ; get
     val)
    ((new-val)  ; set
     (bcom (^cell bcom new-val)))))
#+END_SRC

=case-lambda= allows for dispatching depending on the number of
arguments, so here we're choosing that if no arguments are provided,
our cell shares the current value, and if one argument is provided,
the cell updates itself to become a cell storing the new value.

Cells hold values, and so do treasure chests, so let's make
a treasure chest flavored cell.
Taking things out and putting them back in is easy:

#+BEGIN_SRC scheme
  goblins[1]> (define chest
                (spawn ^cell "sword"))
  goblins[1]> ($ chest)
  ; => "sword"
  goblins[1]> ($ chest "gold")
  goblins[1]> ($ chest)
  ; => "gold" 
#+END_SRC

Now we can see what =bcom= is: a capability specific to this object
instance which allows it to change its behavior!
(For this reason, =bcom= is pronounced "become"!)

** Methods aren't essential, but they are useful

The most common way to select different sub-behaviors isn't by the
number of arguments though.
It's much more common to have "methods" that are selected by name.
We can use the =methods= macro to do just that:

#+BEGIN_SRC scheme
(use-modules (goblins actor-lib methods))

(define* (^mcell bcom #:optional [val #f])
  (methods
   ((get)
    val)
   ((set new-val)
    (bcom (^mcell bcom new-val)))))
#+END_SRC

The use of =^mcell= is similar, but now we pass in a first argument
as a symbol selecting the method, and the rest of the arguments are
passed to the object:

#+BEGIN_SRC scheme
  goblins[1]> (define jar
                (spawn ^mcell "cookies"))
  goblins[1]> ($ jar 'get)
  ; => "cookies"
  goblins[1]> ($ jar 'set "crumbs")
  goblins[1]> ($ jar 'get)
  ; => "crumbs"
#+END_SRC

Methods aren't particularly magical... the =methods= macro just
returns a procedure which is convenient to use for procedure dispatch:

#+BEGIN_SRC scheme
  > (define foo-or-bar
      (methods
       ((foo)
        'called-foo)
       ((bar arg)
        (list 'called-bar-with arg))))
  > (foo-or-bar 'foo)
  ; => called-foo
  > (foo-or-bar 'bar "meep")
  ; => (called-bar-with "meep")
#+END_SRC

So really, =methods= just makes a particularly useful kind of
behavior procedure for us, one which takes a first argument for
the method name, grabs the rest of the arguments, and then applies
them to the relevant method.

** Objects which contain objects

Objects can also contain and define other object references, including
in their outer constructor procedure.

Here is the definition of a "counting greeter" we call =^cgreeter=:

#+BEGIN_SRC scheme
(define (^cgreeter _bcom our-name)
  (define times-called
    (spawn ^mcell 0))
  (methods
   ((get-times-called)
    ($ times-called 'get))
   ((greet your-name)
    ;; increase the number of times called
    ($ times-called 'set
       (+ 1 ($ times-called 'get)))
    (format #f "[~a] Hello ~a, my name is ~a!"
            ($ times-called 'get)
            your-name our-name))))
#+END_SRC

As we can see near the top, =times-called= is instantiated as an
=^cell= like the one we defined earlier.
The current value of this cell is returned by =get-times-called=
and is updated every time the =greet= method is called:

#+BEGIN_SRC scheme
  goblins[1]> (define julius
                (spawn ^cgreeter "Julius"))
  goblins[1]> ($ julius 'get-times-called)
  ; => 0
  goblins[1]> ($ julius 'greet "Gaius")
  ; => "[1] Hello Gaius, my name is Julius!"
  goblins[1]> ($ julius 'greet "Brutus")
  ; => "[2] Hello Brutus, my name is Julius!"
  goblins[1]> ($ julius 'get-times-called)
  ; => 2
#+END_SRC

** Asynchronous message passing

We have shown that the behavior of objects may be invoked
synchronously with =$=.
However, this only works if two objects are both defined on the same
machine on the network and the same event loop within that machine.

Now, recall our friend =alice= who we defined on vat A.
The following works just fine if we're still executing within
=a-vat='s subrepl context:

#+BEGIN_SRC scheme
 goblins[1]> ($ alice "Alfred")
 => "Hello Alfred, my name is Alice!"
#+END_SRC

But let's exit the =a-vat= subrepl and make =b-vat= and enter that:

#+BEGIN_SRC scheme
  goblins[1]> ,q
  scheme> (define b-vat
            (spawn-vat))
  scheme> ,enter-vat b-vat
  goblins[1]>
#+END_SRC

But since Alice works on A, we cannot synchronously invoke her with
=$= on vat B:

#+BEGIN_SRC scheme
  goblins[1]> ($ alice "Bob")
  ;; === Caught error: ===
  ;;  message: #<<message> to: #<local-object> resolve-me: #f args: ()>
  ;;  exception: ... "Not in the same vat:" #<local-object ^greeter>) ...
#+END_SRC

This is where =<-= comes in.
In contrast to =$=, =<-= can be used against objects which live
anywhere, even on remote machines.
However, unlike invocation with =$=, we do not get back an
immediate result, we get a promise:

#+BEGIN_SRC scheme
  goblins[1]> (<- alice "Bob")
  ; => #<promise>
#+END_SRC

This promise must be listened to.
The procedure to listen to promises in Goblins is called
=on=:

#+BEGIN_SRC scheme
  goblins[1]> (on (<- alice "Bob")
                  (lambda (got-back)
                    (format #t "Heard back: ~a\n"
                            got-back)))
  ; Prints out, at some point in the future:
  ;   "Heard back: [3] Hello Bob, my name is Alice!"
#+END_SRC

Not all communication goes as planned, especially in a distributed
system.
Consider an object which breaks in the middle of execution, such as
an instance of =^broken= here:

#+BEGIN_SRC scheme
  (define (^broken _bcom)
    (lambda ()
      (error "Yikes, I broke!")))
#+END_SRC

=on= also supports the keyword arguments of =#:catch= and =#:finally=,
which both accept a procedure defining handling errors in the former case
and code which will run regardless of successful resolution or failure
in the latter case:

#+BEGIN_SRC scheme
  goblins[1]> (define broken-ben
                (spawn ^broken-ben))
  goblins[1]> (on (<- broken-ben)
                  (lambda (what-did-ben-say)
                    (format #t "Ben says: ~a\n" what-did-ben-say))
                  #:catch
                  (lambda (err)
                    (format #t "Got an error: ~a\n" err))
                  #:finally
                  (lambda ()
                    (display "Whew, it's over!\n")))
#+END_SRC

** Transactions make errors survivable

Mistakes happen, and when they do, we'd like damage to be minimal.
But with many moving parts, accomplishing this can be difficult.

However, Goblins makes our life easier.
To see how, let's intentionally insert a couple of print debugging
lines (with =pk=, which is pronounced and means "peek")
and then an error:

#+BEGIN_SRC scheme
  (define (^borked-cgreeter _bcom our-name)
    (define times-called
      (spawn ^mcell 0))
    (methods
      ((get-times-called)
       ($ times-called 'get))
      ((greet your-name)
       (pk 'before-incr ($ times-called 'get))
       ;; increase the number of times called
       ($ times-called 'set
          (+ 1 ($ times-called 'get)))
       (pk 'after-incr ($ times-called 'get))
       (error "Yikes")
       (format #f "[~a] Hello ~a, my name is ~a!"
               ($ times-called 'get)
               your-name our-name))))
#+END_SRC

Now let's spawn this friend and invoke it:

#+BEGIN_SRC scheme
  goblins[1]> (define horatio
                (spawn ^borked-cgreeter "Horatio"))
  goblins[1]> ($ horatio 'get-times-called)
  ; => 0
  goblins[1]> ($ horatio 'greet "Hamlet")
  ; pk debug: (before-incr 0)
  ; pk debug: (after-incr 1)
  ; ice-9/boot-9.scm:1685:16: In procedure raise-exception:
  ;   Yikes
  ; Entering a new prompt.  Type `,bt' for a backtrace or `,q' to continue.
#+END_SRC

Whoops!  Looks like something went wrong!
We can see from the =pk= debugging that the =times-called= cell should
be incremented to 1.
And yet...

#+BEGIN_SRC scheme
  goblins[1]> ($ horatio 'get-times-called)
  ; => 0
#+END_SRC

We will cover this in greater detail later, but the core idea here
is that synchronous operations run with =$= are all done together
as one transaction.
If an unhandled error occurs, any state changes resulting from
synchronous operations within that transaction will simply not
be committed.
This is useful, because it means most otherwise difficult cleanup
steps are handled automatically.

** Promise pipelining

#+BEGIN_QUOTE
  "Machines grow faster and memories grow larger.
  But the speed of light is constant and New York is not getting any
  closer to Tokyo."

   --- Mark S. Miller,
       [[http://www.erights.org/talks/thesis/][Robust Composition: Towards a Unified Approach to Access Control and Concurrency Control]]
#+END_QUOTE

Promise pipelining provides two different features at once:

 - A convenient developer interface for describing a series of
   asynchronous actions, allowing for invoking the objects which
   promises will point to before they are even resolved (sometimes
   before the objects even exist!)
 - A network abstraction that eliminates many round trips

Consider the following car factory, which makes cars carrying
the company name of the factory:

#+BEGIN_SRC scheme
  ;; Create a "car factory", which makes cars branded with
  ;; company-name.
  (define (^car-factory bcom company-name)
    ;; The constructor for cars we will create.
    (define (^car bcom model color)
      (methods                      ; methods for the ^car
       ((drive)                    ; drive the car
        (format #f "*Vroom vroom!*  You drive your ~a ~a ~a!"
                color company-name model))))
    ;; methods for the ^car-factory instance
    (methods                        ; methods for the ^car-factory
     ((make-car model color)       ; create a car
      (spawn ^car model color))))
#+END_SRC

Here is an instance of this car factory, which we will call
=fork-motors=, which we will spawn on =a-vat=:

#+BEGIN_SRC scheme
  scheme> ,enter a-vat
  goblins[1]> (define fork-motors
                (spawn ^car-factory "Fork"))
#+END_SRC

Since asynchronous message passing with =<-= works across machines,
it does not matter whether interacitons with =fork-motors= are local
or via objects communicating over the network.
We will treat =fork-motors= as living on machine A, and so the
following interactions will happen with invocations originating from
machine B.

Let's send a message to =fork-motors= invoking the ='make-car= method,
receiving back a promise for the car which will be made, which we
shall name =car-vow= (=-vow= being the conventional suffix given
for promises in Goblins):

#+BEGIN_SRC scheme
  goblins[1]> ,q
  scheme> ,enter-vat b-vat
  ;; Interaction on machine B, communicating with fork-motors on A
  goblins[1]> (define car-vow
                (<- fork-motors 'make-car "Explorist" "blue"))
#+END_SRC

So we have a /promise/ to a future car reference, but not the
reference itself.
We would like to drive the car as soon as it rolls off the lot of the
factory, which of course involves sending a message to the car.

Without promise pipelining, making use of the tools we have already
shown (and following the pattern most other distributed programming
systems use), we would end up with something like:

#+BEGIN_SRC scheme
  ;; Interaction on machine B, communicating with A
  goblins[1]> (on car-vow                    ; B->A: first resolve the car-vow
                  (lambda (our-car)          ; A->B: car-vow resolved as our-car
                    (on (<- our-car 'drive)  ; B->A: now we can message our-car
                        (lambda (val)        ; A->B: result of that message
                          (format #f "Heard: ~a\n" val)))))
#+END_SRC

With promise pipelining, we can simply message the promise of the car
directly.
The first benefit can be observed from code compactness, in that
we do not need to do an =on= of =car-vow= to later message =our-car=,
we can simply message =car-vow= directly:

#+BEGIN_SRC scheme
  ;; Interaction on machine B, communicating with A
  goblins[1]> (on (<- car-vow 'drive)       ; B->A: send message to future car
                  (lambda (val)             ; A->B: result of that message
                    (format #t "Heard: ~a\n" val)))
#+END_SRC

While clearly a considerable programming convenience, the other
advantage of promise pipelining is a reduction of round-trips, whether
between our event-loop /vats/ or across machines on the network.

This can be understood by looking at the comments to the right of the
two above code interactions.  The message flow in the first case looks
like:

: B => A => B => A => B

The message flow in the second case looks like:

: B => A => B

In other words, machine B can say to machine A: "Make me a car,
and as soon as that car is ready, I want to drive it!"

With this in mind, the promise behind Mark Miller's quote at the
beginning of this section is clear.[fn:thanks-to-e]
If two objects are on opposite ends of the planet, round trips
are unavoidably expensive.
Promise pipelining both allows us to make plans as programmers
and allows for Goblins to optimize carrying out those steps as
bulk operations over the network.

[fn:thanks-to-e] Like so many examples in this document, the designs
of promise pipelining and the explanation of its value come from the E
programming language, the many contributors to its design, and Mark
S. Miller's extraordinary work documenting that work and its history.
If you find this section interesting, both the the [[http://www.erights.org/elib/distrib/pipeline.html][Promise Pipelining]]
page from [[http://erights.org][erights.org]] and sections 2.5 and 16.2 of
[[http://www.erights.org/talks/thesis/markm-thesis.pdf][Mark Miller's dissertation]].

** OCapN, my CapN!

TODO

* API

Here lies the core procedures for building and manipulating Goblins
programs!

Unless where stated, most code from this section can be found by
importing:

#+BEGIN_SRC scheme
  (use-modules (goblins))
#+END_SRC

** Objects

Objects are the core of Goblins.
In general, you'll need to be within an ambient "Goblins Context" (TM)
in order to start programming against them, see [[*Vats][Vats]] for most event
loop type programming, or [[*Actormaps][Actormaps]] if you want to play with more low-level
control over transactional operations.
(However, most users will just use vats.)

*** Spawning objects

Objects can be spawned with the =spawn= operator:

#+BEGIN_SRC scheme
  (spawn CONSTRUCTOR ARGS ...)
  ;=> <local-refr>
#+END_SRC

where =CONSTRUCTOR= is a procedure which itself returns a procedure
representing an object's current behavior.
The =CONSTRUCTOR= is implicitly passed a first argument, traditionally
labeled =bcom=, which can be used to change an object's behavior.
The =ARGS= are passed as the remaining arguments to the constructor.

So for example, let's say we have the following constructor:

#+BEGIN_SRC scheme
  (define* (^cell bcom #:optional val)  ; constructor (outer procedure)
    (case-lambda                        ; behavior    (inner procedure)
      (()                               ; 0-argument invocation (getter)
       val)                             ;   (return current value)
      ((new-val)                        ; 1-argument invocation (setter)
       (bcom (^cell bcom new-val)))))   ;   ("become" ^cell with new value)
#+END_SRC

And so...

#+BEGIN_SRC scheme
  (define some-cell (spawn ^cell 42))
#+END_SRC

will bind =val= to =42=.

Let's look at the =bcom= argument in depth.
This is a capability which allows the actor to change its own behavior.
It must be called in a tail position, since =bcom= actually returns
a datastructure demonstrating that this object is choosing to change
its value (part of Goblins' quasi-functional design.)

=bcom= also can take a second argument, which will be returned from
the object's invocation as a return value, allowing for both an object
change its own behavior and return a value at the same time during an
invocation.

The following actor represents a consumable object that returns a
string explaining its current status:

#+BEGIN_SRC scheme
  (define (^drink bcom drink-name portions)
    (define (drinkable-beh portions)   ; "-beh" is a common suffix for "-behavior"
      (lambda ()
        (define portions-left
          (- portions 1))
        (if (zero? portions-left)
            (bcom empty-beh
                  (format #f "*GLUG!* You drink your ~a. It's empty!"
                          drink-name))
            (bcom (drinkable-beh portions-left)
                  (format #f "*GLUG!* You drink your ~a. Still some left!"
                          drink-name)))))
    (define (empty-beh)
      "Sadly, your glass appears to be empty!")
    (drinkable-beh portions))
#+END_SRC

Now, playing around at the REPL, we can see how this works:

#+BEGIN_SRC scheme
  > ,vr (define root-beer (spawn ^drink "root beer" 3))
  > ,vr ($ root-beer)
  => "*GLUG!* You drink your root beer. Still some left!"
  > ,vr ($ root-beer)
  => "*GLUG!* You drink your root beer. Still some left!"
  > ,vr ($ root-beer)
  => "*GLUG!* You drink your root beer. It's empty!"
  > ,vr ($ root-beer)
  => "Sadly, your glass appears to be empty!"
#+END_SRC

As you can see above, =bcom= is also a handy way to construct state
machines, as =^drink= moves from drinkable to empty as it is consumed.

*** Synchronous invocation

To synchronously invoke two objects within the same vat / actormap,
use =$=:

#+BEGIN_SRC scheme
  ($ near-object args ...)
  ;=> something
#+END_SRC

Provide a synchronous call against the current message handler of
=NEAR-REFR=, which must be a /near/ =live-refr?=
in the same vat as the currently running actor context.
The value returned is that which is returned by the
current behavior of =NEAR-REFR= upon invocation (or, if
=NEAR-REFR= chose to =bcom= something else, the second
argument passed to its =bcom=, or is =unspecified?= if not provided.)

*** Asynchronous invocation

#+BEGIN_SRC scheme
  (<- near-object arg ...)
  ;=> <local-promise>
#+END_SRC

Like =$=, but called asynchronously and returns a /promise/,
which may be handled with =on=.
Unlike =$=, =<-= is not limited to only /near/ objects;
interaction with /far/ actors are permitted as well.

#+BEGIN_SRC scheme
  (<-np [actor-refr live-refr?] [arg any/c] ...)
#+END_SRC

Like =<-= but does not return (or require the overhead of) a
promise.
=<-np= is effectively an optimization; where promises are not
needed, using =<-np= over =<-= is a good idea.

#+BEGIN_SRC scheme
(on vow
    [fulfilled-handler]
    [#:catch broken-handler]
    [#:finally finally-handler]
    [#:promise? #f])
#+END_SRC

Sets up promise handlers for =vow=, which is typically a
=live-refr?= to a /promise/ but may be anything.

=fulfilled-handler=, =broken-handler=, and =finally-handler=
all, if specified, may be either a procedure (the most common case)
which is run when =vow= becomes resolved, or a reference to an
actor that should be messaged when the promise is resolved with the
same arguments that would be passed to an equivalent procedure.
As their names suggest, =fulfilled-handler= will run if a promise is
fulfilled and takes one argument, the fulfilled value.
=broken-handler= will run if a promise is broken and takes one
argument, the error value.
=finally-handler= will run when a promise is resolved, no matter the
outcome and is called with no arguments.

If =#:promise?= is set to =#t=, then =on=
will itself return a promise.
The promise will be resolved as follows:

 - If =vow= is fulfilled and =fulfilled-handler= is not
   provided, the promise returned will share =vow='s resolution.
 - If =vow= is broken and =broken-handler= is not
   provided, the promise returned will share =vow='s broken result.
 - If =vow= is fulfilled and =fulfilled-handler= is provided,
   the resolution will be whatever is returned from =fulfilled-handler=,
   unless =fulfilled-handler= raises an error, in which case the promise
   will be broken with its error-value set to this exception.
 - If =vow= is broken and =broken-handler= is provided,
   the resolution will be whatever is returned from =broken-handler=,
   unless =broken-handler= raises an error, in which case the promise
   will be broken with its error-value set to this exception (which
   may even be the original exception).

** Vats

In order to start programming with Goblins, you will need to boot up a
vat somewhere.

In general, Goblins uses [[https://github.com/wingo/fibers/][Fibers]] to implement vats.  However, it is
intended that users should be able to roll their own vats should they
have "unusual" event loop needs.  More on how to do this in a future
iteration of these docs.  ;)

*** Starting and stopping vats

#+BEGIN_SRC scheme
  > (define my-vat (spawn-vat))
  > my-vat
  => #<procedure (vat-controller)>
#+END_SRC

Running =spawn-vat= returns what's called a "vat controller".
Running with no argument runs some code in the vat, blocking until
a response is returned... useful for bootstrapping vats, or
hacking at the REPL:

#+BEGIN_SRC scheme
  > (define my-vat (spawn-vat))
  => #<procedure (vat-controller)>
  > (my-vat
      (lambda ()
        (define alice (spawn ^greeter "Alice"))
        ($ alice "Bob")))
  => "Hello Alice, my name is Bob!"
#+END_SRC

You can also send it the ='halt= method to stop the vat,
and ='running?= to check its status:

#+BEGIN_SRC scheme
  > (my-vat 'halt)
  > (my-vat 'running?)
  => #f
#+END_SRC

*NOTE:* In the future, we would like vats to automatically halt when
no more references exist and thus the vat can do no more work.  The
Racket version of vats works this way, it would be good for the Guile
version to do the same.  In the meanwhile, you'll need to use ='halt=
manually.

*** COMMENT Rolling your own vats

** Actormaps

So far we have dealt with vats, but there is a lower level of
abstraction in Goblins which is called an =actormap=.

The key differences are:

 - *vat*: An event loop implementation that runs continuously
    in its own thread.
    Comes pre-built with tooling to handle message passing between
    vats.
    Actually wraps an actormap.
 - *actormap*: The transactional datastructure that vats use.
    But, useful on its own to either build your own event loop
    or as a synchronous one-turn-at-a-time mapping of actor references
    to their current implementations.

The best way to learn is by doing, so let's make an actormap now:

#+BEGIN_SRC scheme
  (define am (make-actormap))
#+END_SRC

Let's add an actor to it.
Since cells are simple, let's add one of those.

#+BEGIN_SRC scheme
  (define lunchbox
    (actormap-spawn! am ^cell))
#+END_SRC

What's in the lunchbox?
We could take a look with =actormap-peek=:

#+BEGIN_SRC scheme
  > (actormap-peek am lunchbox)
  ; => #f
#+END_SRC

An empty lunchbox... we'd like to eat something later, so how about we
pack ourselves a nice sandwich by using =actormap-poke=:

#+BEGIN_SRC scheme
  > (actormap-poke! am lunchbox 'peanut-butter-and-jelly)
  > (actormap-peek am lunchbox)
  ; => 'peanut-butter-and-jelly
#+END_SRC

What if we tried to look inside the lunchbox with =actormap-poke!=
instead of =actormap-peek=?

#+BEGIN_SRC scheme
  > (actormap-poke! am lunchbox 'bbq-tofu)
  > (actormap-poke! am lunchbox)
  ; => 'bbq-tofu
#+END_SRC

Well that worked just fine.
What happens if we do both operations with =actormap-peek=?

#+BEGIN_SRC scheme
  > (actormap-peek am lunchbox 'chickpea-salad)
  > (actormap-peek am lunchbox)
  ; => 'bbq-tofu
#+END_SRC

What the...???
Our lunchbox didn't change!

We said that actormaps were transactional.
We have gotten a hint of this with the above:
=actormap-poke!= returns a value and commits any changes.
=actormap-peek= returns a value and throws any changes away.

Actually, these two functions are just simple conveniences that wrap a
more powerful (but cumbersome to use) tool, =actormap-turn=:

#+BEGIN_SRC scheme
  > (actormap-turn am lunchbox)
  ; => 'bbq-tofu
  ; => #<transactormap>
  ; => '()
  (actormap-turn am lunchbox 'chickpea-salad)
  ; => *unspecified* (not printed)
  ; => #<transactormap>
  ; => '()
#+END_SRC

=actormap-turn= returns three values to its continuation: a
return value (if any... Guile's REPL doesn't print out the unspecified
value, which is what actually got returned in the second invocation),
a "transactormap", and a list representing messages
queued for delivery.

This =#<transactormap>= is interesting... we haven't mentioned this
before, but there are really two kinds of actormaps, "whactormaps"
(weak-hash actormaps) and "transactormaps" (which hold a transaction
which we can choose whether or not to commit).
Actually our =am= is a whactormap:

#+BEGIN_SRC scheme
  > am
  ; => #<transactormap>
#+END_SRC

It's a weak hashtable which stores the current mutable state of all
actors.

But we'd like to see about that transactormap... just running
=actormap-turn= on its own won't update the lunchbox either:

#+BEGIN_SRC scheme
  > (actormap-turn am lunchbox 'chickpea-salad)
  ; => #<transactormap>
  > (actormap-turn am lunchbox)
#+END_SRC

We need to capture the transactormap and commit it.

#+BEGIN_SRC scheme
  > (define-values (_val tr-am _nm)
      (actormap-turn am lunchbox 'chickpea-salad))
  > tr-am
  ; => #<transactormap>
  > (transactormap-merge! tr-am)
#+END_SRC

Now at least our =am= actormap should reflect that we've switched out
our ='bbq-tofu= sandwich for a ='chickpea-salad= one:

#+BEGIN_SRC scheme
  > (actormap-peek am lunchbox)
  ; => 'chickpea-salad
#+END_SRC

Horray!

** OCapN
** Persistence

* actor-lib: A standard library of sorts

** Cells

** Methods

** Joiners

** Sealers

* COMMENT Design and philosophy

** On the design of Goblins' distributed objects


** Why Scheme?  Why Guile?

** History

** The future: hopes, dreams, and hard work

** License choice

** Spritely and user freedom

* Thanks

This manual was primarily written by Christine Lemmer-Webber.

# Additional text by: ...

Many of the ideas are borrowed from [[http://www.erights.org/talks/thesis/markm-thesis.pdf][Mark Miller's dissertation]],
which is an excellent, if nerdy, read.

Jessica Tallon, Jonathan A. Rees, Randy Farmer, and David Thompson
provided review and feedback.

* License

/(C) 2019-2022 Christine Lemmer-Webber, the Spritely Institute, and other contributors.  See =AUTHORS= for details./

/Both Spritely Goblins and this manual are released under the terms of the following license:/

#+INCLUDE: "../COPYING"
