#+TITLE: Spritely Goblins

This is the manual for [[https://spritelyproject.org/#goblins][Spritely Goblins]].  It is released under the
[[https://www.apache.org/licenses/LICENSE-2.0][Apache v2 license]], just like Goblins itself.

* What is Goblins?

[[https://spritelyproject.org/#goblins][Spritely Goblins]] is a distributed object programming environment.
It provides:

 - An asynchronous programming environment,
 - A quasi-functional distributed object[fn:on-actors-and-objects]
   system which is fully transactional (bad things can happen and
   relevant parties can be notified, but modified state will roll
   back, preventing the system from becoming corrupted)

Coming soon to the Guile version (and already semi-present in the
Racket version):

 - A distributed object-capability-based object programming system
 - Peer to peer networking abstraction layers 
 - Time travel debugging
 - Process persistence which preserves the security properties
   of the running system

Its design is inspired by the [[http://www.erights.org/][E programming language]] and by the
observation that [[http://mumble.net/~jar/pubs/secureos/secureos.html][lambda is already the ultimate security mechanism]]
(ie, normal argument-passing in programs, if taken seriously/purely,
is already all the security system we need).

Spritely is a wider project to advance decentralized networking
infrastructure, particularly as it pertains to social networks.
Goblins is the heart of the system, on which other layers are built.
At the time of writing, two key versions of Goblins are supported, the
[[https://docs.racket-lang.org/goblins/index.html][Racket version of Goblins]], and the [[https://www.gnu.org/software/guile/][Guile]] version.
This manual is for the Guile edition of Spritely Goblins.

This manual is also very, very incomplete in this early release.
Please see the [[https://docs.racket-lang.org/goblins/][manual for the Racket version of Goblins]] manual,
most of which applies to the Guile version too.

[fn:on-actors-and-objects] Goblins uses the term "object" and "actor"
somewhat interchangably, even though in some ways these terms have
become vague.  There are, in particular,
[[http://mumble.net/~jar/articles/oo.html][many meanings for the word "object"]]; for us, object really means an
encapsulation of behavior and state.  (In Goblins, state is typically
built out of behavior, not the other way around.)
Goblins also follows the [[https://en.wikipedia.org/wiki/Actor_model#Fundamental_concepts][classic actor]] model mostly, in that
in response to a message, an "actor" can:
(a) send a finite number of messages to other actors;
(b) create a finite number of new actors; or
(c) designate the behavior to be used for the next message it receives.
However, Goblins supports both synchronous call-return invocation of
actors within the same event loop via =$= and asynchronous message
sends via =<-=.  Arguably the true "classic actor" model only supports
the latter.

* Getting started

** Installing Goblins

You'll need to install =guile-goblins=.  Either use [[https://guix.gnu.org/][Guix]] or use your
standard GNU/Linux distro's package for =guile-goblins= (if it exists)
or even better yet run Guix as your standard distro.

See the =HACKING= and =README= files with git checkouts / release
tarballs otherwise to install.

** Setup for hacking on Goblins

You're going to want/need:

 - [[https://www.gnu.org/software/emacs/][GNU Emacs]]
 - [[https://www.nongnu.org/geiser/][Geiser]], for hacking on Guile

Then, at minimum, you'll want to put in your .emacs:

#+BEGIN_SRC emacs-lisp
(show-paren-mode 1)  ; Match parentheses
#+END_SRC

However you probably also want some combination of:

 - [[https://github.com/Fuco1/smartparens][smartparens]] (or [[https://www.emacswiki.org/emacs/ParEdit][paredit]], which is much more strict... use
   smartparens if uncertain)
 - [[https://github.com/Fanael/rainbow-delimiters][rainbow-delimeters]]
 - [[https://www.emacswiki.org/emacs/HighlightParentheses][highlight-parentheses]]

Now you'll have a nice hacking setup!  Be sure to read the Geiser
manual.

** TEMPORARY: Live hacking "fix"

The traditional way to hack Guile is to use Geiser, both evaluating
from some =foo.scm= file/buffer with more "permanent" code via, for
example, the =C-x C-e= / =C-x C-b= / =C-x C-k= commands to evaluate an
expression, evaluate a whole buffer, or compile a buffer's content,
and switching back and forth between that and the (usually called
=*Geiser Guile REPL*=) experimental-hacking-and-debugging REPL.

This works with Goblins, but Geiser does some things to temporarily
redirect output/error ports when doing the file/buffer oriented
evaluation, and unfortunately this results in Goblins vats potentially
breaking due to spawning a separate thread which inherit these
temporarily redirected ports, which then are closed when the
evaluation succeeds.  We have a long-term plan to deal with this, but
in the meanwhile, whenever you start a Guile / Geiser hacking session,
first execute:

#+BEGIN_SRC scheme
  > (use-modules (goblins))
#+END_SRC

... from the =*Geiser Guile REPL*=.  Otherwise vats may mysteriously
"hang".  We know this is an annoyance!  It'll be fixed soon!


* Tutorial

TODO: we should port the [[https://docs.racket-lang.org/goblins/index.html][Goblins on Racket tutorial]] but simplify it
(introduce actormaps much later, use =(goblins vrun)= to simplify
REPL experimentation, etc).

** A simple greeter

First, let's import Goblins:

#+BEGIN_SRC scheme
  > (use-modules (goblins))
#+END_SRC

(*NOTE*: See [[*TEMPORARY: Live hacking "fix"][TEMPORARY: Live hacking "fix"]] if you haven't.)

Every Goblins actor / object has to live in a vat somewhere.
So, let's make a vat to play around with:

#+BEGIN_SRC scheme
  > (define a-vat
      (spawn-vat))
  ;; This will make interacting with the vat a bit easier
  > (define-vat-run a-run a-vat)
#+END_SRC

Objects/actors are instantiated with =spawn= and can be synchronously
invoked with =$= or asynchronously invoked with =<-=.
All of these operations need to operate within a Goblins-aware context,
and so =a-run= "bootstraps" some code within the vat.

Now let us implement a friend who will greet us:

#+BEGIN_SRC scheme
(define (^greeter bcom our-name)   ; constructor (outer procedure)
  (lambda (your-name)              ; behavior    (inner procedure)
    (format #f "Hello ~a, my name is ~a!"
            your-name our-name)))
#+END_SRC

Let's give it a try by instantiating an instance of =^greeter= using
=spawn= and assign her to the variable =alice=:

#+BEGIN_SRC scheme
 > (define alice
     (a-run (spawn ^greeter "Alice")))
#+END_SRC

The first argument to =spawn= is the constructor we will use to make
our Goblins object, in this case =^greeter=.
The remaining arguments will be passed to the constructor,
along with an implicit argument which can be used to change object
behavior called =bcom= (pronounced "become").
Thus ="Alice"= maps to =our-name=.

We can invoke =alice= by using =$= for a synchronous call-return
operation:

#+BEGIN_SRC scheme
 > (a-run ($ alice "Alfred"))
 ; => "Hello Alfred, my name is Alice!"
#+END_SRC

The first argument to =$= is the object to be invoked, the remaining
arguments are passed to the "behavior" of the object.
Thus =your-name= in =^greeter='s behavior procedure is bound to
="Bob"=.
The behavior procedure thus proceeds with formatting and returning the
greeting string.

** State as updating behavior

Let's introduce a simple cell which stores a value.
This cell will have two methods:
='get= retrieves the current value, and ='set= replaces
the current value with a new value.

#+BEGIN_SRC scheme
(define* (^cell bcom #:optional [val #f])
  (case-lambda
    (()         ; get
     val)
    ((new-val)  ; set
     (bcom (^cell bcom new-val)))))
#+END_SRC

=case-lambda= allows for dispatching depending on the number of
arguments, so here we're choosing that if no arguments are provided,
our cell shares the current value, and if one argument is provided,
the cell updates itself to become a cell storing the new value.

Let's try it.
Cells hold values, and so do treasure chests, so let's make
a treasure chest flavored cell.
Taking things out and putting them back in is easy:

#+BEGIN_SRC scheme
  > (define chest
      (a-run (spawn ^cell "sword")))
  > (a-run ($ chest))
  ; => "sword"
  > (a-run ($ chest "gold"))
  > (a-run ($ chest))
  ; => "gold" 
#+END_SRC

Now we can see what =bcom= is: a capability specific to this object
instance which allows it to change its behavior!
(For this reason, =bcom= is pronounced "become"!)

** Methods aren't essential, but they are useful

The most common way to select different sub-behaviors isn't by the
number of arguments though.
It's much more common to have "methods" that are selected by name.
We can use the =methods= macro to do just that:

#+BEGIN_SRC scheme
(use-modules (goblins actor-lib methods))

(define* (^mcell bcom #:optional [val #f])
  (methods
   ((get)
    val)
   ((set new-val)
    (bcom (^mcell bcom new-val)))))
#+END_SRC

The use of =^mcell= is similar, but now we pass in a first argument
as a symbol selecting the method, and the rest of the arguments are
passed to the object:

#+BEGIN_SRC scheme
  > (define jar
      (a-run (spawn ^mcell "cookies")))
  > (a-run ($ jar 'get))
  ; => "cookies"
  > (a-run ($ jar 'set "crumbs"))  
  > (a-run ($ jar 'get))
  ; => "crumbs"
#+END_SRC

Methods aren't particularly magical... the =methods= macro just
returns a procedure which is convenient to use for procedure dispatch:

#+BEGIN_SRC scheme
  > (define foo-or-bar
      (methods
       ((foo)
        'called-foo)
       ((bar arg)
        (list 'called-bar-with arg))))
  > (foo-or-bar 'foo)
  ; => called-foo
  > (foo-or-bar 'bar "meep")
  ; => (called-bar-with "meep")
#+END_SRC

So really, =methods= just makes a particularly useful kind of
behavior procedure for us, one which takes a first argument for
the method name, grabs the rest of the arguments, and then applies
them to the relevant method.

** Objects which contain objects

Objects can also contain and define other object references, including
in their outer constructor procedure.

Here is the definition of a "counting greeter" we call =^cgreeter=:

#+BEGIN_SRC scheme
(define (^cgreeter _bcom our-name)
  (define times-called
    (spawn ^mcell 0))
  (methods
   ((get-times-called)
    ($ times-called 'get))
   ((greet your-name)
    ;; increase the number of times called
    ($ times-called 'set
       (+ 1 ($ times-called 'get)))
    (format #f "[~a] Hello ~a, my name is ~a!"
            ($ times-called 'get)
            your-name our-name))))
#+END_SRC

As we can see near the top, =times-called= is instantiated as an
=^cell= like the one we defined earlier.
The current value of this cell is returned by =get-times-called=
and is updated every time the =greet= method is called:

#+BEGIN_SRC scheme
  > (define julius
      (a-run (spawn ^cgreeter "Julius")))
  > (a-run ($ julius 'get-times-called))
  ; => 0
  > (a-run ($ julius 'greet "Gaius"))
  ; => "[1] Hello Gaius, my name is Julius!"
  > (a-run ($ julius 'greet "Brutus"))
  ; => "[2] Hello Brutus, my name is Julius!"
  > (a-run ($ julius 'get-times-called))
  ; => 2
#+END_SRC

** Asynchronous message passing

We have shown that the behavior of objects may be invoked
synchronously with =$=.
However, this only works if two objects are both defined on the same
machine on the network and the same event loop within that machine.

To demonstrate this, let's create a new vat, =b-vat= (as well as a
=b-run= to make REPL examples a bit easier to demonstrate):

#+BEGIN_SRC scheme
  > (define b-vat
      (spawn-vat))
  > (define-vat-run b-run b-vat)
#+END_SRC

Now, recall our friend =alice= who we defined on vat A.
The following works just fine:

#+BEGIN_SRC scheme
 > (a-run ($ alice "Alfred"))
 ; => "Hello Alfred, my name is Alice!"
#+END_SRC

But since Alice works on A, we cannot synchronously invoke her with
=$= on vat B:

#+BEGIN_SRC scheme
> (b-run ($ alice "Bob"))
;; === Caught error: ===
;;  message: #<<message> to: #<local-object> resolve-me: #f args: ()>
;;  exception: ... "Not in the same vat: ~a" #<local-object ^greeter>) ...
#+END_SRC

This is where =<-= comes in.
In contrast to =$=, =<-= can be used against objects which live
anywhere, even on remote machines.
However, unlike invocation with =$=, we do not get back an
immediate result, we get a promise:

#+BEGIN_SRC scheme
> (b-run (<- alice "Bob"))
; => #<promise>
#+END_SRC

This promise must be listened to.
The procedure to listen to promises in Goblins is called
=on=:

#+BEGIN_SRC scheme
  > (b-run
     (on (<- alice "Bob")
       (lambda (got-back)
         (format #t "Heard back: ~a\n"
                 got-back))))
  ; Prints out, at some point in the future:
  ;   "Heard back: [3] Hello Bob, my name is Alice!"
#+END_SRC

Not all communication goes as planned, especially in a distributed
system.
=on= also supports the keyword arguments of =#:catch= and =#:finally=,
which both accept a procedure defining handling errors in the former case
and code which will run regardless of successful resolution or failure
in the latter case:

#+BEGIN_SRC scheme
  > (define (^broken-ben _bcom)
      (lambda ()
        (error "Yikes, I broke!")))
  > (define broken-ben
      (b-run (spawn ^broken-ben)))
  > (a-run
     (on (<- broken-ben)
         (lambda (what-did-ben-say)
           (format #t "Ben says: ~a\n" what-did-ben-say))
         #:catch
         (lambda (err)
           (format #t "Got an error: ~a\n" err))
         #:finally
         (lambda ()
           (display "Whew, it's over!\n")))
#+END_SRC

** Transactions make errors survivable

Mistakes happen, and when they do, we'd like damage to be minimal.
But with many moving parts, accomplishing this can be difficult.

However, Goblins makes our life easier.
To see how, let's intentionally insert a couple of print debugging
lines (with =pk=, which is pronounced and means "peek")
and then an error:

#+BEGIN_SRC scheme
  (define (^borked-cgreeter _bcom our-name)
    (define times-called
      (spawn ^cell 0))
    (methods
      ((get-times-called)
       ($ times-called 'get))
      ((greet your-name)
       (pk 'before-incr ($ times-called 'get))
       ;; increase the number of times called
       ($ times-called 'set
          (+ 1 ($ times-called 'get)))
       (pk 'after-incr ($ times-called 'get))
       (error "Yikes")
       (format #f "[~a] Hello ~a, my name is ~a!"
               ($ times-called 'get)
               your-name our-name))))
#+END_SRC

Now let's spawn this friend and invoke it:

#+BEGIN_SRC scheme
  > (define horatio
      (a-run (spawn ^borked-cgreeter "Horatio")))
  > (a-run ($ horatio 'get-times-called))
  ; => 0
  > (a-run ($ horatio 'greet "Hamlet"))
  ; pk debug: (before-incr 0)
  ; pk debug: (after-incr 1)
  ; ice-9/boot-9.scm:1685:16: In procedure raise-exception:
  ;   Yikes
  ; Entering a new prompt.  Type `,bt' for a backtrace or `,q' to continue.
#+END_SRC

Whoops!  Looks like something went wrong!
We can see from the =pk= debugging that the =times-called= cell should
be incremented to 1.
And yet...

#+BEGIN_SRC scheme
> (a-run ($ horatio 'get-times-called))
; => 0
#+END_SRC

We will cover this in greater detail later, but the core idea here
is that synchronous operations run with =$= are all done together
as one transaction.
If an unhandled error occurs, any state changes resulting from
synchronous operations within that transaction will simply not
be committed.
This is useful, because it means most otherwise difficult cleanup
steps are handled automatically.

** Promise pipelining

#+BEGIN_QUOTE
  "Machines grow faster and memories grow larger.
  But the speed of light is constant and New York is not getting any
  closer to Tokyo."

   --- Mark S. Miller,
       [[http://www.erights.org/talks/thesis/][Robust Composition: Towards a Unified Approach to Access Control and Concurrency Control]]
#+END_QUOTE

Promise pipelining provides two different features at once:

 - A convenient developer interface for describing a series of
   asynchronous actions, allowing for invoking the objects which
   promises will point to before they are even resolved (sometimes
   before the objects even exist!)
 - A network abstraction that eliminates many round trips

Consider the following car factory, which makes cars carrying
the company name of the factory:

#+BEGIN_SRC scheme
  ;; Create a "car factory", which makes cars branded with
  ;; company-name.
  (define (^car-factory bcom company-name)
    ;; The constructor for cars we will create.
    (define (^car bcom model color)
      (methods                      ; methods for the ^car
       ((drive)                    ; drive the car
        (format #t "*Vroom vroom!*  You drive your ~a ~a ~a!"
                color company-name model))))
    ;; methods for the ^car-factory instance
    (methods                        ; methods for the ^car-factory
     ((make-car model color)       ; create a car
      (spawn ^car model color))))
#+END_SRC

Here is an instance of this car factory, which we will call
=fork-motors=:

#+BEGIN_SRC scheme
  ;; Interaction on machine A
  > (define fork-motors
      (a-run
       (spawn ^car-factory "Fork")))
#+END_SRC

Since asynchronous message passing with =<-= works across machines,
it does not matter whether interacitons with =fork-motors are local
or via objects communicating over the network.
We will treat =fork-motors= as living on machine A, and so the
following interactions will happen with invocations originating from
machine B.

Let's send a message to =fork-motors= invoking the ='make-car= method,
receiving back a promise for the car which will be made, which we
shall name =car-vow= (=-vow= being the conventional suffix given
for promises in Goblins):

#+BEGIN_SRC scheme
  ;; Interaction on machine B, communicating with fork-motors on A
  > (define car-vow
      (b-run
       (<- fork-motors 'make-car "Explorist" "blue")))
#+END_SRC


So we have a /promise/ to a future car reference, but not the
reference itself.
We would like to drive the car as soon as it rolls off the lot of the
factory, which of course involves sending a message to the car.

Without promise pipelining, making use of the tools we have already
shown (and following the pattern most other distributed programming
systems use), we would end up with something like:

#+BEGIN_SRC scheme
  ;; Interaction on machine B, communicating with A
  > (b-run
     (on car-vow                    ; B->A: first resolve the car-vow
         (lambda (our-car)          ; A->B: car-vow resolved as our-car
           (on (<- our-car 'drive)  ; B->A: now we can message our-car
               (lambda (val)        ; A->B: result of that message
                 (format #f "Heard: ~a\n" val))))))
#+END_SRC

With promise pipelining, we can simply message the promise of the car
directly.
The first benefit can be observed from code compactness, in that
we do not need to do an =on= of =car-vow= to later message =our-car=,
we can simply message =car-vow= directly:

#+BEGIN_SRC scheme
  ;; Interaction on machine B, communicating with A
  > (b-run
     (on (<- car-vow 'drive)     ; B->A: send message to future car
         (lambda (val)             ; A->B: result of that message
           (format #f "Heard: ~a\n" val))))
#+END_SRC

While clearly a considerable programming convenience, the other
advantage of promise pipelining is a reduction of round-trips, whether
between our event-loop /vats/ or across machines on the network.

This can be understood by looking at the comments to the right of the
two above code interactions.  The message flow in the first case looks
like:

: B => A => B => A => B

The message flow in the second case looks like:

: B => A => B

In other words, machine B can say to machine A: "Make me a car,
and as soon as that car is ready, I want to drive it!"

With this in mind, the promise behind Mark Miller's quote at the
beginning of this section is clear.[fn:thanks-to-e]
If two objects are on opposite ends of the planet, round trips
are unavoidably expensive.
Promise pipelining both allows us to make plans as programmers
and allows for Goblins to optimize carrying out those steps as
bulk operations over the network.

[fn:thanks-to-e] Like so many examples in this document, the designs
of promise pipelining and the explanation of its value come from the E
programming language, the many contributors to its design, and Mark
S. Miller's extraordinary work documenting that work and its history.
If you find this section interesting, both the the [[http://www.erights.org/elib/distrib/pipeline.html][Promise Pipelining]]
page from [[http://erights.org][erights.org]] and sections 2.5 and 16.2 of
[[http://www.erights.org/talks/thesis/markm-thesis.pdf][Mark Miller's dissertation]].

** OCapN, my CapN!

TODO

* API

TODO

** Objects and behavior

TODO

*** Spawning objects

# TODO

*** Synchronous calls

# TODO

*** Asynchronous message passing

# TODO

# ** Vats: Communicating event loops
# ** Actormaps: Low level transactional heaps
# ** CapTP: Distributed programming
# ** Aurie: Persistence
# ** actor-lib: A standard library of sorts

# * Debugging

# More on debugging coming soon.

# * Design and philosophy

# ** Why Scheme?  Why Guile?

# ** History

# ** The future: hopes, dreams, and hard work

# ** License choice

# ** Spritely and user freedom
