#+TITLE: Spritely Goblins

This is the manual for [[https://spritelyproject.org/#goblins][Spritely Goblins]].  It is released under the
[[https://www.apache.org/licenses/LICENSE-2.0][Apache v2 license]], just like Goblins itself.

* What is Goblins?

[[https://spritelyproject.org/#goblins][Spritely Goblins]] is a distributed object programming environment.
It provides:

 - An asynchronous programming environment,
 - A quasi-functional distributed object[fn:on-actors-and-objects]
   system which is fully transactional (bad things can happen and
   relevant parties can be notified, but modified state will roll
   back, preventing the system from becoming corrupted)

Coming soon to the Guile version (and already semi-present in the
Racket version):

 - A distributed object-capability-based object programming system
 - Peer to peer networking abstraction layers 
 - Time travel debugging
 - Process persistence which preserves the security properties
   of the running system

Its design is inspired by the [[http://www.erights.org/][E programming language]] and by the
observation that [[http://mumble.net/~jar/pubs/secureos/secureos.html][lambda is already the ultimate security mechanism]]
(ie, normal argument-passing in programs, if taken seriously/purely,
is already all the security system we need).

Spritely is a wider project to advance decentralized networking
infrastructure, particularly as it pertains to social networks.
Goblins is the heart of the system, on which other layers are built.
At the time of writing, two key versions of Goblins are supported, the
[[https://docs.racket-lang.org/goblins/index.html][Racket version of Goblins]], and the [[https://www.gnu.org/software/guile/][Guile]] version.
This manual is for the Guile edition of Spritely Goblins.

This manual is also very, very incomplete in this early release.
Please see the [[https://docs.racket-lang.org/goblins/][manual for the Racket version of Goblins]] manual,
most of which applies to the Guile version too.

[fn:on-actors-and-objects] Goblins uses the term "object" and "actor"
somewhat interchangably, even though in some ways these terms have
become vague.  There are, in particular,
[[http://mumble.net/~jar/articles/oo.html][many meanings for the word "object"]]; for us, object really means an
encapsulation of behavior and state.  (In Goblins, state is typically
built out of behavior, not the other way around.)
Goblins also follows the [[https://en.wikipedia.org/wiki/Actor_model#Fundamental_concepts][classic actor]] model mostly, in that
in response to a message, an "actor" can:
(a) send a finite number of messages to other actors;
(b) create a finite number of new actors; or
(c) designate the behavior to be used for the next message it receives.
However, Goblins supports both synchronous call-return invocation of
actors within the same event loop via =$= and asynchronous message
sends via =<-=.  Arguably the true "classic actor" model only supports
the latter.

* Getting started

** Installing Goblins

You'll need to install =guile-goblins=.  Either use [[https://guix.gnu.org/][Guix]] or use your
standard GNU/Linux distro's package for =guile-goblins= (if it exists)
or even better yet run Guix as your standard distro.

See the =HACKING= and =README= files with git checkouts / release
tarballs otherwise to install.

** Setup for hacking on Goblins

You're going to want/need:

 - [[https://www.gnu.org/software/emacs/][GNU Emacs]]
 - [[https://www.nongnu.org/geiser/][Geiser]], for hacking on Guile

Then, at minimum, you'll want to put in your .emacs:

#+BEGIN_SRC emacs-lisp
(show-paren-mode 1)  ; Match parentheses
#+END_SRC

However you probably also want some combination of:

 - [[https://github.com/Fuco1/smartparens][smartparens]] (or [[https://www.emacswiki.org/emacs/ParEdit][paredit]], which is much more strict... use
   smartparens if uncertain)
 - [[https://github.com/Fanael/rainbow-delimiters][rainbow-delimeters]]
 - [[https://www.emacswiki.org/emacs/HighlightParentheses][highlight-parentheses]]

Now you'll have a nice hacking setup!  Be sure to read the Geiser
manual.

* Tutorial

TODO: we should port the [[https://docs.racket-lang.org/goblins/index.html][Goblins on Racket tutorial]] but simplify it
(introduce actormaps much later, use =(goblins vrun)= to simplify
REPL experimentation, etc).

** A few goblin'y friends

First, let's import Goblins:

#+BEGIN_SRC scheme
  (use-modules (goblins))
#+END_SRC

Now let us implement a friend who will greet us:

#+BEGIN_SRC scheme
(define (^greeter _bcom our-name)  ; constructor (outer procedure)
  (lambda (your-name)              ; behavior    (inner procedure)
    (format #f "Hello ~a, my name is ~a!"
            your-name our-name)))
#+END_SRC

Objects/actors are instantiated with =spawn= and can be synchronously
invoked with =$= or asynchronously invoked with =<-=.
But in order in order to use all these, we need an event loop which
contains objects for us to =spawn= and which can handle messages sent
to those objects.

Every Goblins actor / object has to live in a vat somewhere.
So, let's make a vat for our new friend:

#+BEGIN_SRC scheme
  > (define-values (a-vat a-ctrl)
      (spawn-vat))
  ;; This will make interacting with the vat a bit easier
  > (define-vat-run a-run a-vat)
#+END_SRC

 - vat dispatcher with methods (like in racket)
 - *just* return the run method equivalent
 - return two values (run method equivalent, halt)

#+BEGIN_SRC scheme
  > (a-run
      (define alice (spawn ^greeter "Alice"))
      ($ alice "Bob"))
#+END_SRC

EXPLAIN

#+BEGIN_SRC scheme
(define* (^cell bcom #:optional [val #f])
  (case-lambda
    (()         ; get
     val)
    ((new-val)  ; set
     (bcom (^cell bcom new-val)))))
#+END_SRC

#+BEGIN_SRC scheme
(use-modules (goblins actor-lib methods))

(define* (^mcell bcom #:optional [val #f])
  (methods
   ((get)
    val)
   ((set new-val)
    (bcom (^mcell bcom new-val)))))
#+END_SRC

Methods aren't particularly magical:

#+BEGIN_SRC scheme
> (methods ...)
#+END_SRC


#+BEGIN_SRC scheme
(define (^cgreeter _bcom our-name)
  (define times-called
    (spawn ^mcell 0))
  (methods
   ((get-times-called)
    ($ times-called 'get))
   ((greet your-name)
    ;; increase the number of times called
    ($ times-called.set
       (+ 1 ($ times-called 'get)))
    (format #f "[~a] Hello ~a, my name is ~a!"
            ($ times-called 'get)
            your-name our-name))))
#+END_SRC

#+BEGIN_SRC scheme
(define (^borked-cgreeter _bcom our-name)
  (define times-called
    (spawn ^mcell 0))
  (methods
   ((get-times-called)
    ($ times-called 'get))
   ((greet your-name)
    (pk 'before-incr ($ times-called 'get))
    ;; increase the number of times called
    ($ times-called 'set
       (+ 1 ($ times-called 'get)))
    (pk 'after-incr ($ times-called 'get))
    (error "Yikes")
    (format #f "[~a] Hello ~a, my name is ~a!"
            ($ times-called 'get)
            your-name our-name))))
#+END_SRC

#+BEGIN_SRC wisp
  ;; unwisp and wrap in b-vat
  REPL> on (<- call-me 'greet)
  _____   lambda (got-back)
  _____     format #t "Heard back: ~a\n"
  _____            . got-back
  ;; Prints out, at some point in the future:
  ;;   "Heard back: [3] Hello Lear, my name is Julius!"
#+END_SRC

[fn:hard-hats] The =^= character is conventionally prefixed on Goblins
constructors and is called a /hard hat/, referring to the kind used by
construction workers.

** OCapN, my CapN!

TODO

** Promise pipelining

TODO

* API

TODO

** Objects and behavior

TODO

*** Spawning objects

# TODO

*** Synchronous calls

# TODO

*** Asynchronous message passing

# TODO

# ** Vats: Communicating event loops
# ** Actormaps: Low level transactional heaps
# ** CapTP: Distributed programming
# ** Aurie: Persistence
# ** actor-lib: A standard library of sorts

# * Debugging

# More on debugging coming soon.

# * Design and philosophy

# ** Why Scheme?  Why Guile?

# ** History

# ** The future: hopes, dreams, and hard work

# ** License choice

# ** Spritely and user freedom
