#+TITLE: Spritely Goblins

This is the manual for [[https://spritelyproject.org/#goblins][Spritely Goblins]].  It is released under the
[[https://www.apache.org/licenses/LICENSE-2.0][Apache v2 license]], just like Goblins itself.

* What is Goblins?

[[https://spritelyproject.org/#goblins][Spritely Goblins]] is a distributed object programming environment.
Features:

 - *Quasi-functional object system:*
   Users hold on to references of objects/actors, but objects/actors
   are just procedures.
   Rather than directly mutating, objects/actors can specify that
   they should "become" a new version of themselves when they
   handle the next invocation.

 - *Fully distributed, networked, secure p2p communication:*
   Via OCapN, the Object Capability Network (which features CapTP, the
   Capability Transport Protocol), you can communicate with other
   objects over a network connection.  Distributed object interactions
   are safe because of ocap security guarantees.

 - *Transactional updates:*
   Changes happen within a transaction.
   If an unhandled exception occurs, we can "roll back" history
   as if the message never happened, avoiding confused state
   changes throughout the system.

 - *Time travel:*
   We can snapshot old revisions of the system and
   interact with them.

 - *Asynchronous programming with sophisticated promise chaining:*
   Asynchronous message passing with promises is supported.
   Promises work such that there's no need to wait for promises
   to resolve before interacting... you can communicate with the
   future that doesn't even yet exist!
   Sent a message to that remote car factory asking for a new car?
   Why wait for the car to be delivered... you can send it a
   drive message at the same time, and both messages can be
   delivered across the network in a single hop.

 - *Communicating event loops:*
   Objects across multiple event loops (aka "vats") can
   communicate, whether in the same OS process or (soon) across
   the network.

 - *Synchronous and asynchronous behavior, integrated but distinguished:*
   Both synchronous and asynchronous programming is supported,
   but only objects in the same "vat" (event loop) can perform
   synchronous immediate calls.
   All objects can perform asynchronous calls against each other.

 - *A library, not a language:*
   Goblins is itself a library that can be utilized across a wide
   variety of Guile programs.

 - *Object capability security:*
   Goblins itself is built for object capability (ocap) security,
   which is to say that you can only operate on the references
   you have access to.
   Goblins embraces and builds upon this foundation.
   (However, full ocap security will require utilizing the
   sandboxing features of Guile; demonstrations of this coming soon.)


Goblins' design is inspired by the [[http://www.erights.org/][E programming language]] and by the
observation that [[http://mumble.net/~jar/pubs/secureos/secureos.html][lambda is already the ultimate security mechanism]]
(ie, normal argument-passing in programs, if taken seriously/purely,
is already all the security system we need).

Spritely is a wider project to advance decentralized networking
infrastructure, particularly as it pertains to social networks.
Goblins is the heart of the system, on which other layers are built.
At the time of writing, two key versions of Goblins are supported, the
[[https://docs.racket-lang.org/goblins/index.html][Racket version of Goblins]], and the [[https://www.gnu.org/software/guile/][Guile]] version.
This manual is for the Guile edition of Spritely Goblins.

This manual is also very, very incomplete in this early release.
Please see the [[https://docs.racket-lang.org/goblins/][manual for the Racket version of Goblins]] manual,
most of which applies to the Guile version too.

[fn:on-actors-and-objects] Goblins uses the term "object" and "actor"
somewhat interchangably, even though in some ways these terms have
become vague.  There are, in particular,
[[http://mumble.net/~jar/articles/oo.html][many meanings for the word "object"]]; for us, object really means an
encapsulation of behavior and state.  (In Goblins, state is typically
built out of behavior, not the other way around.)
Goblins also follows the [[https://en.wikipedia.org/wiki/Actor_model#Fundamental_concepts][classic actor]] model mostly, in that
in response to a message, an "actor" can:
(a) send a finite number of messages to other actors;
(b) create a finite number of new actors; or
(c) designate the behavior to be used for the next message it receives.
However, Goblins supports both synchronous call-return invocation of
actors within the same event loop via =$= and asynchronous message
sends via =<-=.  Arguably the true "classic actor" model only supports
the latter.

* Getting started

** Installing Goblins

You'll need to install =guile-goblins=.  Either use [[https://guix.gnu.org/][Guix]] or use your
standard GNU/Linux distro's package for =guile-goblins= (if it exists)
or even better yet run Guix as your standard distro.

See the =HACKING= and =README= files with git checkouts / release
tarballs otherwise to install.

** Setup for hacking on Goblins

You're going to want/need:

 - [[https://www.gnu.org/software/emacs/][GNU Emacs]]
 - [[https://www.nongnu.org/geiser/][Geiser]], for hacking on Guile

Then, at minimum, you'll want to put in your .emacs:

#+BEGIN_SRC emacs-lisp
(show-paren-mode 1)  ; Match parentheses
#+END_SRC

However you probably also want some combination of:

 - [[https://github.com/Fuco1/smartparens][smartparens]] (or [[https://www.emacswiki.org/emacs/ParEdit][paredit]], which is much more strict... use
   smartparens if uncertain)
 - [[https://github.com/Fanael/rainbow-delimiters][rainbow-delimeters]]
 - [[https://www.emacswiki.org/emacs/HighlightParentheses][highlight-parentheses]]

Now you'll have a nice hacking setup!  Be sure to read the Geiser
manual.

** TEMPORARY: Live hacking "fix"

The traditional way to hack Guile is to use Geiser, both evaluating
from some =foo.scm= file/buffer with more "permanent" code via, for
example, the =C-x C-e= / =C-x C-b= / =C-x C-k= commands to evaluate an
expression, evaluate a whole buffer, or compile a buffer's content,
and switching back and forth between that and the (usually called
=*Geiser Guile REPL*=) experimental-hacking-and-debugging REPL.

This works with Goblins, but Geiser does some things to temporarily
redirect output/error ports when doing the file/buffer oriented
evaluation, and unfortunately this results in Goblins vats potentially
breaking due to spawning a separate thread which inherit these
temporarily redirected ports, which then are closed when the
evaluation succeeds.  We have a long-term plan to deal with this, but
in the meanwhile, whenever you start a Guile / Geiser hacking session,
first execute:

#+BEGIN_SRC scheme
  > (use-modules (goblins))
#+END_SRC

... from the =*Geiser Guile REPL*=.  Otherwise vats may mysteriously
"hang".  We know this is an annoyance!  It'll be fixed soon!


* A high level view of Goblins

Let's start with a sketch of a network of Goblins objects wired
to communicate with each other:

#+BEGIN_SRC text
  .----------------------------------.         .----------------------.
  |            Machine 1             |         |       Machine 2      |
  |            =========             |         |       =========      |
  |                                  |         |                      |
  | .--------------.  .---------.   .-.       .-.                     |
  | |    Vat A     |  |  Vat B  |   |  \______|  \_   .------------.  |
  | |  .---.       |  |   .-.   | .-|  /      |  / |  |    Vat C   |  |
  | | (Alice)----------->(Bob)----' '-'       '-'  |  |  .---.     |  |
  | |  '---'       |  |   '-'   |    |         |   '--->(Carol)    |  |
  | |      \       |  '----^----'    |         |      |  '---'     |  |
  | |       V      |       |         |         |      |            |  |
  | |      .----.  |       |        .-.       .-.     |  .------.  |  |
  | |     (Alfred) |       '-------/  |______/  |____---( Carlos ) |  |
  | |      '----'  |               \  |      \  |     |  '------'  |  |
  | |              |                '-'       '-'     '------------'  |
  | '--------------'                 |         |                      |
  |                                  |         |                      |
  '----------------------------------'         '----------------------'
#+END_SRC

In the above diagram, we see:

 - Two machines (=Machine 1= and =Machine 2=, running separately from
   each other, but connected to each other over the network via OCapN
   and CapTP.

 - =Vat A= and =Vat B= are event loops which live on =Machine 1=,
   and =Vat C= is an event loop which live son =Machine 2=.

 - The individual objects (represented by circles) live in /vats/,
   aka event loops which contain objects.  =Alice= and
   =Alfred= live in =Vat A=, =Bob= lives in =Vat B=, and =Carol= and
   =Carlos= live on =Vat C=.  (While we've given these objects
   human-like names, they're just Goblins objects.)

 - The arrows between the objects represent references these objects
   have to each other.  =Alice= has references to both =Alfred= and
   =Bob=.  =Bob= has a reference to =Carol=.  =Carlos= has a reference
   to =Bob=.

 - Two objects which are in the same vat are considered /near/ each
   other, and thus can invoke each other synchronously, whereas any
   objects not in the same vat are considered /far/ from each other.
   Any objects can invoke each other by asynchronous message
   passing... assuming they have a reference to each other.

 - Not pictured: each vat has an /actormap/, an underlying
   transactional heap used for object communication.  This is what
   permits transactionality and time travel.  (Actormaps can also used
   independently of vats for certain categories of applications.)

Another way to think about this is via the following abstraction
nesting dolls:

#+BEGIN_SRC scheme
  (machine (vat (actormap {refr: object-behavior})))
#+END_SRC

 - *Machines*, which are computers on the network, or more
   realistically, operating system processes, which contain...
 - *Vats*, which are communicating event loops, which contain...
 - *Actormaps*, transactional heaps, which contain...
 - A mapping of *References* to *Object Behavior*.

** The "vat model" of computation

As said, Goblins follows what is called the /vat model/ of
computation.
A /vat/ is simply an event loop that manages a set of
objects which are /near/ to each other (and similarly, objects outside
of a vat are /far/ from each other).

Objects which are /near/ can perform synchronous call-return
invocations in a manner familiar to most sequential programming
languages used by most programmers today.  Aside from being
a somewhat more convenient way to program, sequential invocation
is desirable because of cheap /transactionality/, which we shall
expand on more later.  In Goblins, we use the =$= operator
to perform synchronous operations.

Both /near/ and /far/ objects are able to invoke each other
asynchronously using asynchronous message passing (in the same style
as the /classic actor model/).  It does not
generally matter whether or not a /far/ object is running within the
same OS process or machine or one somewhere else on the
network for most programming tasks; asynchronous
message passing works the same either way.  In Goblins, we use the
=<-= operator to perform asynchronous operations.
# [fn:classic-actors] [fn:session-severance]

For both programmer convenience and for networked efficiency, Goblins
supports /promise pipelining/: messages can be sent to promises which
have not yet resolved, and will be forwarded to the target once the
promise resolves.
The sender of the message is handed back a promise to which it can
supply callbacks, listening for the promise to be fulfilled with a
value or broken (usually in case of an unexpected error).
# [fn:full-promise-vision]

As usual in the vat model of computation, individual message sends to
a vat (event loop) are queued and then handled one /turn/ at a time,
akin to the way board game players take turns around a table (which is
indeed the basis for the term /turn/).

The message, addressing a specific object, is passed to the recipient
object's current behavior.  This object may then invoke other
/near/ objects (residing within the same vat), which may themselves
invoke other near objects in a synchronous and sequential call-return
style familiar to most users of most contemporary programming
languages.  Any of these invoked objects may also change their
state/behavior (behavior changes appear purely functional in Goblins;
invocations of other actors do not), spawn new objects, invoke
ordinary expressions from the host language, or send asynchronous
messages to other objects (which are only sent if the /turn/ completes
successfully).

While the /vat model/ of computation is not new (it originates in the
[[http://erights.org/][E]] programming language and can trace some of its ideas back to E's
predecessor [[http://erights.org/history/joule/][Joule]], and has since reappeared in systems such as
[[https://agoric.com/][Agoric's]] [[https://github.com/Agoric/agoric-sdk/tree/master/packages/SwingSet][SwingSet]] kernel), Goblins brings some novel contributions to
the table in terms of transactionality and time-travel debugging,
enhancing an already powerful distributed programming paradigm.

* Tutorial

** A simple greeter

First, let's import Goblins:

#+BEGIN_SRC scheme
  > (use-modules (goblins))
#+END_SRC

(*NOTE*: See [[*TEMPORARY: Live hacking "fix"][TEMPORARY: Live hacking "fix"]] if you haven't.)

Every Goblins actor / object has to live in a vat somewhere.
So, let's make a vat to play around with:

#+BEGIN_SRC scheme
  > (define a-vat
      (spawn-vat))
  ;; This will make interacting with the vat a bit easier
  > (define-vat-run a-run a-vat)
#+END_SRC

Objects/actors are instantiated with =spawn= and can be synchronously
invoked with =$= or asynchronously invoked with =<-=.
All of these operations need to operate within a Goblins-aware context,
and so =a-run= "bootstraps" some code within the vat.

Now let us implement a friend who will greet us:

#+BEGIN_SRC scheme
(define (^greeter bcom our-name)   ; constructor (outer procedure)
  (lambda (your-name)              ; behavior    (inner procedure)
    (format #f "Hello ~a, my name is ~a!"
            your-name our-name)))
#+END_SRC

Let's give it a try by instantiating an instance of =^greeter= using
=spawn= and assign her to the variable =alice=:

#+BEGIN_SRC scheme
 > (define alice
     (a-run (spawn ^greeter "Alice")))
#+END_SRC

The first argument to =spawn= is the constructor we will use to make
our Goblins object, in this case =^greeter=.
The remaining arguments will be passed to the constructor,
along with an implicit argument which can be used to change object
behavior called =bcom= (pronounced "become").
Thus ="Alice"= maps to =our-name=.

We can invoke =alice= by using =$= for a synchronous call-return
operation:

#+BEGIN_SRC scheme
 > (a-run ($ alice "Alfred"))
 ; => "Hello Alfred, my name is Alice!"
#+END_SRC

The first argument to =$= is the object to be invoked, the remaining
arguments are passed to the "behavior" of the object.
Thus =your-name= in =^greeter='s behavior procedure is bound to
="Bob"=.
The behavior procedure thus proceeds with formatting and returning the
greeting string.

** State as updating behavior

Let's introduce a simple cell which stores a value.
This cell will have two methods:
='get= retrieves the current value, and ='set= replaces
the current value with a new value.

#+BEGIN_SRC scheme
(define* (^cell bcom #:optional [val #f])
  (case-lambda
    (()         ; get
     val)
    ((new-val)  ; set
     (bcom (^cell bcom new-val)))))
#+END_SRC

=case-lambda= allows for dispatching depending on the number of
arguments, so here we're choosing that if no arguments are provided,
our cell shares the current value, and if one argument is provided,
the cell updates itself to become a cell storing the new value.

Let's try it.
Cells hold values, and so do treasure chests, so let's make
a treasure chest flavored cell.
Taking things out and putting them back in is easy:

#+BEGIN_SRC scheme
  > (define chest
      (a-run (spawn ^cell "sword")))
  > (a-run ($ chest))
  ; => "sword"
  > (a-run ($ chest "gold"))
  > (a-run ($ chest))
  ; => "gold" 
#+END_SRC

Now we can see what =bcom= is: a capability specific to this object
instance which allows it to change its behavior!
(For this reason, =bcom= is pronounced "become"!)

** Methods aren't essential, but they are useful

The most common way to select different sub-behaviors isn't by the
number of arguments though.
It's much more common to have "methods" that are selected by name.
We can use the =methods= macro to do just that:

#+BEGIN_SRC scheme
(use-modules (goblins actor-lib methods))

(define* (^mcell bcom #:optional [val #f])
  (methods
   ((get)
    val)
   ((set new-val)
    (bcom (^mcell bcom new-val)))))
#+END_SRC

The use of =^mcell= is similar, but now we pass in a first argument
as a symbol selecting the method, and the rest of the arguments are
passed to the object:

#+BEGIN_SRC scheme
  > (define jar
      (a-run (spawn ^mcell "cookies")))
  > (a-run ($ jar 'get))
  ; => "cookies"
  > (a-run ($ jar 'set "crumbs"))  
  > (a-run ($ jar 'get))
  ; => "crumbs"
#+END_SRC

Methods aren't particularly magical... the =methods= macro just
returns a procedure which is convenient to use for procedure dispatch:

#+BEGIN_SRC scheme
  > (define foo-or-bar
      (methods
       ((foo)
        'called-foo)
       ((bar arg)
        (list 'called-bar-with arg))))
  > (foo-or-bar 'foo)
  ; => called-foo
  > (foo-or-bar 'bar "meep")
  ; => (called-bar-with "meep")
#+END_SRC

So really, =methods= just makes a particularly useful kind of
behavior procedure for us, one which takes a first argument for
the method name, grabs the rest of the arguments, and then applies
them to the relevant method.

** Objects which contain objects

Objects can also contain and define other object references, including
in their outer constructor procedure.

Here is the definition of a "counting greeter" we call =^cgreeter=:

#+BEGIN_SRC scheme
(define (^cgreeter _bcom our-name)
  (define times-called
    (spawn ^mcell 0))
  (methods
   ((get-times-called)
    ($ times-called 'get))
   ((greet your-name)
    ;; increase the number of times called
    ($ times-called 'set
       (+ 1 ($ times-called 'get)))
    (format #f "[~a] Hello ~a, my name is ~a!"
            ($ times-called 'get)
            your-name our-name))))
#+END_SRC

As we can see near the top, =times-called= is instantiated as an
=^cell= like the one we defined earlier.
The current value of this cell is returned by =get-times-called=
and is updated every time the =greet= method is called:

#+BEGIN_SRC scheme
  > (define julius
      (a-run (spawn ^cgreeter "Julius")))
  > (a-run ($ julius 'get-times-called))
  ; => 0
  > (a-run ($ julius 'greet "Gaius"))
  ; => "[1] Hello Gaius, my name is Julius!"
  > (a-run ($ julius 'greet "Brutus"))
  ; => "[2] Hello Brutus, my name is Julius!"
  > (a-run ($ julius 'get-times-called))
  ; => 2
#+END_SRC

** Asynchronous message passing

We have shown that the behavior of objects may be invoked
synchronously with =$=.
However, this only works if two objects are both defined on the same
machine on the network and the same event loop within that machine.

To demonstrate this, let's create a new vat, =b-vat= (as well as a
=b-run= to make REPL examples a bit easier to demonstrate):

#+BEGIN_SRC scheme
  > (define b-vat
      (spawn-vat))
  > (define-vat-run b-run b-vat)
#+END_SRC

Now, recall our friend =alice= who we defined on vat A.
The following works just fine:

#+BEGIN_SRC scheme
 > (a-run ($ alice "Alfred"))
 ; => "Hello Alfred, my name is Alice!"
#+END_SRC

But since Alice works on A, we cannot synchronously invoke her with
=$= on vat B:

#+BEGIN_SRC scheme
> (b-run ($ alice "Bob"))
;; === Caught error: ===
;;  message: #<<message> to: #<local-object> resolve-me: #f args: ()>
;;  exception: ... "Not in the same vat: ~a" #<local-object ^greeter>) ...
#+END_SRC

This is where =<-= comes in.
In contrast to =$=, =<-= can be used against objects which live
anywhere, even on remote machines.
However, unlike invocation with =$=, we do not get back an
immediate result, we get a promise:

#+BEGIN_SRC scheme
> (b-run (<- alice "Bob"))
; => #<promise>
#+END_SRC

This promise must be listened to.
The procedure to listen to promises in Goblins is called
=on=:

#+BEGIN_SRC scheme
  > (b-run
     (on (<- alice "Bob")
       (lambda (got-back)
         (format #t "Heard back: ~a\n"
                 got-back))))
  ; Prints out, at some point in the future:
  ;   "Heard back: [3] Hello Bob, my name is Alice!"
#+END_SRC

Not all communication goes as planned, especially in a distributed
system.
=on= also supports the keyword arguments of =#:catch= and =#:finally=,
which both accept a procedure defining handling errors in the former case
and code which will run regardless of successful resolution or failure
in the latter case:

#+BEGIN_SRC scheme
  > (define (^broken-ben _bcom)
      (lambda ()
        (error "Yikes, I broke!")))
  > (define broken-ben
      (b-run (spawn ^broken-ben)))
  > (a-run
     (on (<- broken-ben)
         (lambda (what-did-ben-say)
           (format #t "Ben says: ~a\n" what-did-ben-say))
         #:catch
         (lambda (err)
           (format #t "Got an error: ~a\n" err))
         #:finally
         (lambda ()
           (display "Whew, it's over!\n")))
#+END_SRC

** Transactions make errors survivable

Mistakes happen, and when they do, we'd like damage to be minimal.
But with many moving parts, accomplishing this can be difficult.

However, Goblins makes our life easier.
To see how, let's intentionally insert a couple of print debugging
lines (with =pk=, which is pronounced and means "peek")
and then an error:

#+BEGIN_SRC scheme
  (define (^borked-cgreeter _bcom our-name)
    (define times-called
      (spawn ^cell 0))
    (methods
      ((get-times-called)
       ($ times-called 'get))
      ((greet your-name)
       (pk 'before-incr ($ times-called 'get))
       ;; increase the number of times called
       ($ times-called 'set
          (+ 1 ($ times-called 'get)))
       (pk 'after-incr ($ times-called 'get))
       (error "Yikes")
       (format #f "[~a] Hello ~a, my name is ~a!"
               ($ times-called 'get)
               your-name our-name))))
#+END_SRC

Now let's spawn this friend and invoke it:

#+BEGIN_SRC scheme
  > (define horatio
      (a-run (spawn ^borked-cgreeter "Horatio")))
  > (a-run ($ horatio 'get-times-called))
  ; => 0
  > (a-run ($ horatio 'greet "Hamlet"))
  ; pk debug: (before-incr 0)
  ; pk debug: (after-incr 1)
  ; ice-9/boot-9.scm:1685:16: In procedure raise-exception:
  ;   Yikes
  ; Entering a new prompt.  Type `,bt' for a backtrace or `,q' to continue.
#+END_SRC

Whoops!  Looks like something went wrong!
We can see from the =pk= debugging that the =times-called= cell should
be incremented to 1.
And yet...

#+BEGIN_SRC scheme
> (a-run ($ horatio 'get-times-called))
; => 0
#+END_SRC

We will cover this in greater detail later, but the core idea here
is that synchronous operations run with =$= are all done together
as one transaction.
If an unhandled error occurs, any state changes resulting from
synchronous operations within that transaction will simply not
be committed.
This is useful, because it means most otherwise difficult cleanup
steps are handled automatically.

** Promise pipelining

#+BEGIN_QUOTE
  "Machines grow faster and memories grow larger.
  But the speed of light is constant and New York is not getting any
  closer to Tokyo."

   --- Mark S. Miller,
       [[http://www.erights.org/talks/thesis/][Robust Composition: Towards a Unified Approach to Access Control and Concurrency Control]]
#+END_QUOTE

Promise pipelining provides two different features at once:

 - A convenient developer interface for describing a series of
   asynchronous actions, allowing for invoking the objects which
   promises will point to before they are even resolved (sometimes
   before the objects even exist!)
 - A network abstraction that eliminates many round trips

Consider the following car factory, which makes cars carrying
the company name of the factory:

#+BEGIN_SRC scheme
  ;; Create a "car factory", which makes cars branded with
  ;; company-name.
  (define (^car-factory bcom company-name)
    ;; The constructor for cars we will create.
    (define (^car bcom model color)
      (methods                      ; methods for the ^car
       ((drive)                    ; drive the car
        (format #t "*Vroom vroom!*  You drive your ~a ~a ~a!"
                color company-name model))))
    ;; methods for the ^car-factory instance
    (methods                        ; methods for the ^car-factory
     ((make-car model color)       ; create a car
      (spawn ^car model color))))
#+END_SRC

Here is an instance of this car factory, which we will call
=fork-motors=:

#+BEGIN_SRC scheme
  ;; Interaction on machine A
  > (define fork-motors
      (a-run
       (spawn ^car-factory "Fork")))
#+END_SRC

Since asynchronous message passing with =<-= works across machines,
it does not matter whether interacitons with =fork-motors are local
or via objects communicating over the network.
We will treat =fork-motors= as living on machine A, and so the
following interactions will happen with invocations originating from
machine B.

Let's send a message to =fork-motors= invoking the ='make-car= method,
receiving back a promise for the car which will be made, which we
shall name =car-vow= (=-vow= being the conventional suffix given
for promises in Goblins):

#+BEGIN_SRC scheme
  ;; Interaction on machine B, communicating with fork-motors on A
  > (define car-vow
      (b-run
       (<- fork-motors 'make-car "Explorist" "blue")))
#+END_SRC


So we have a /promise/ to a future car reference, but not the
reference itself.
We would like to drive the car as soon as it rolls off the lot of the
factory, which of course involves sending a message to the car.

Without promise pipelining, making use of the tools we have already
shown (and following the pattern most other distributed programming
systems use), we would end up with something like:

#+BEGIN_SRC scheme
  ;; Interaction on machine B, communicating with A
  > (b-run
     (on car-vow                    ; B->A: first resolve the car-vow
         (lambda (our-car)          ; A->B: car-vow resolved as our-car
           (on (<- our-car 'drive)  ; B->A: now we can message our-car
               (lambda (val)        ; A->B: result of that message
                 (format #f "Heard: ~a\n" val))))))
#+END_SRC

With promise pipelining, we can simply message the promise of the car
directly.
The first benefit can be observed from code compactness, in that
we do not need to do an =on= of =car-vow= to later message =our-car=,
we can simply message =car-vow= directly:

#+BEGIN_SRC scheme
  ;; Interaction on machine B, communicating with A
  > (b-run
     (on (<- car-vow 'drive)     ; B->A: send message to future car
         (lambda (val)             ; A->B: result of that message
           (format #f "Heard: ~a\n" val))))
#+END_SRC

While clearly a considerable programming convenience, the other
advantage of promise pipelining is a reduction of round-trips, whether
between our event-loop /vats/ or across machines on the network.

This can be understood by looking at the comments to the right of the
two above code interactions.  The message flow in the first case looks
like:

: B => A => B => A => B

The message flow in the second case looks like:

: B => A => B

In other words, machine B can say to machine A: "Make me a car,
and as soon as that car is ready, I want to drive it!"

With this in mind, the promise behind Mark Miller's quote at the
beginning of this section is clear.[fn:thanks-to-e]
If two objects are on opposite ends of the planet, round trips
are unavoidably expensive.
Promise pipelining both allows us to make plans as programmers
and allows for Goblins to optimize carrying out those steps as
bulk operations over the network.

[fn:thanks-to-e] Like so many examples in this document, the designs
of promise pipelining and the explanation of its value come from the E
programming language, the many contributors to its design, and Mark
S. Miller's extraordinary work documenting that work and its history.
If you find this section interesting, both the the [[http://www.erights.org/elib/distrib/pipeline.html][Promise Pipelining]]
page from [[http://erights.org][erights.org]] and sections 2.5 and 16.2 of
[[http://www.erights.org/talks/thesis/markm-thesis.pdf][Mark Miller's dissertation]].

** OCapN, my CapN!

TODO

* API

** Objects

Objects are the core of Goblins.
In general, you'll need to be within an ambient "Goblins Context" (TM)
in order to start programming against them, see [[*Vats][Vats]] for most event
loop type programming, or [[*Actormaps][Actormaps]] if you want to play with more low-level
control over transactional operations.
(However, most users will just use vats.)

*** Spawning objects

Objects can be spawned with the =spawn= operator:

#+BEGIN_SRC scheme
  (spawn CONSTRUCTOR ARGS ...)
  ;; => <local-refr>
#+END_SRC

where =CONSTRUCTOR= is a procedure which itself returns a procedure
representing an object's current behavior.
The =CONSTRUCTOR= is implicitly passed a first argument, traditionally
labeled =bcom=, which can be used to change an object's behavior.
The =ARGS= are passed as the remaining arguments to the constructor.

So for example, let's say we have the following constructor:

#+BEGIN_SRC scheme
  (define* (^cell bcom #:optional val)  ; constructor (outer procedure)
    (case-lambda                        ; behavior    (inner procedure)
      (()                               ; 0-argument invocation (getter)
       val)                             ;   (return current value)
      ((new-val)                        ; 1-argument invocation (setter)
       (bcom (^cell bcom new-val)))))   ;   ("become" ^cell with new value)
#+END_SRC

And so...

#+BEGIN_SRC scheme
  (define some-cell (spawn ^cell 42))
#+END_SRC

will bind =val= to =42=.

*** Synchronous invocation

To synchronously invoke two objects within the same vat / actormap,
use =$=:

#+BEGIN_SRC scheme
  ($ near-object args ...)
  ;; => something
#+END_SRC

Provide a synchronous call against the current message handler of
=NEAR-REFR=, which must be a /near/ =live-refr?=
in the same vat as the currently running actor context.
The value returned is that which is returned by the
current behavior of =NEAR-REFR= upon invocation (or, if
=NEAR-REFR= chose to =bcom= something else, the second
argument passed to its =bcom=, or is =unspecified?= if not provided.)

*** Asynchronous invocation

#+BEGIN_SRC scheme
  (<- near-object arg ...)
  ;; => <local-promise>
#+END_SRC

Like =$=, but called asynchronously and returns a /promise/,
which may be handled with =on=.
Unlike =$=, =<-= is not limited to only /near/ objects;
interaction with /far/ actors are permitted as well.

#+BEGIN_SRC 
  (<-np [actor-refr live-refr?] [arg any/c] ...)
#+END_SRC

Like =<-= but does not return (or require the overhead of) a
promise.
=<-np= is effectively an optimization; where promises are not
needed, using =<-np= over =<-= is a good idea.

#+BEGIN_SRC scheme
(on vow
    [fulfilled-handler]
    [#:catch broken-handler]
    [#:finally finally-handler]
    [#:promise? #f])
#+END_SRC

Sets up promise handlers for =vow=, which is typically a
=live-refr?= to a /promise/ but may be anything.

=fulfilled-handler=, =broken-handler=, and =finally-handler=
all, if specified, may be either a procedure (the most common case)
which is run when =vow= becomes resolved, or a reference to an
actor that should be messaged when the promise is resolved with the
same arguments that would be passed to an equivalent procedure.
As their names suggest, =fulfilled-handler= will run if a promise is
fulfilled and takes one argument, the fulfilled value.
=broken-handler= will run if a promise is broken and takes one
argument, the error value.
=finally-handler= will run when a promise is resolved, no matter the
outcome and is called with no arguments.

If =#:promise?= is set to =#t=, then =on=
will itself return a promise.
The promise will be resolved as follows:

 - If =vow= is fulfilled and =fulfilled-handler= is not
   provided, the promise returned will share =vow='s resolution.
 - If =vow= is broken and =broken-handler= is not
   provided, the promise returned will share =vow='s broken result.
 - If =vow= is fulfilled and =fulfilled-handler= is provided,
   the resolution will be whatever is returned from =fulfilled-handler=,
   unless =fulfilled-handler= raises an error, in which case the promise
   will be broken with its error-value set to this exception.
 - If =vow= is broken and =broken-handler= is provided,
   the resolution will be whatever is returned from =broken-handler=,
   unless =broken-handler= raises an error, in which case the promise
   will be broken with its error-value set to this exception (which
   may even be the original exception).

** Vats

In order to start programming with Goblins, you will need to boot up a
vat somewhere.  Most of Goblins programming doesn't spend much time
with the user thinking particularly hard about vats; most of the

*** Starting and stopping vats

*** COMMENT Rolling your own vats

** Actormaps

** OCapN
** Persistence

* actor-lib: A standard library of sorts

** Cells

** Methods


* COMMENT Design and philosophy

** On the design of Goblins' distributed objects


** Why Scheme?  Why Guile?

** History

** The future: hopes, dreams, and hard work

** License choice

** Spritely and user freedom

* Thanks

This manual was primarily written by Christine Lemmer-Webber.

# Additional text by: ...

Many of the ideas are borrowed from [[http://www.erights.org/talks/thesis/markm-thesis.pdf][Mark Miller's dissertation]],
which is an excellent, if nerdy, read.

Jessica Tallon, Jonathan A. Rees, and Randy Farmer provided review and
feedback.
