Goblins has a secure persistence mechanism that allows for serializing
an entire object graph. The mechanism allows objects to describe
themselves with only the capabilities they have, this protects against
one object claiming it has more abilities than it actually does.

When the object graph can be serialized it allows for it to be stored
(e.g. to disk) and restored (sometimes called rehydrated) into the
objects it consisted of. Due to the nature of how the persistence
mechanism works, it also can be used as a powerful tool in object
upgrade and live hacking.

@menu
* Persistence Tutorial::
* Persistence capable objects::
* Operations on actormaps::
* Persistent Vats::
* Persistence Environments::
* Upgrading through persistence::
* Persistence stores::
@end menu

@node Persistence Tutorial
@section Persistence Tutorial

When writing goblins code without considering persistence, we simply
define a outer lambda (the constructor, usually ^my-constructor) and
an inner lambda (the behavior) that's invoked when the object is sent
messages. Persistence capable objects are a little different; they do
still follow this general pattern, but they need to provide a way to
describe themselves. Fortunately goblins provides a macro called
@code{define-actor} which makes this easier (if you're doing something
more advanced where the macro is unsuitable, or simply prefer not
using it, @xref{Persistence capable objects}).

Lets take the cell example we defined in the tutorial:

@lisp
(define* (^cell bcom #:optional [val #f])
  (case-lambda
    (()         ; get
     val)
    ((new-val)  ; set
     (bcom (^cell bcom new-val)))))
@end lisp

Assuming we want to upgrade this to be persistence capable, you just
change it to @code{define-actor}:

@lisp
(define-actor (^cell bcom #:optional [val #f])
  (case-lambda
    (()         ; get
     val)
    ((new-val)  ; set
     (bcom (^cell bcom new-val)))))
@end lisp

And it's done! Lets try it out. To use the persistence tooling, you
need to define a persistence environment. What is this extra thing I
hear you ask?

In short, when Goblins serializes all the objects in the graph it
needs to take them from scheme procedures (which can't be serialized)
to something else. It does this by storing them with a name/label and
the data the actor told Goblins it wanted. The persistence environment
is simply a mapping between name/label <=> object type.

Lets define one that just has our new shiny persistence @code{^cell}:

@lisp
(define my-env
  (make-persistence-env
   `((((my-cool-scheme-project cell) ^cell) ,^cell))))

;;    |-----------------------------------|  |------|
;;            this is the label/name          object
@end lisp

Just remember the label/name should be unique within the object graph,
or you'll get into quite the pickle (for more information, see
@xref{Persistence Environments}).

The persistence tools work with both actormaps and vats (they use the
same tooling even as vats are built on actormaps). When we use vats we
need to specify a store which is basically a place for the vat to save
the serialized data to or find it when it starts back up.

For this example lets just use the memory store, which is ephemeral and
is not actually saved to any long-term storage:

@lisp
(use-modules (goblins)
             (goblins persistence-store memory))

(define memory-store (make-memory-store))
(define-values (my-vat my-cell)
  (spawn-persistent-vat
    my-env
    (lambda ()
      (spawn ^cell))
    memory-store))
@end lisp

Hold on, did we just spawn our object alongside spawning the vat?

Yes we did, we don't need to do it for all the objects in the graph,
just the roots. When we call @code{spawn-persistence-vat} it checks in
our store to see if there's already persistence data and if there is
it doesn't invoke the thunk we provided, it instead restores the graph
from that data and hands us back the objects. In our case though the
store is empty so it spanwed our cell from the thunk we provided.

Lets enter the vat and use the cell:
@lisp
,enter-vat my-vat
goblins[1]> ($ my-cell 'apple)
@end lisp

Okay we stored an apple but how do we persist this? Well, it already
is persisted. By default vats are configured to store the changed
objects.

An interesting debugging tool we can use however is the vat command to
inspect what the persistence data for a given object looks like:

@lisp
goblins[1]> ,vat-take-object-portrait my-cell
(apple)
@end lisp

So lets take a more advanced example of a persistent object. Lets
first build it without persistence in mind and then see some of the
problems we might face making it persistence aware. Here's a basic a
player ship, it has some positions, a @code{fire} method and it can
be killed, once it's killed it just becomes some dead behavior which
errors. It also has this @code{tick} that can be hooked up to a game
loop and will move to player ship forward in the x axis:

@lisp
(define (^player-ship bcom init-x init-y)
  (define x (spawn ^cell init-x))
  (define y (spawn ^cell init-y))
  (define (dead-beh)
    (error "I'm already dead!"))
  (define active-beh
    (methods
     [(tick) ($ x (+ ($ x) 1))]
     [(x) ($ x)]
     [(y) ($ y)]
     [(fire) "pew pew"]
     [(kill) (bcom dead-beh)]))
  active-beh)
@end lisp

We could just change this to define-actor and at first, maybe it'd
seem like it worked, but it actually has some big problems. Let's
actually see this happen:

@lisp
(use-modules (goblins actor-lib methods))

(define-actor (^player-ship bcom init-x init-y)
  (define x (spawn ^cell init-x))
  (define y (spawn ^cell init-y))
  (define (dead-beh)
    (error "I'm already dead!"))
  (define active-beh
    (methods
     [(tick) ($ x (+ ($ x) 1))]
     [(x) ($ x)]
     [(y) ($ y)]
     [(fire) "pew pew"]
     [(kill) (bcom dead-beh)]))
  active-beh)

goblins[1]> (define ship (spawn ^player-ship 0 0))
goblins[1]> ,vat-take-object-portrait ship
(0 0)
goblins[1]> ;; Lets tick the game loop and see if x changes
goblins[1]> ($ ship 'tick)
goblins[1]> ,vat-take-object-portrait ship
(0 0)
goblins[1]> ($ ship 'kill)
goblins[1]> ,vat-take-object-portrait ship
(0 0)
@end lisp

As we can see, initially it looked correct. We ticked it once and we
checked to see what the persistence system would get and it didn't
update, we then killed the ship and the portrait again didn't change,
how will Goblins know the ship is no longer alive.

The problem we're facing here is that we take two static initial x, y
values into the object and that's what Goblins is seeing. We then
spawn cells internally but these cells are not exposed to goblins and
we're not updating them to bcom.

So how can we write this with persistence aware? This player ship
solves these problems:

@lisp
(define-actor (^player-ship bcom x y #:key [active? #t])
  (define (dead-beh)
    (error "I'm already dead!"))
  (define active-beh
    (methods
     [(tick) (bcom (^player-ship bcom (+ 1 x) y))]
     [(x) x]
     [(y) y]
     [(fire) "pew pew"]
     [(kill) (bcom (^player-ship bcom x y #:active? #f))]))
  (if active?
      active-beh
      dead-beh))

goblins[1]> (define ship (spawn ^player-ship 0 0))
goblins[1]> ,vat-take-object-portrait ship
(0 0 #:active? #t)
goblins[1]> ;; Lets tick the game loop and see if x changes
goblins[1]> ($ ship 'tick)
goblins[1]> ,vat-take-object-portrait ship
(1 0 #:active? #t)
@end lisp

Instead of having internal cells we mutate, we just change the values
in the constructor and Goblins is able to see that and ensure the
portrait is adjusted correctly, equally switching between the two
different states is done by having that be passed in to the
constructor too.

In most cases, and usually when using @code{define-actor}, we need to
think the behavior and state being determined by the constructor, not
relying on internal state.

There are many ways to write this object and I'm going to show you two
more and then put these different ideas together to create a much more
advanced player ship.

We don't have to do away with cells, we could pass cells into the
constructor and then Goblins will be able to see that, but then we
loose some of the old erganomics and interface of the object, users
would have to manually spawn these cells.

Here's a solution to continue to use cells but keep the old interface:

@lisp
(use-modules (goblins actor-lib cell))

;; IMPORTANT: note this is now ^player-ship* not ^player-ship.
(define-actor (^player-ship* bcom x y #:key [active? #t])
  (define (dead-beh)
    (error "I'm already dead!"))
  (define active-beh
    (methods
     [(tick) ($ x (+ ($ x) 1))]
     [(x) ($ x)]
     [(y) ($ y)]
     [(fire) "pew pew"]
     [(kill) (bcom (^player-ship bcom x y #:active? #f))]))
  (if active?
      active-beh
      dead-beh))

(define (^player-ship bcom x y)
  (spawn ^player-ship*
         (spawn ^cell x)
         (spawn ^cell y)))

;; NOTE: Because of the feature of returning a refr described
;; below, only `^player-ship*` needs to be in the environment
(define my-env
  (make-persistence-env
    `((((my-cool-scheme-project game) ^player-ship) ,player-ship*))
    #:extends cell-env))
@end lisp

This has a pattern of having a sort of ``public'' constructor which
allows for nice erganomics, and maybe does some setup and then hands
off to a ``real'' or ``internal'' constructor for the actor. In this
case the public version both prevents a user spawning a dead ship to
begin with and handles the cellification of the x and y coordinates.

Normally in Goblins an object returns behavior as a procedure from the
constructor, however you can return a refr to another object and
Goblins will instead of creating a new object with spawn, simply
return the refr returned by the object's constructor.

The new persistence environment provided defines a single object, just
the @code{^player-ship*}. This is because, as explained above, the
@code{^player-ship} doesn't remain around. This also instead of using
our cell we defined above, uses the one from actor-lib so we need to
extend from the @code{cell-env} provided by the cell
module. Persistence environments can extend from one or a list of
several environments as needed.

Okay, so that's bringing the cells back. Having a sort of ``state''
flag passed into the object allows us to decide if the active or dead
behavior should be returned, but there are other ways to do that. Lets
look at an interesting one which uses Goblin's swappable library (for
more information on this library, @xref{Swappable}):

@lisp
(use-modules (goblins actor-lib swappable))

;; Public constructor again, except this time spawning the swappable
;; object as well as cellifying the x and y coordinates.
(define (^player-ship bcom x y)
  (define-values (beh-proxy beh-swapper)
    ;; NOTE: Due to how swappable works, it must be spawned with a
    ;; refr. use a place holder one which we will immidately switch
    ;; away from.
    (swappable (spawn (lambda _ (lambda _ 'noop)))))
  ;; Swap away from the dummy place-holder above directly to the
  ;; initial, default behavior of the alive player-ship
  ($ beh-swapper (spawn ^player-ship:ALIVE
			(spawn ^cell x)
			(spawn ^cell y)
			beh-swapper))
  ;; Return the proxy we setup.
  beh-proxy)

;; The behavior and state for the alive player ship
(define-actor (^player-ship:ALIVE bcom x y swapper)
  (methods
   [(tick) ($ x (+ ($ x) 1))]
   [(x) ($ x)]
   [(y) ($ y)]
   [(fire) "pew pew"]
   [(kill) ($ swapper (spawn ^player-ship:DEAD x y swapper))]))

;; The behavior and state for the dead player ship
(define-actor (^player-ship:DEAD bcom x y swapper
                                 #:optional [countdown 30])
  (methods
   [(tick)
    ;; When dead instead of moving, just wait until the countdown
    ;; has reached zero and then swap to alive.
    (if (zero? countdown)
        ($ swapper (spawn ^player-ship:ALIVE x y swapper))
        (bcom (^player-ship:DEAD bcom x y swapper (- countdown 1))))]
   [(x) ($ x)]
   [(y) ($ y)]
   [(fire) 'noop]   ;; cannot fire when dead
   [(kill) 'noop])) ;; cannot be killed when dead

;; Note because the swappable and cell objects are being passed in and
;; thus need to be persisted in the graph, we *MUST* include those in
;; persistence environment.
(define game-env
  (make-persistence-env
   `((((game) ^player-ship:ALIVE) ,^player-ship:ALIVE)
     (((game) ^player-ship:DEAD) ,^player-ship:DEAD))
   #:extends (list swappable-env cell-env)))
@end lisp

So this is returning the proxy object from swappable as the
player-ship and then giving the capability to swap to the ships which
swap between the alive and dead states. While this is probably
overkill for our version of the player ship, we can see how if an
object had many different behaviors and those behaviors had their own
state associated with them, this could be a powerful way of building
objects.

If you're wondering if you could simplify this by removing the swapper
and just doing a @code{(bcom (spawn ^player-ship:DEAD ...))} this does
not work, Goblins does not allow the object to beocme something its
not, this would be a security issue.

And that's it!

Go out and save the world :)

@node Persistence capable objects
@section Persistence capable objects

When using the persistence mechanism you take a portrait of a graph, the
graph has one or more roots. All object references starting from those
root objects will be serialized, this even for graphs which contain
cycle. Take the following graph:

@verbatim

       A           H                 <-- roots
      /|\          |
     / E \         J
    B     F
   / \
  C   D
@end verbatim

The root objects would be objects @code{A} and @code{H}.

In order for an object to have persistence support it must be able to
create a self portrait of itself. The self portrait is a collection of
all the data and capabilities an object has thats needed to restore
itself. This can be done by creating a function will be called upon
taking a portrait return a list containing all the portrait data. The
data can include references to other local objects.

Lets take a really simple example which is just an object which has a
name it's known by and greets you:

@lisp
(use-modules (goblins))

(define (^greeter _bcom our-name)
  (lambda (their-name)
    (format #f "Hello ~a, my name is ~a" their-name
            our-name)))
@end lisp

This object is not persistence capable, that is it does not currently
have a mechanism to describe itself to create the self portrait. Trying
to take a portrait of a graph with a non-persistence aware object will
result in an error. The easiest way to convert this to a persistence
aware object is to use the @code{define-actor} macro:

@lisp
(use-modules (goblins)
             (goblins actor-lib define-actor))

(define-actor (^greeter _bcom our-name)
  (lambda (their-name)
    (format #f "Hello ~a, my name is ~a" their-name
            our-name)))
@end lisp

That's it! The @code{define-actor} macro is probably good enough to
handle most use cases. There will however be cases where you need to be
a bit more explicit regarding serialization. The @code{define-actor}
macro takes all of the values it's spawned with, and keeps them around
so that you can be re-spawned with those values, however there may be
times for example where you need to convert certain values to a
serializable form.

In cases where you do need to be more explicit and can't rely on the
macro, you can do this manually. To do this we can define a
self-portrait function which is called when the persistence system is
taking a portrait, this function is expected to return either a list of
values or a versioned tagged list of values (more on versioning
@xref{Upgrading through persistence}). Here's the same greeter but
manually specifying the self-portrait behavior:

@lisp
(use-modules (goblins))

(define (^greeter _bcom our-name)
  (define (main-beh their-name)
    (format #f "Hello ~a, my name is ~a" their-name
            our-name))
  (define (self-portrait)
    (list our-name))
  (portraitize main-beh self-portrait))
@end lisp

The persistence system supports the following types:

@itemize @bullet
@item
number
@item
boolean
@item
character
@item
string
@item
symbol
@item
bytevector
@item
list
@item
vector
@item
keyword
@item
ghash
@item
tagged value (from the @code{(goblins abstract-types)} module)
@item
zilch (from the @code{(goblins abstract-types)} module)
@item
local object refr
@item
resolved local promises
@item
All OCapN IDs from @code{(goblins ocapn ids)}
@end itemize

Any other value of another type needs to be converted into one of the
supported types above.

As mentioned above, the goblins persistence system can handle references
to objects within the same actormap or vat, you simply include the refer
when persisting. Let's take a look at a greeter which does that, keeping
track of the number of types its been called:

@lisp
(use-modules (goblins)
             (goblins actor-lib cell))

(define-actor (^greeter* _bcom our-name number-of-times)
  (lambda (their-name)
    (let ((times ($ number-of-times)))
      ($ number-of-times (+ 1 times))
      (format #f "Hello ~a, my name is ~a (called ~a)"
              their-name our-name times))))

(define* (^greeter bcom our-name #:optional [number-of-times 0])
  (^greeter bcom our-name (spawn ^cell number-of-times)))
@end lisp

This example uses @code{define-actor} with a seperate constructor which
``cellifies` the number-of-times and has a default argument. The
@code{define-actor} will include both the name (a string, like before)
and a local reference to the cell object containing the number of times
called. This could have also been written a different way using the
manual, more explicit way, this exercise is left to the reader.

@node Operations on actormaps
@section Operations on actormaps

Using the persistence support on an actormap allows for taking a
portrait of its current state, rehydrating that state into an actormap
and updating the behavior of an object through an upgrade mechanism.

@deffn {Procedure} actormap-take-portrait am persistence-env . roots

Takes a portrait of the objects within the actormap starting with the
supplied roots.

This takes an actormap, @var{am} which contains the objects and an
@var{persistence-env} which describes some additional information about
all the objects within the graph that's needed to support persistence.
The final arguments are all the roots within the graph.

The portrait is a map where each object within the portrait that is
represented by an integer which maps to its respective portrait data (in
a serializable form), this integer is known as a slot. When an object
contains a reference to another object, that object is referred
to by its slot.

The procedure returns two values to its continuation, those are:

1. the self portrait data
2. the root slots: these are in order the integers of the root objects.

@end deffn

@deffn {Procedure} actormap-restore! am persistence-env portrait-data roots

This restores the objects in the actormap @var{am} from the portrait data
@var{portrait-data} using the object specifications data stored in
@var{persistence-env} with the given @var{roots}.

Due to the way rehydration of depictions works each object is
represented as a vow which will be resolved when returned.

This procedure returns to the continuation all the references to the
restored objects for the given @var{roots}. This is so that the number
of values returned is equal to the number of roots provided.

@end deffn

@deffn {Procedure} actormap-replace-behavior! am persistence-env

Replace actors in actormap @var{am} with new behavior from
@var{persistence-env}

It's often desirable, especially when developing a system, to update or
otherwise change the bahavior of objects which already exist in an
actormap. This can easily be done by using the persistence system in
Goblins. Each object can describe itself through its self portrait and
then be rehydrated into its new behavior allowing seamless upgrades.

This procedure will first calculate all of the objects that have an
updated constructor within @var{persistence-env}. It will then take a
portrait all those objects, then using that portrait data, rehydrate
them with the new behavior keeping the object references the same.

It's important to note that in order to be able to replace the
bahavior the objects must be been defined as redefinable, this is
commonly done by using the @code{define-hackable} macro provided with
Goblins. Non-redefinable actors will not have their bahavior replaced
as they will appear as different objects within the
@var{persistence-env}.

@end deffn

@deffn {Procedure} actormap-replace-behavior am persistence-env

Functional version of @code{actormap-replace-behavior!}

This works the same as `actormap-replace-behavior!' but it returns a
transactormap which the user can choose whether or not to commit.

@end deffn

@node Persistent Vats
@section Persistent Vats

When a vat is spawned, it can be spawned as a persistent vat with a
given persistence environment and set of roots. The vat also has a
storage provider associated with it. Vats can be persisted either on
each churn (when the vat reaches quiescence), or manually. If a vat is
configured to persist on churns, just the objects which have changed
(using become) will be persisted.

@deffn {Procedure} spawn-persistent-vat persistent-env spawn-roots-thunk @
       store [#:persist-on] [#:vat-constructor] [#:name] [#:log?]
       [#:log-capacity] [#:aurie-registry]

Create and return a reference to a new @emph{vat} configured with
persistence.

@itemize
@item
@var{persistence-env}: The persistence environment containing all
objects within the persistence graph (@xref{Persistence Environments})

@item
@var{spawn-roots-thunk}: A thunk which is invoked if no persisted
state of the vat exists. The lambda should spawn and return the roots
of the object graph to be persisted.

@item
@var{store}: The store that persistence data will be read and written
to @xref{Persistence stores}.

@item
@var{persist-on}: If @code{'churn} will persist on churns, otherwise
in a manual persistence mode (default: @code{'churn}).

@item
@var{vat-constructor}: The constructor used to create the vat,
defaults to @code{spawn-fibrous-vat}.

@var{name}: Name of the vat.  Note that this is @emph{not} the name it is
bound to in the current namespace.

@item
@var{log?}: If @code{#t}, log @emph{vat} events; otherwise, do not.

@item
@var{log-capacity}: Number of events to be retained in the log.
Defaults to 256.

@item
@var{aurie-registry}: The refr to a shared ^aurie-registry object which, if
provided, enables persisting and rehydrating objects from other local vats.

@end itemize

@lisp
(define-actor (^counter bcom value)
  (lambda ()
    (bcom (^counter bcom (+ 1 value)) value)))

(define persistence-env
  (make-persistence-env
   `((((counter) ^counter) ,^counter))))

(define-values (vat my-counter)
  (spawn-persistent-vat
   persistence-env
   (lambda ()
     (spawn ^counter 0))
   (make-memory-store)))
@end lisp

The @code{^aurie-registry} actor is designed to be spawned anew each time the
program starts (i.e. is not part of the persistence graph) and is shared amongst
several persistent vats which want to persist/rehydrate objects across vats.

Unlike local near refrs which are promises during rehydration, but are swapped
to local refrs after rehydration is complete, Far refrs remain promises and
should resolve after both vats are setup and have registered themselves with
the @code{^aurie-registry} object.

Here's an example of two vats, the cell on @code{b-vat} holds a reference to
an object on @code{a-vat}

@lisp
;; Spawn the aurie registry in its own vat without persistence enabled.
(define aurie-vat (spawn-vat))
(define aurie-registry
  (with-vat aurie-vat
    (spawn ^aurie-registry)))

;; Spawn the initial a-vat with an a-cell object
(define a-vat-store (make-memory-store))
(define-values (a-vat a-cell)
  (spawn-persistent-vat
   cell-env
   (lambda () (spawn ^cell))
   a-vat-store
   #:aurie-registry aurie-registry))

;; Spawn a b-vat with a b-cell object, that will reference the far refr a-cell
(define b-vat-store (make-memory-store))
(define-values (b-vat b-cell)
  (spawn-persistent-vat
   cell-env
   (lambda () (spawn ^cell a-cell))
   b-vat-store
   #:aurie-registry aurie-registry))
@end lisp

@end deffn

@node Persistence Environments
@section Persistence Environments

All persistence aware objects need be defined in what's known as an
persistence environment. These environments specify a set of information
which must exist to be able to take portrait and/or rehydrate objects.
This is a unique name for the object, the constructor, and if different
from the constructor, a function to rehydrate the object upon
rehydration.

When taking portraits of objects or rehydrating them every single object
must be present in the given persistence env, this would obviously be
quite tedious as object graphs get larger and contain lots of different
objects. This is made easier by the persistence environments being able
to extend from (or inherit from) other persistence environments. Lets
take the idea of our greeter:

@lisp

(use-modules (goblins)
             (goblins actor-lib cell))

(define* (^greeter _bcom our-name #:optional (init-number-of-times #f))
  (define number-of-times
    (or init-number-of-times (spawn ^cell 0)))
  (lambda (their-name)
    ($ number-of-times (+ ($ number-of-times) 1))
    (format #f "Hello ~a, my name is ~a (called: ~a)"
            their-name our-name ($ number-of-times))))
@end lisp

The persistence environment here would need to specify two objects, the
@code{^greeter} object and the @code{^cell} object. This is made a
little more complicated by the fact that we didn't define @code{^cell},
we're using that from a library, Goblins' actor-lib library.

This is where persistence environment inheritance helps, we can specify
the objects we've defined (i.e. @code{^greeter}) and specify the
persistence environment that actor-lib's cell module provides for us:

@lisp
(define greeter-env
  (make-persistence-env
   (list (list '((greeter) ^greeter) ^greeter))
   #:extends cell-env))
@end lisp

If we later wanted to define another persistence environment which uses
our greeter, we could define a new persistence environment which
extends from @var{greeter-env}.

@deffn {Procedure} make-persistence-env bindings #:extends

This creates a persistence environment based on a set of object
specifications and a list of other persistence environments to extend
from.

This takes two arguments, each being a list. The first is @var{bindings}
which is a list of all the object specifications specified as a list:

(OBJECT-NAME OBJECT-CONSTRUCTOR [OBJECT_REHYDRATOR])

The second keyword argument, @var{extends} is either a single persistent
environment to extend from, or a list of several persistent environments
to extent from.

Important: Care should be taken to prevent cycles within persistence
environments.

This procedure returns a single value, a persistence environment.

@end deffn

@node Upgrading through persistence
@section Upgrading through persistence

The design of the persistence system allows for this to be a powerful
mechanism to make upgrades for object data. The very basic situation of
adding a new piece of data is automatic as you can provide a default
value. More complicated data upgrade is also fully supported. Lets take
an example of a thermostat that represents the set temperature in
fahrenheit:

@lisp
(define (^thermostat bcom temperature)
  (define main-beh
    (methods
     [(get-current-temp) temperature]
     [(set-temp new-temp) ...]))
  (define (self-portrait)
    (list temperature))
  (portraitize main-beh self-portrait))

(define thermostat-env
  (make-persistence-env
   (list (list ''((house temp) ^thermostat) ^thermostat))))
@end lisp

Later, we want to change the thermostat object to work with the set
temperature in Celsius. Normally this is a bit tricky as we have just
stored an integer for the portrait data, however Goblins tags this data
with a version and it can be upgraded and tagged by us too, lets take a
look at how we can upgrade the above actor using this upgrade mechanism:

@lisp
(define (^thermostat bcom temperature)
  (define main-beh
    (methods
     [(get-current-temp) temperature]
     [(set-temp new-temp) ...]))
  (define (self-portrait)
    (versioned 1 (list temperature)))
  (portraitize main-beh self-portrait))

(define (rehydrate-thermostat version restored-temperature)
  (define temperature
    (match version
      ;; F -> C conversion
      [0 (+ (* 9/5 restored-temperature) 32)]
      ;; C, no conversion needed.
      [1 restored-temperature]))
  (spawn ^thermostat temperature))

(define thermostat-env
  (make-persistence-env
   (list (list '((house temp) ^thermostat) ^thermostat rehydrate-thermostat))))
@end lisp

There are two changes here:

1. The thermostat object's @code{self-portrait} function now versions
the data with version 1.
2. We now have this @code{rehydrate-thermostat} function which takes in
a version and might convert it before spawing the thermostat.

Goblins has a @code{versioned} function provided which allows the first
argument to be a version tag which usually is an integer but could be
any atomic serializable data such as a simple or even string and as a
second argument the self-portrait data. If the self-portrait doesn't
return a versioned portrait, Goblins will assign the version 0 to that
portrait data. Later you're able to match on it and upgrade it like the
example above.

With the above example newly created objects which are created using
Celcius will not be need to be upgraded, but the old fahrenheit objects
will be converted.

@node Persistence stores
@section Persistence stores

Persistence stores are an abstraction used primarily for vats, however
they can also be used with actormaps too. They are used to save and
retrieve data from different backing stores and other storage
mechanisms.

Currently Goblins provides two stores, the first is an in memory store
where nothing is persisted and the second is a syrup store, which
reads and writes to files, serializing the data in the Syrup
serialization format.

Note: Stores are currently not designed in a thread safe mannor so
care should be taken to ensure they are only accessed by one vat.

@node Memory Store
@subsection Memory Store

The memory store keeps everything within memory and does not persist
it. This is mostly good for testing.

The memory store can be found in @code{(goblins persistence-store
memory)}.

@deffn {Procedure} make-memory-store

Returns a memory store.

@end deffn

@node Syrup Store
@subsection Syrup Store

This provides a persistent storage mechanism which serializes the data
to a file in syrup format.

The memory store can be found in @code{(goblins persistence-store
syrup)}.

More informaiton about the Syrup serialization format can be found
here: @uref{https://github.com/ocapn/syrup}

@deffn {Procedure} make-syrup-store backing-filename

Returns a syrup store which stores the data in a file specified in
@var{backing-file}.

@end deffn
